export type PublicQaKnowledgeSeed = {
  id: string;
  key: string;
  title: string;
  category: string;
  audience: "public" | "party" | "employee" | "admin";
  keywords: string[];
  answer: string;
  sourceLabel: string;
  sourceUrl: string;
  priority: number;
  isActive: boolean;
};

const SOURCE_ALETA = "ALETA Public Knowledge";
const SOURCE_IDENTITY = "ALETA Public Knowledge - Identitas Instansi";
const SOURCE_ECOURT = "ALETA Public Knowledge - e-Court MA RI";
const SOURCE_SIWAS = "ALETA Public Knowledge - SIWAS MA RI";
const SOURCE_DIRPUT = "ALETA Public Knowledge - Direktori Putusan MA RI";
const SOURCE_EBERPADU = "ALETA Public Knowledge - e-Berpadu MA RI";
const SOURCE_BADILAG = "ALETA Public Knowledge - Ditjen Badilag MA RI";
const SOURCE_JDIH = "ALETA Public Knowledge - JDIH MA RI";
const SOURCE_EKEPEGAWAIAN = "ALETA Public Knowledge - E-Kepegawaian";

export const DEFAULT_PUBLIC_QA_KNOWLEDGE: PublicQaKnowledgeSeed[] = [
  {
    id: "pqk-info-kontak-resmi",
    key: "info_kontak_resmi_pengadilan",
    title: "Kontak Resmi Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["kontak pengadilan", "nomor pengadilan", "whatsapp pengadilan", "telepon pengadilan", "email pengadilan"],
    answer:
      "Kontak resmi {{court_name}}:\nTelepon: {{phone}}\nCS WhatsApp resmi: {{cs_whatsapp_number}}\nWhatsApp Bot informasi: {{bot_whatsapp_number}}\nEmail: {{email}}\nWebsite: {{website}}\n\nGunakan kanal resmi tersebut untuk memastikan informasi layanan terbaru.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 95,
    isActive: true,
  },
  {
    id: "pqk-info-alamat-lokasi",
    key: "info_alamat_lokasi_pengadilan",
    title: "Alamat dan Lokasi Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["alamat pengadilan", "lokasi pengadilan", "maps pengadilan", "dimana pengadilan", "kantor pengadilan"],
    answer:
      "Alamat {{court_name}}:\n{{address}}\n\nJika tersedia, gunakan tautan peta dari website/portal resmi pengadilan agar tidak salah lokasi.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 94,
    isActive: true,
  },
  {
    id: "pqk-info-jam-layanan",
    key: "info_jam_layanan_pengadilan",
    title: "Jam Layanan Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["jam layanan", "jam buka", "hari kerja", "ptsp buka", "pelayanan buka"],
    answer:
      "Layanan pengadilan umumnya dilayani pada hari kerja. Untuk jam layanan terbaru, hari libur, atau perubahan jadwal khusus, mohon cek website resmi {{court_name}} atau hubungi PTSP.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 92,
    isActive: true,
  },
  {
    id: "pqk-info-website-resmi",
    key: "info_website_resmi_pengadilan",
    title: "Website Resmi Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["website pengadilan", "situs pengadilan", "web resmi", "informasi resmi"],
    answer:
      "Website resmi {{court_name}} adalah {{website}}.\n\nInformasi layanan, pengumuman, jadwal, standar pelayanan, dan kontak terbaru sebaiknya dicek dari website resmi atau PTSP pengadilan.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 90,
    isActive: true,
  },
  {
    id: "pqk-identitas-profil-satker",
    key: "identitas_profil_pengadilan_saat_ini",
    title: "Profil Pengadilan Saat Ini",
    category: "informasi_umum",
    audience: "public",
    keywords: ["pengadilan ini", "profil pengadilan", "nama pengadilan", "satker pengadilan", "instansi pengadilan", "tentang pengadilan"],
    answer:
      "Instansi yang terhubung dengan layanan ini adalah {{court_name}}.\nNama singkat: {{court_short_name}}\nJenis instansi: {{court_type}}\nWilayah/nama satker: {{jurisdiction}}\nAlamat: {{address}}\nWebsite: {{website}}\n\nData ini mengikuti menu Identitas Instansi pada aplikasi ALETA.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 100,
    isActive: true,
  },
  {
    id: "pqk-identitas-nama-satker",
    key: "identitas_nama_singkat_satker",
    title: "Nama Resmi dan Nama Singkat Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["nama resmi pengadilan", "nama singkat", "singkatan pengadilan", "nama satker", "pa apa ini", "pn apa ini"],
    answer:
      "Nama resmi: {{court_name}}\nNama singkat: {{court_short_name}}\n\nJika ada perbedaan penulisan di dokumen layanan, gunakan nama resmi yang tercantum pada dokumen pengadilan.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 98,
    isActive: true,
  },
  {
    id: "pqk-identitas-wilayah-hukum",
    key: "identitas_wilayah_hukum_pengadilan",
    title: "Wilayah Hukum Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["wilayah hukum", "yurisdiksi pengadilan", "wilayah pengadilan", "daerah kewenangan", "pengadilan wilayah mana"],
    answer:
      "{{court_name}} adalah {{court_type}} dengan wilayah/nama satker {{jurisdiction}}.\n\nUntuk memastikan apakah alamat pihak termasuk kewenangan pengadilan ini, mohon konfirmasi ke PTSP karena kewenangan relatif mengikuti ketentuan dan data alamat perkara.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 94,
    isActive: true,
  },
  {
    id: "pqk-identitas-alamat-lengkap",
    key: "identitas_alamat_lengkap_instansi",
    title: "Alamat Lengkap dari Identitas Instansi",
    category: "informasi_umum",
    audience: "public",
    keywords: ["alamat lengkap pengadilan", "alamat kantor", "lokasi kantor", "kantor pengadilan dimana", "alamat satker"],
    answer:
      "Alamat {{court_name}}:\n{{address}}\n\nJika Bapak/Ibu akan datang langsung, sebaiknya konfirmasi jam layanan dan kebutuhan dokumen terlebih dahulu melalui kontak resmi pengadilan.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 96,
    isActive: true,
  },
  {
    id: "pqk-identitas-google-maps",
    key: "identitas_titik_google_maps",
    title: "Titik Google Maps Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["google maps pengadilan", "titik maps", "lokasi maps", "rute ke pengadilan", "arah ke pengadilan"],
    answer:
      "Titik peta {{court_name}}:\n{{map_url}}\n\nJika tautan peta belum tersedia, silakan cek alamat pada website resmi atau hubungi PTSP agar tidak salah lokasi.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 93,
    isActive: true,
  },
  {
    id: "pqk-identitas-telepon-resmi",
    key: "identitas_telepon_resmi_instansi",
    title: "Nomor Telepon Resmi Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["telepon pengadilan", "nomor telepon", "nomor kantor", "hubungi kantor", "kontak telepon"],
    answer:
      "Nomor telepon {{court_name}}:\n{{phone}}\n\nGunakan nomor resmi ini untuk informasi layanan. Jangan mengikuti arahan pembayaran atau permintaan data dari nomor pribadi yang tidak jelas.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 95,
    isActive: true,
  },
  {
    id: "pqk-identitas-whatsapp-resmi",
    key: "identitas_whatsapp_resmi_instansi",
    title: "Nomor WhatsApp Resmi Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["whatsapp pengadilan", "wa pengadilan", "nomor wa", "chat pengadilan", "kontak whatsapp"],
    answer:
      "Nomor CS WhatsApp resmi {{court_name}}:\n{{cs_whatsapp_number}}\nLink chat: {{cs_whatsapp_chat_url}}\n\nSaat menghubungi, tuliskan nama dan kebutuhan layanan secara singkat. Untuk data perkara, cukup sebutkan nomor perkara bila diminta petugas.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 96,
    isActive: true,
  },
  {
    id: "pqk-identitas-bot-whatsapp",
    key: "identitas_whatsapp_bot_informasi",
    title: "WhatsApp Bot Informasi Realtime",
    category: "informasi_umum",
    audience: "public",
    keywords: ["whatsapp bot", "nomor bot", "bot informasi", "bot ai", "aleta bot", "informasi realtime"],
    answer:
      "Nomor WhatsApp Bot informasi {{court_name}}:\n{{bot_whatsapp_number}}\nLink chat: {{bot_whatsapp_chat_url}}\n\nNomor ini dipakai untuk informasi otomatis/realtime. Jika membutuhkan petugas manusia, hubungi CS WhatsApp resmi: {{cs_whatsapp_number}}.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 95,
    isActive: true,
  },
  {
    id: "pqk-identitas-bicara-petugas",
    key: "identitas_bicara_dengan_petugas_cs",
    title: "Bicara dengan CS atau Petugas Manusia",
    category: "layanan",
    audience: "public",
    keywords: ["bicara petugas", "bicara manusia", "hubungi cs", "customer service", "operator", "admin manusia", "minta petugas", "mau bicara petugas"],
    answer:
      "Baik, untuk berbicara dengan petugas/CS manusia {{court_name}}, silakan hubungi:\nCS WhatsApp resmi: {{cs_whatsapp_number}}\nLink chat: {{cs_whatsapp_chat_url}}\n\nMohon tuliskan nama, kebutuhan layanan, dan nomor perkara jika sudah ada. Jangan mengirim data pribadi berlebihan sebelum diminta petugas resmi.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 99,
    isActive: true,
  },
  {
    id: "pqk-hr-layanan-tanpa-login",
    key: "e_kepegawaian_layanan_tanpa_login",
    title: "E-Kepegawaian Tanpa Login",
    category: "layanan_pegawai",
    audience: "public",
    keywords: [
      "cuti tanpa login",
      "ajukan cuti tanpa login",
      "setor pck",
      "setor skp",
      "laporan wfa",
      "lambat datang",
      "pulang cepat",
      "agenda rapat pegawai",
      "e kepegawaian publik",
      "layanan pegawai tanpa login",
    ],
    answer:
      "Layanan E-Kepegawaian ALETA tanpa login tersedia untuk pegawai melalui tiga cara:\n1. URL langsung: /public/e-kepegawaian\n2. Menu Login ALETA: pilih bagian Layanan tanpa login.\n3. WhatsApp resmi: minta tautan layanan dari Bot/CS, lalu isi data pada halaman publik ALETA.\n\nLayanan yang tersedia: permohonan cuti, penyetoran PCK, penyetoran SKP, laporan WFA, permohonan lambat datang, permohonan pulang cepat, cek status tiket, dan agenda/hasil rapat publik.\n\nDemi keamanan, jangan kirim NIP/NIK lengkap, password, atau lampiran pribadi melalui chat bila belum diminta petugas resmi.",
    sourceLabel: SOURCE_EKEPEGAWAIAN,
    sourceUrl: "/public/e-kepegawaian",
    priority: 98,
    isActive: true,
  },
  {
    id: "pqk-hr-format-whatsapp-aman",
    key: "e_kepegawaian_format_whatsapp_aman",
    title: "Format Aman WhatsApp E-Kepegawaian",
    category: "layanan_pegawai",
    audience: "public",
    keywords: [
      "format whatsapp cuti",
      "format wa cuti",
      "cara whatsapp cuti",
      "whatsapp e kepegawaian",
      "minta link cuti",
      "minta link skp",
      "minta link pck",
      "minta link wfa",
    ],
    answer:
      "Format aman untuk WhatsApp E-Kepegawaian:\nAssalamu'alaikum. Saya ingin menggunakan layanan [nama layanan] E-Kepegawaian ALETA tanpa login. Mohon tautan form publik dan panduan aman.\n\nUntuk permohonan cuti, buka /public/e-kepegawaian/cuti lalu gunakan tombol Kirim Chat Cuti. Sistem akan membuat format khusus:\nMODE: EKEPEGAWAIAN_PERMOHONAN_CUTI\nNama: [nama]\nNIP/NIK/Nomor Pegawai: [identitas pegawai]\nNomor HP: [nomor aktif]\nJenis Cuti: [jenis cuti]\nTanggal Mulai: [YYYY-MM-DD]\nTanggal Selesai: [YYYY-MM-DD]\nAlasan: [alasan]\nAlamat Selama Cuti: [alamat]\n\nPeriksa ulang isi chat sebelum dikirim. Jangan kirim password atau dokumen sensitif yang tidak diperlukan.",
    sourceLabel: SOURCE_EKEPEGAWAIAN,
    sourceUrl: "/public/e-kepegawaian",
    priority: 97,
    isActive: true,
  },
  {
    id: "pqk-hr-statistik-cuti",
    key: "e_kepegawaian_statistik_cuti",
    title: "Statistik dan Permintaan Cuti E-Kepegawaian",
    category: "layanan_pegawai",
    audience: "public",
    keywords: [
      "statistik cuti",
      "berapa pegawai cuti hari ini",
      "permintaan cuti aleta bot",
      "simulasi persentase cuti",
      "pegawai cuti hari ini",
      "dashboard cuti",
    ],
    answer:
      "ALETA Bot dapat membantu permintaan cuti melalui format aman WhatsApp:\nMODE: EKEPEGAWAIAN_PERMOHONAN_CUTI\nNama: [nama]\nNIP/NIK/Nomor Pegawai: [identitas pegawai]\nNomor HP: [nomor aktif]\nJenis Cuti: [jenis cuti]\nTanggal Mulai: [YYYY-MM-DD]\nTanggal Selesai: [YYYY-MM-DD]\nAlasan: [alasan]\nAlamat Selama Cuti: [alamat]\n\nStatistik cuti, daftar permintaan cuti, dan simulasi persentase pegawai cuti per tanggal tersedia di ALETA > E-Kepegawaian > Dashboard/Cuti untuk role internal yang berwenang. Informasi statistik pegawai tidak dikirim sebagai data rinci melalui WhatsApp publik demi perlindungan data pribadi.",
    sourceLabel: SOURCE_EKEPEGAWAIAN,
    sourceUrl: "/e-kepegawaian?section=cuti",
    priority: 96,
    isActive: true,
  },
  {
    id: "pqk-identitas-email-resmi",
    key: "identitas_email_resmi_instansi",
    title: "Email Resmi Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["email pengadilan", "alamat email", "kirim email", "surat elektronik pengadilan"],
    answer:
      "Email resmi {{court_name}}:\n{{email}}\n\nGunakan subjek yang jelas dan cantumkan kontak yang dapat dihubungi. Jangan mengirim dokumen pribadi berlebihan jika belum diminta petugas.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 92,
    isActive: true,
  },
  {
    id: "pqk-identitas-kanal-digital",
    key: "identitas_kanal_digital_resmi",
    title: "Kanal Digital Resmi Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["kanal resmi", "akun resmi", "media sosial resmi", "website dan sosial media", "sosmed pengadilan"],
    answer:
      "Kanal digital {{court_name}}:\nWebsite: {{website}}\nInstagram: {{instagram}}\nFacebook: {{facebook}}\nYouTube: {{youtube}}\n\nPastikan kanal yang dipakai sesuai data Identitas Instansi/website resmi pengadilan.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 89,
    isActive: true,
  },
  {
    id: "pqk-identitas-instagram",
    key: "identitas_instagram_resmi",
    title: "Instagram Resmi Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["instagram resmi", "ig pengadilan", "akun instagram", "instagram pengadilan"],
    answer:
      "Instagram resmi {{court_name}}:\n{{instagram}}\n\nJika belum tercantum, cek website resmi pengadilan atau hubungi PTSP untuk memastikan akun yang benar.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 78,
    isActive: true,
  },
  {
    id: "pqk-identitas-facebook",
    key: "identitas_facebook_resmi",
    title: "Facebook Resmi Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["facebook resmi", "fb pengadilan", "akun facebook", "facebook pengadilan"],
    answer:
      "Facebook resmi {{court_name}}:\n{{facebook}}\n\nJika belum tercantum, cek website resmi pengadilan atau hubungi PTSP untuk memastikan akun yang benar.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 77,
    isActive: true,
  },
  {
    id: "pqk-identitas-youtube",
    key: "identitas_youtube_resmi",
    title: "YouTube Resmi Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["youtube resmi", "kanal youtube", "channel youtube", "youtube pengadilan"],
    answer:
      "YouTube resmi {{court_name}}:\n{{youtube}}\n\nJika belum tercantum, cek website resmi pengadilan atau hubungi PTSP untuk memastikan kanal yang benar.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 76,
    isActive: true,
  },
  {
    id: "pqk-info-ptsp",
    key: "info_ptsp_pengadilan",
    title: "PTSP Pengadilan",
    category: "layanan",
    audience: "public",
    keywords: ["ptsp", "pelayanan terpadu satu pintu", "loket pengadilan", "petugas layanan"],
    answer:
      "PTSP adalah tempat utama untuk meminta informasi layanan pengadilan, menyerahkan berkas, mengambil produk layanan, dan bertanya prosedur. Petugas akan membantu sesuai jenis layanan dan data yang Bapak/Ibu bawa.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 88,
    isActive: true,
  },
  {
    id: "pqk-info-pengunjung-pertama",
    key: "info_panduan_pengunjung_pertama",
    title: "Panduan Datang ke Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["baru pertama ke pengadilan", "datang ke pengadilan", "apa yang dibawa", "pengunjung pengadilan"],
    answer:
      "Jika baru pertama datang ke pengadilan, siapkan identitas diri, dokumen terkait layanan/perkara, nomor kontak aktif, dan datang ke PTSP. Petugas akan membantu mengarahkan loket atau layanan yang sesuai.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 86,
    isActive: true,
  },
  {
    id: "pqk-info-layanan-disabilitas",
    key: "info_layanan_disabilitas",
    title: "Layanan Disabilitas dan Prioritas",
    category: "layanan",
    audience: "public",
    keywords: ["disabilitas", "difabel", "kursi roda", "layanan prioritas", "lansia", "ibu hamil"],
    answer:
      "Jika Bapak/Ibu membutuhkan layanan prioritas, pendampingan disabilitas, kursi roda, atau bantuan akses, silakan sampaikan kepada petugas keamanan/PTSP saat datang atau hubungi pengadilan lebih dulu.",
    sourceLabel: SOURCE_BADILAG,
    sourceUrl: "https://badilag.mahkamahagung.go.id/",
    priority: 84,
    isActive: true,
  },
  {
    id: "pqk-info-etika-layanan",
    key: "info_etika_layanan_pengadilan",
    title: "Etika Saat Menghubungi Pengadilan",
    category: "informasi_umum",
    audience: "public",
    keywords: ["cara chat pengadilan", "bertanya ke pengadilan", "etika layanan", "menghubungi ptsp"],
    answer:
      "Saat menghubungi pengadilan, tuliskan nama, kebutuhan layanan, dan nomor perkara jika sudah ada. Hindari mengirim data pribadi yang tidak diminta. Untuk perkara berjalan, informasi resmi tetap mengikuti data pengadilan dan ketentuan hukum acara.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 82,
    isActive: true,
  },
  {
    id: "pqk-info-media-sosial-resmi",
    key: "info_media_sosial_resmi",
    title: "Media Sosial Resmi",
    category: "informasi_umum",
    audience: "public",
    keywords: ["instagram pengadilan", "facebook pengadilan", "youtube pengadilan", "media sosial"],
    answer:
      "Media sosial resmi {{court_name}}:\nInstagram: {{instagram}}\nFacebook: {{facebook}}\nYouTube: {{youtube}}\n\nPastikan akun yang diikuti terhubung dari website resmi agar terhindar dari akun tidak resmi.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 70,
    isActive: true,
  },
  {
    id: "pqk-identitas-validasi-kanal-resmi",
    key: "identitas_validasi_kanal_resmi",
    title: "Cara Memastikan Kanal Resmi",
    category: "informasi_umum",
    audience: "public",
    keywords: ["akun palsu", "nomor palsu", "pastikan resmi", "validasi kanal resmi", "rekening pribadi", "penipuan pengadilan"],
    answer:
      "Untuk memastikan kanal resmi {{court_name}}, cocokkan informasi dengan website {{website}}, kontak PTSP, atau media sosial yang tercantum pada Identitas Instansi.\n\nAbaikan permintaan pembayaran ke rekening pribadi atau permintaan data rahasia dari akun yang tidak jelas.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 91,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-umum",
    key: "pendaftaran_perkara_umum",
    title: "Pendaftaran Perkara Umum",
    category: "pendaftaran",
    audience: "public",
    keywords: ["pendaftaran perkara", "daftar perkara", "cara daftar perkara", "mengajukan perkara", "gugatan", "permohonan"],
    answer:
      "Untuk pendaftaran perkara, siapkan identitas, nomor kontak aktif, dokumen pendukung, dan uraian singkat permohonan/gugatan. Pendaftaran dapat dilakukan melalui PTSP atau e-Court jika memenuhi syarat. Petugas akan memeriksa kelengkapan dan memberi arahan biaya serta tahapan berikutnya.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 96,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-informasi",
    key: "informasi_pendaftaran_layanan_pengadilan",
    title: "Informasi Pendaftaran Layanan Pengadilan",
    category: "pendaftaran",
    audience: "public",
    keywords: ["informasi pendaftaran", "daftar layanan pengadilan", "pendaftaran layanan", "syarat pendaftaran", "mendaftar layanan"],
    answer:
      "Informasi pendaftaran layanan pengadilan bergantung pada jenis layanan yang diminta. Secara umum, siapkan identitas, dokumen pendukung, nomor kontak aktif, dan datang/konfirmasi ke PTSP. Jika layanan bisa elektronik, petugas dapat mengarahkan ke e-Court atau kanal resmi lain.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 95,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-cerai-gugat",
    key: "pendaftaran_cerai_gugat",
    title: "Pendaftaran Cerai Gugat",
    category: "pendaftaran",
    audience: "public",
    keywords: ["cerai gugat", "istri menggugat cerai", "daftar cerai gugat", "syarat cerai gugat"],
    answer:
      "Untuk cerai gugat, pihak penggugat biasanya menyiapkan identitas, buku nikah/akta nikah, alamat pihak tergugat, dan dokumen pendukung sesuai keadaan perkara. Syarat rinci dapat berbeda, jadi mohon konfirmasi ke PTSP atau Posbakum bila membutuhkan bantuan menyusun gugatan.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 90,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-cerai-talak",
    key: "pendaftaran_cerai_talak",
    title: "Pendaftaran Cerai Talak",
    category: "pendaftaran",
    audience: "public",
    keywords: ["cerai talak", "suami mengajukan cerai", "daftar cerai talak", "permohonan cerai talak"],
    answer:
      "Untuk cerai talak, pihak pemohon biasanya menyiapkan identitas, buku nikah/akta nikah, alamat pihak termohon, dan dokumen pendukung. Petugas PTSP/Posbakum dapat membantu memastikan kelengkapan administrasi dan alur pendaftaran.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 89,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-dispensasi-kawin",
    key: "pendaftaran_dispensasi_kawin",
    title: "Pendaftaran Dispensasi Kawin",
    category: "pendaftaran",
    audience: "public",
    keywords: ["dispensasi kawin", "dispensasi nikah", "anak belum cukup umur menikah", "daftar dispensasi kawin"],
    answer:
      "Dispensasi kawin diajukan jika ada calon mempelai yang belum memenuhi batas usia perkawinan menurut ketentuan. Siapkan identitas para pihak, dokumen calon mempelai, dokumen orang tua/wali, dan dokumen pendukung lain. Konfirmasi syarat rinci ke PTSP karena dapat bergantung pada kondisi perkara.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 86,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-itsbat-nikah",
    key: "pendaftaran_itsbat_nikah",
    title: "Pendaftaran Itsbat Nikah",
    category: "pendaftaran",
    audience: "public",
    keywords: ["itsbat nikah", "isbat nikah", "pengesahan nikah", "nikah belum tercatat"],
    answer:
      "Itsbat nikah umumnya diajukan untuk meminta penetapan pengesahan perkawinan yang belum tercatat. Siapkan identitas, data perkawinan, dokumen pendukung, dan informasi saksi bila diperlukan. Untuk rincian syarat, silakan konfirmasi ke PTSP/Posbakum.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 84,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-wali-adhal",
    key: "pendaftaran_wali_adhal",
    title: "Pendaftaran Wali Adhal",
    category: "pendaftaran",
    audience: "public",
    keywords: ["wali adhal", "wali nikah menolak", "permohonan wali adhal"],
    answer:
      "Permohonan wali adhal dapat diajukan jika terdapat persoalan wali nikah yang perlu diperiksa pengadilan. Siapkan identitas, data calon mempelai, informasi wali, dan dokumen pendukung. Petugas PTSP dapat membantu memeriksa kebutuhan administrasi awal.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 82,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-harta-bersama",
    key: "pendaftaran_harta_bersama",
    title: "Pendaftaran Perkara Harta Bersama",
    category: "pendaftaran",
    audience: "public",
    keywords: ["harta bersama", "gono gini", "harta gono gini", "pembagian harta"],
    answer:
      "Untuk perkara harta bersama, siapkan identitas, uraian objek harta, bukti awal kepemilikan bila ada, dan alamat para pihak. Pengadilan tidak dapat memberi strategi perkara, tetapi PTSP/Posbakum dapat membantu informasi administrasi dan pembuatan dokumen sesuai ketentuan.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 80,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-waris",
    key: "pendaftaran_perkara_waris",
    title: "Pendaftaran Perkara Waris",
    category: "pendaftaran",
    audience: "public",
    keywords: ["waris", "ahli waris", "pembagian waris", "penetapan ahli waris"],
    answer:
      "Untuk layanan/perkara waris, siapkan identitas para pihak, hubungan keluarga, dokumen pewaris, dan dokumen pendukung lain sesuai kebutuhan. Karena jenis layanan waris bisa berbeda, mohon konfirmasi rincian administrasi ke PTSP/Posbakum.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 78,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-asal-usul-anak",
    key: "pendaftaran_asal_usul_anak",
    title: "Pendaftaran Asal Usul Anak",
    category: "pendaftaran",
    audience: "public",
    keywords: ["asal usul anak", "penetapan anak", "akta anak", "anak"],
    answer:
      "Permohonan asal usul anak memerlukan identitas pemohon, data anak, dokumen perkawinan/kelahiran yang tersedia, dan dokumen pendukung lain. Petugas PTSP dapat membantu memeriksa kelengkapan awal sesuai prosedur.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 76,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-dokumen-identitas",
    key: "syarat_identitas_dokumen_umum",
    title: "Dokumen Identitas Umum",
    category: "pendaftaran",
    audience: "public",
    keywords: ["dokumen identitas", "ktp", "kartu keluarga", "dokumen syarat", "berkas pendaftaran"],
    answer:
      "Dokumen umum yang sering diminta adalah identitas diri, kartu keluarga, dokumen perkawinan/kelahiran bila relevan, alamat pihak lawan, dan dokumen pendukung perkara. Jangan mengirim foto identitas melalui chat jika tidak diminta petugas resmi.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 75,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-kuasa-hukum",
    key: "pendaftaran_melalui_kuasa_hukum",
    title: "Pendaftaran Melalui Kuasa Hukum",
    category: "pendaftaran",
    audience: "public",
    keywords: ["kuasa hukum", "advokat", "surat kuasa", "daftar lewat pengacara"],
    answer:
      "Jika menggunakan kuasa hukum/advokat, pastikan surat kuasa dan dokumen pendukung disiapkan. Advokat umumnya memakai e-Court sebagai pengguna terdaftar. Untuk pengguna non-advokat, petugas PTSP dapat memberi arahan jalur pendaftaran yang tersedia.",
    sourceLabel: SOURCE_ECOURT,
    sourceUrl: "https://ecourt.mahkamahagung.go.id/",
    priority: 74,
    isActive: true,
  },
  {
    id: "pqk-pendaftaran-gugatan-mandiri",
    key: "gugatan_mandiri",
    title: "Gugatan Mandiri",
    category: "pendaftaran",
    audience: "public",
    keywords: ["gugatan mandiri", "buat gugatan sendiri", "surat gugatan", "surat permohonan"],
    answer:
      "Jika tersedia di pengadilan, layanan gugatan mandiri membantu masyarakat menyusun draft gugatan/permohonan secara lebih tertib. Bila bingung memilih format atau uraian, minta arahan PTSP/Posbakum tanpa meminta strategi untuk memenangkan perkara.",
    sourceLabel: SOURCE_BADILAG,
    sourceUrl: "https://badilag.mahkamahagung.go.id/",
    priority: 72,
    isActive: true,
  },
  {
    id: "pqk-bantuan-hukum-posbakum",
    key: "layanan_posbakum",
    title: "Pos Bantuan Hukum",
    category: "bantuan_hukum",
    audience: "public",
    keywords: ["posbakum", "bantuan hukum", "gratis bantuan hukum", "konsultasi hukum gratis", "buat gugatan gratis"],
    answer:
      "Posbakum adalah layanan bantuan hukum di pengadilan untuk masyarakat yang membutuhkan, terutama yang kurang mampu atau kesulitan membuat dokumen hukum. Layanan dapat berupa informasi, konsultasi/advis hukum terbatas, dan bantuan pembuatan dokumen sesuai ketentuan.",
    sourceLabel: SOURCE_BADILAG,
    sourceUrl: "https://badilag.mahkamahagung.go.id/",
    priority: 92,
    isActive: true,
  },
  {
    id: "pqk-bantuan-hukum-prodeo",
    key: "perkara_prodeo_pembebasan_biaya",
    title: "Perkara Prodeo / Pembebasan Biaya",
    category: "bantuan_hukum",
    audience: "public",
    keywords: ["prodeo", "gratis biaya perkara", "tidak mampu bayar perkara", "pembebasan biaya"],
    answer:
      "Perkara prodeo adalah permohonan pembebasan biaya perkara bagi masyarakat tidak mampu sesuai ketentuan dan ketersediaan anggaran. Biasanya diperlukan dokumen keterangan tidak mampu atau dokumen pendukung sejenis. Konfirmasi syarat terbaru ke PTSP.",
    sourceLabel: SOURCE_BADILAG,
    sourceUrl: "https://badilag.mahkamahagung.go.id/",
    priority: 90,
    isActive: true,
  },
  {
    id: "pqk-ecourt-pengertian",
    key: "ecourt_pengertian",
    title: "Pengertian e-Court",
    category: "ecourt",
    audience: "public",
    keywords: ["ecourt", "e-court", "perkara online", "daftar online", "pengadilan elektronik"],
    answer:
      "e-Court adalah layanan Mahkamah Agung untuk administrasi perkara secara elektronik, antara lain pendaftaran perkara, taksiran panjar, pembayaran, pemanggilan/pemberitahuan elektronik, dan persidangan elektronik sesuai ketentuan.",
    sourceLabel: SOURCE_ECOURT,
    sourceUrl: "https://ecourt.mahkamahagung.go.id/",
    priority: 98,
    isActive: true,
  },
  {
    id: "pqk-ecourt-efiling",
    key: "ecourt_efiling_pendaftaran",
    title: "e-Filing / Pendaftaran Online",
    category: "ecourt",
    audience: "public",
    keywords: ["efiling", "e filing", "pendaftaran online", "unggah gugatan", "daftar perkara online"],
    answer:
      "e-Filing dipakai untuk pendaftaran perkara secara elektronik. Berkas pendaftaran dikirim melalui aplikasi e-Court pada pengadilan yang sudah aktif. Pastikan akun, dokumen, dan pilihan pengadilan sudah benar sebelum mengirim.",
    sourceLabel: SOURCE_ECOURT,
    sourceUrl: "https://ecourt.mahkamahagung.go.id/",
    priority: 94,
    isActive: true,
  },
  {
    id: "pqk-ecourt-pengguna-terdaftar",
    key: "ecourt_pengguna_terdaftar_advokat",
    title: "Pengguna Terdaftar e-Court",
    category: "ecourt",
    audience: "public",
    keywords: ["pengguna terdaftar", "akun advokat", "daftar akun ecourt", "register advokat"],
    answer:
      "Pengguna terdaftar e-Court antara lain advokat yang telah memiliki akun dan melalui proses validasi sesuai ketentuan. Untuk kendala akun, gunakan kanal resmi e-Court atau hubungi petugas pengadilan terkait.",
    sourceLabel: SOURCE_ECOURT,
    sourceUrl: "https://ecourt.mahkamahagung.go.id/",
    priority: 88,
    isActive: true,
  },
  {
    id: "pqk-ecourt-pengguna-lain",
    key: "ecourt_pengguna_lain_non_advokat",
    title: "Pengguna Lain e-Court",
    category: "ecourt",
    audience: "public",
    keywords: ["pengguna lain", "non advokat ecourt", "masyarakat ecourt", "akun perorangan"],
    answer:
      "Selain advokat, ada pengguna lain/non-advokat yang dapat menggunakan layanan elektronik jika sudah terdaftar dan memenuhi ketentuan. Untuk pendaftaran atau kendala akses, konfirmasi ke PTSP atau kanal resmi e-Court.",
    sourceLabel: SOURCE_ECOURT,
    sourceUrl: "https://ecourt.mahkamahagung.go.id/",
    priority: 86,
    isActive: true,
  },
  {
    id: "pqk-ecourt-epayment",
    key: "ecourt_epayment_pembayaran",
    title: "e-Payment / Pembayaran Panjar",
    category: "ecourt",
    audience: "public",
    keywords: ["epayment", "e payment", "virtual account", "bayar panjar online", "nomor pembayaran"],
    answer:
      "Pada e-Court, pendaftar memperoleh taksiran panjar dan nomor pembayaran/virtual account setelah pendaftaran. Pembayaran harus mengikuti tagihan sistem. Jika ada kendala pembayaran, segera hubungi petugas pengadilan atau kanal resmi e-Court.",
    sourceLabel: SOURCE_ECOURT,
    sourceUrl: "https://ecourt.mahkamahagung.go.id/",
    priority: 86,
    isActive: true,
  },
  {
    id: "pqk-ecourt-esummons",
    key: "ecourt_esummons_panggilan_elektronik",
    title: "e-Summons / Panggilan Elektronik",
    category: "ecourt",
    audience: "public",
    keywords: ["esummons", "e summons", "panggilan elektronik", "pemberitahuan elektronik", "email panggilan"],
    answer:
      "e-Summons adalah pemanggilan/pemberitahuan secara elektronik melalui domisili elektronik yang terdaftar. Pihak yang memakai e-Court perlu rutin memeriksa akun/email agar tidak melewatkan panggilan atau pemberitahuan.",
    sourceLabel: SOURCE_ECOURT,
    sourceUrl: "https://ecourt.mahkamahagung.go.id/",
    priority: 84,
    isActive: true,
  },
  {
    id: "pqk-ecourt-elitigation",
    key: "ecourt_elitigation_persidangan_elektronik",
    title: "e-Litigation / Persidangan Elektronik",
    category: "ecourt",
    audience: "public",
    keywords: ["elitigation", "e litigation", "sidang online", "persidangan elektronik", "upload jawaban"],
    answer:
      "e-Litigation mendukung persidangan elektronik, termasuk pengiriman dokumen persidangan seperti jawaban, replik, duplik, dan kesimpulan sesuai jadwal serta ketentuan majelis/hukum acara.",
    sourceLabel: SOURCE_ECOURT,
    sourceUrl: "https://ecourt.mahkamahagung.go.id/",
    priority: 82,
    isActive: true,
  },
  {
    id: "pqk-ecourt-kendala-login",
    key: "ecourt_kendala_login_akun",
    title: "Kendala Login e-Court",
    category: "ecourt",
    audience: "public",
    keywords: ["ecourt tidak bisa login", "lupa password ecourt", "reset password ecourt", "akun ecourt bermasalah"],
    answer:
      "Jika tidak bisa login e-Court, gunakan fitur bantuan/reset yang tersedia pada aplikasi e-Court dan cek email termasuk folder spam. Jika masih terkendala, hubungi kanal resmi e-Court atau petugas pengadilan.",
    sourceLabel: SOURCE_ECOURT,
    sourceUrl: "https://ecourt.mahkamahagung.go.id/",
    priority: 80,
    isActive: true,
  },
  {
    id: "pqk-pengaduan-siwas",
    key: "pengaduan_siwas_ma",
    title: "Pengaduan Melalui SIWAS",
    category: "pengaduan",
    audience: "public",
    keywords: ["siwas", "pengaduan ma", "lapor pelanggaran", "melapor hakim", "lapor aparatur"],
    answer:
      "Untuk dugaan pelanggaran aparatur pengadilan, Bapak/Ibu dapat memakai SIWAS Mahkamah Agung. Tuliskan kronologi, waktu/ tempat kejadian, pihak terkait, dan bukti pendukung bila ada. Identitas pelapor/terlapor dijaga kerahasiaannya sesuai ketentuan SIWAS.",
    sourceLabel: SOURCE_SIWAS,
    sourceUrl: "https://siwas.mahkamahagung.go.id/",
    priority: 96,
    isActive: true,
  },
  {
    id: "pqk-pengaduan-layanan-ptsp",
    key: "pengaduan_layanan_ptsp",
    title: "Pengaduan Layanan PTSP",
    category: "pengaduan",
    audience: "public",
    keywords: ["pengaduan layanan", "komplain pelayanan", "keluhan ptsp", "pelayanan tidak baik"],
    answer:
      "Untuk keluhan layanan, sampaikan kronologi singkat, tanggal kejadian, loket/unit terkait, dan kontak yang dapat dihubungi. Pengaduan dapat disampaikan melalui kanal pengaduan resmi pengadilan atau SIWAS jika terkait dugaan pelanggaran aparatur.",
    sourceLabel: SOURCE_SIWAS,
    sourceUrl: "https://siwas.mahkamahagung.go.id/",
    priority: 88,
    isActive: true,
  },
  {
    id: "pqk-pengaduan-gratifikasi-pungli",
    key: "pengaduan_gratifikasi_pungli",
    title: "Pengaduan Gratifikasi atau Pungli",
    category: "pengaduan",
    audience: "public",
    keywords: ["pungli", "gratifikasi", "suap", "diminta uang", "bayar petugas", "anti penyuapan"],
    answer:
      "Jika ada dugaan pungli, gratifikasi, atau permintaan uang di luar ketentuan resmi, jangan menyerahkan uang/barang. Simpan bukti bila ada dan laporkan melalui kanal pengaduan resmi pengadilan atau SIWAS Mahkamah Agung.",
    sourceLabel: SOURCE_SIWAS,
    sourceUrl: "https://siwas.mahkamahagung.go.id/",
    priority: 94,
    isActive: true,
  },
  {
    id: "pqk-pengaduan-bukan-konsultasi",
    key: "pengaduan_bukan_konsultasi_hukum",
    title: "Pengaduan Bukan Konsultasi Hukum",
    category: "pengaduan",
    audience: "public",
    keywords: ["pengaduan perkara", "tidak puas putusan", "mau lapor putusan", "hakim salah"],
    answer:
      "Pengaduan digunakan untuk melaporkan dugaan pelanggaran perilaku atau layanan, bukan untuk meminta perubahan putusan. Jika tidak setuju dengan putusan, gunakan upaya hukum sesuai ketentuan dan tenggat waktu yang berlaku.",
    sourceLabel: SOURCE_SIWAS,
    sourceUrl: "https://siwas.mahkamahagung.go.id/",
    priority: 78,
    isActive: true,
  },
  {
    id: "pqk-layanan-akta-cerai-umum",
    key: "layanan_akta_cerai_umum",
    title: "Informasi Akta Cerai",
    category: "akta_cerai",
    audience: "public",
    keywords: ["akta cerai", "ambil akta cerai", "akta cerai sudah jadi", "status akta cerai"],
    answer:
      "Akta cerai dapat diproses setelah perkara berkekuatan hukum tetap dan administrasi selesai. Untuk mengecek status akta berdasarkan nomor perkara, gunakan layanan cek akta jika tersedia atau hubungi PTSP.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 90,
    isActive: true,
  },
  {
    id: "pqk-layanan-akta-cerai-syarat",
    key: "syarat_pengambilan_akta_cerai",
    title: "Syarat Pengambilan Akta Cerai",
    category: "akta_cerai",
    audience: "public",
    keywords: ["syarat ambil akta cerai", "dokumen ambil akta", "mengambil akta cerai", "kuasa ambil akta"],
    answer:
      "Untuk mengambil akta cerai, siapkan identitas asli, informasi nomor perkara, dan bukti pembayaran/administrasi bila diperlukan. Jika diwakilkan, biasanya diperlukan surat kuasa dan identitas penerima kuasa. Konfirmasi syarat terbaru ke PTSP.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 88,
    isActive: true,
  },
  {
    id: "pqk-layanan-validasi-akta-cerai",
    key: "validasi_akta_cerai",
    title: "Validasi Akta Cerai",
    category: "akta_cerai",
    audience: "public",
    keywords: ["validasi akta cerai", "cek akta cerai asli", "akta cerai palsu", "verifikasi akta"],
    answer:
      "Untuk validasi akta cerai, siapkan nomor akta/nomor perkara dan identitas terkait. Gunakan kanal resmi pengadilan agar petugas dapat memeriksa data sesuai prosedur dan menjaga kerahasiaan data pribadi.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 84,
    isActive: true,
  },
  {
    id: "pqk-layanan-salinan-putusan",
    key: "layanan_salinan_putusan",
    title: "Salinan Putusan atau Penetapan",
    category: "layanan",
    audience: "public",
    keywords: ["salinan putusan", "salinan penetapan", "ambil putusan", "copy putusan", "minutasi"],
    answer:
      "Untuk meminta salinan putusan/penetapan, siapkan identitas, nomor perkara, dan jelaskan hubungan/kepentingan hukum Bapak/Ibu. Petugas akan memeriksa ketersediaan dokumen dan prosedur pengambilannya.",
    sourceLabel: SOURCE_DIRPUT,
    sourceUrl: "https://putusan3.mahkamahagung.go.id/",
    priority: 86,
    isActive: true,
  },
  {
    id: "pqk-layanan-direktori-putusan",
    key: "informasi_direktori_putusan_ma",
    title: "Direktori Putusan Mahkamah Agung",
    category: "informasi_publik",
    audience: "public",
    keywords: ["direktori putusan", "putusan mahkamah agung", "cari putusan", "putusan online"],
    answer:
      "Direktori Putusan MA memuat arsip putusan yang dapat dicari berdasarkan klasifikasi, pengadilan, tahun, atau kata kunci tertentu. Data yang tampil di direktori mengikuti publikasi resmi dan anonimisasi yang berlaku.",
    sourceLabel: SOURCE_DIRPUT,
    sourceUrl: "https://putusan3.mahkamahagung.go.id/",
    priority: 84,
    isActive: true,
  },
  {
    id: "pqk-layanan-biaya-panjar-umum",
    key: "informasi_biaya_panjar_perkara",
    title: "Informasi Biaya Panjar Perkara",
    category: "biaya_panjar",
    audience: "public",
    keywords: ["biaya perkara", "panjar biaya", "berapa biaya cerai", "biaya daftar perkara", "skum"],
    answer:
      "Biaya/panjar perkara bergantung pada jenis perkara, radius panggilan, jumlah pihak, dan ketentuan biaya setempat. Untuk angka resmi, minta taksiran panjar dari PTSP atau gunakan e-Court jika pendaftaran dilakukan secara elektronik.",
    sourceLabel: SOURCE_ECOURT,
    sourceUrl: "https://ecourt.mahkamahagung.go.id/",
    priority: 90,
    isActive: true,
  },
  {
    id: "pqk-layanan-sisa-panjar",
    key: "informasi_sisa_panjar_pengembalian",
    title: "Sisa Panjar dan Pengembalian",
    category: "biaya_panjar",
    audience: "public",
    keywords: ["sisa panjar", "pengembalian panjar", "ambil sisa biaya", "biaya perkara kembali"],
    answer:
      "Sisa panjar dapat ditanyakan ke kasir/PTSP dengan menyebut nomor perkara. Pengembalian mengikuti data keuangan perkara dan prosedur pengadilan. Siapkan identitas dan dokumen pendukung saat mengambil.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 86,
    isActive: true,
  },
  {
    id: "pqk-persidangan-jadwal-sidang",
    key: "informasi_jadwal_sidang_umum",
    title: "Informasi Jadwal Sidang",
    category: "persidangan",
    audience: "public",
    keywords: ["jadwal sidang", "kapan sidang", "sidang hari ini", "ruang sidang", "agenda sidang"],
    answer:
      "Jadwal sidang dapat dicek melalui papan informasi, website, SIPP/e-Court jika tersedia, atau PTSP. Untuk perkara tertentu, siapkan nomor perkara agar petugas dapat membantu mengecek data yang benar.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 88,
    isActive: true,
  },
  {
    id: "pqk-persidangan-hadir-sidang",
    key: "panduan_hadir_sidang",
    title: "Panduan Hadir Sidang",
    category: "persidangan",
    audience: "public",
    keywords: ["hadir sidang", "apa dibawa sidang", "sidang pertama", "datang sidang"],
    answer:
      "Saat hadir sidang, bawa identitas, panggilan/pemberitahuan sidang jika ada, dokumen yang relevan, dan datang lebih awal. Ikuti arahan petugas serta panggilan dari ruang sidang.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 82,
    isActive: true,
  },
  {
    id: "pqk-persidangan-panggilan-resmi",
    key: "panggilan_sidang_resmi",
    title: "Panggilan Sidang Resmi",
    category: "persidangan",
    audience: "public",
    keywords: ["panggilan sidang", "surat panggilan", "relaas", "jurusita", "dipanggil sidang"],
    answer:
      "Panggilan sidang resmi disampaikan sesuai ketentuan hukum acara oleh petugas yang berwenang atau melalui kanal elektronik jika perkara memakai e-Court. Pesan WhatsApp bersifat bantuan informasi dan tidak menggantikan panggilan resmi.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 85,
    isActive: true,
  },
  {
    id: "pqk-persidangan-penundaan",
    key: "penundaan_sidang",
    title: "Penundaan Sidang",
    category: "persidangan",
    audience: "public",
    keywords: ["sidang ditunda", "penundaan sidang", "jadwal berubah", "sidang batal"],
    answer:
      "Jika sidang ditunda atau jadwal berubah, informasi resmi mengikuti penetapan/agenda persidangan. Cek kembali melalui PTSP, SIPP/e-Court, atau panggilan/pemberitahuan resmi agar tidak salah jadwal.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 82,
    isActive: true,
  },
  {
    id: "pqk-persidangan-mediasi",
    key: "informasi_mediasi_pengadilan",
    title: "Mediasi di Pengadilan",
    category: "mediasi",
    audience: "public",
    keywords: ["mediasi", "mediator", "perdamaian", "sidang mediasi"],
    answer:
      "Mediasi adalah proses penyelesaian sengketa dengan bantuan mediator sesuai ketentuan. Hadiri jadwal mediasi, siapkan identitas dan dokumen penting, serta ikuti arahan mediator. Bot tidak dapat memberi strategi atau menjamin hasil mediasi.",
    sourceLabel: SOURCE_JDIH,
    sourceUrl: "https://jdih.mahkamahagung.go.id/legal-product/perma-nomor-1-tahun-2016/detail",
    priority: 84,
    isActive: true,
  },
  {
    id: "pqk-persidangan-bukti-saksi",
    key: "informasi_bukti_dan_saksi",
    title: "Bukti dan Saksi",
    category: "persidangan",
    audience: "public",
    keywords: ["bukti sidang", "saksi sidang", "dokumen bukti", "membawa saksi"],
    answer:
      "Untuk bukti dan saksi, ikuti arahan majelis/petugas sesuai tahap persidangan. Siapkan dokumen asli dan salinan bila diperlukan. Bot hanya memberi informasi umum, bukan nasihat strategi perkara.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 72,
    isActive: true,
  },
  {
    id: "pqk-persidangan-sidang-keliling",
    key: "informasi_sidang_keliling",
    title: "Sidang Keliling / Sidang di Luar Gedung",
    category: "layanan",
    audience: "public",
    keywords: ["sidang keliling", "sidang luar gedung", "pelayanan terpadu", "mobile court"],
    answer:
      "Sidang keliling atau sidang di luar gedung dapat dilaksanakan oleh pengadilan tertentu sesuai program dan jadwal. Untuk ketersediaan di wilayah Bapak/Ibu, silakan cek pengumuman website {{court_name}} atau hubungi PTSP.",
    sourceLabel: SOURCE_BADILAG,
    sourceUrl: "https://badilag.mahkamahagung.go.id/",
    priority: 70,
    isActive: true,
  },
  {
    id: "pqk-eberpadu-pengertian",
    key: "eberpadu_pengertian",
    title: "Pengertian e-Berpadu",
    category: "instansi_terkait",
    audience: "public",
    keywords: ["eberpadu", "e-berpadu", "berkas pidana elektronik", "izin besuk tahanan", "pinjam barang bukti"],
    answer:
      "e-Berpadu adalah layanan elektronik berkas pidana terpadu Mahkamah Agung untuk integrasi layanan pidana tertentu, seperti izin penggeledahan, penyitaan, penahanan, pelimpahan berkas, izin besuk tahanan, dan layanan terkait sesuai kewenangan.",
    sourceLabel: SOURCE_EBERPADU,
    sourceUrl: "https://eberpadu.mahkamahagung.go.id/",
    priority: 86,
    isActive: true,
  },
  {
    id: "pqk-eberpadu-izin-besuk",
    key: "eberpadu_izin_besuk_tahanan",
    title: "Izin Besuk Tahanan Online",
    category: "instansi_terkait",
    audience: "public",
    keywords: ["izin besuk tahanan", "besuk tahanan online", "cek izin besuk", "eberpadu besuk"],
    answer:
      "Untuk layanan izin besuk tahanan online, gunakan e-Berpadu jika layanan tersedia untuk perkara/wilayah terkait. Setelah mengajukan, simpan nomor register agar dapat mengecek status pengajuan.",
    sourceLabel: SOURCE_EBERPADU,
    sourceUrl: "https://eberpadu.mahkamahagung.go.id/",
    priority: 80,
    isActive: true,
  },
  {
    id: "pqk-instansi-kua-data-perceraian",
    key: "instansi_kua_data_perceraian",
    title: "Koordinasi KUA terkait Data Perceraian",
    category: "instansi_terkait",
    audience: "public",
    keywords: ["kua", "data perceraian kua", "lapor cerai ke kua", "status perkawinan kua"],
    answer:
      "Untuk kebutuhan pencatatan atau konfirmasi data perceraian dengan KUA, gunakan dokumen resmi seperti akta cerai atau salinan putusan/penetapan sesuai kebutuhan. Jika instansi memerlukan konfirmasi, arahkan melalui surat/kanal resmi pengadilan.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 72,
    isActive: true,
  },
  {
    id: "pqk-instansi-dukcapil-status",
    key: "instansi_dukcapil_status_perkawinan",
    title: "Koordinasi Dukcapil terkait Status Perkawinan",
    category: "instansi_terkait",
    audience: "public",
    keywords: ["dukcapil", "ubah status ktp", "status perkawinan", "kartu keluarga setelah cerai"],
    answer:
      "Untuk perubahan data kependudukan setelah putusan/akta cerai, Bapak/Ibu biasanya perlu membawa dokumen resmi ke Dukcapil sesuai ketentuan Dukcapil. Pengadilan dapat memberi produk hukum/akta sesuai prosedur, sedangkan perubahan data dilakukan oleh Dukcapil.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 72,
    isActive: true,
  },
  {
    id: "pqk-instansi-kepolisian",
    key: "instansi_kepolisian_koordinasi",
    title: "Koordinasi dengan Kepolisian",
    category: "instansi_terkait",
    audience: "public",
    keywords: ["kepolisian", "polisi", "permintaan data perkara", "surat dari polisi"],
    answer:
      "Permintaan data dari kepolisian atau instansi penegak hukum sebaiknya diajukan melalui surat/kanal resmi. Pengadilan akan memproses sesuai kewenangan, kerahasiaan data, dan ketentuan administrasi yang berlaku.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 68,
    isActive: true,
  },
  {
    id: "pqk-instansi-desa-kelurahan",
    key: "instansi_desa_kelurahan_panggilan",
    title: "Koordinasi Desa/Kelurahan",
    category: "instansi_terkait",
    audience: "public",
    keywords: ["desa", "kelurahan", "panggilan lewat desa", "surat keterangan desa", "domisili"],
    answer:
      "Desa/kelurahan dapat terlibat dalam kebutuhan administrasi seperti keterangan domisili atau penyampaian panggilan sesuai prosedur. Untuk dokumen yang diperlukan, ikuti arahan PTSP atau petugas yang berwenang.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 66,
    isActive: true,
  },
  {
    id: "pqk-instansi-bank-pos",
    key: "instansi_bank_pos_pembayaran",
    title: "Pembayaran melalui Bank/Pos",
    category: "instansi_terkait",
    audience: "public",
    keywords: ["bayar lewat bank", "bayar lewat pos", "virtual account", "rekening pengadilan", "pembayaran panjar"],
    answer:
      "Pembayaran panjar perkara harus mengikuti nomor pembayaran/virtual account atau instruksi resmi dari pengadilan/e-Court. Jangan transfer ke rekening pribadi. Jika ragu, konfirmasi ke kasir/PTSP sebelum membayar.",
    sourceLabel: SOURCE_ECOURT,
    sourceUrl: "https://ecourt.mahkamahagung.go.id/",
    priority: 78,
    isActive: true,
  },
  {
    id: "pqk-informasi-publik-permohonan",
    key: "permohonan_informasi_publik",
    title: "Permohonan Informasi Publik",
    category: "informasi_publik",
    audience: "public",
    keywords: ["informasi publik", "ppid", "minta informasi", "permohonan informasi"],
    answer:
      "Permohonan informasi publik dapat diajukan melalui kanal informasi/PPID pengadilan jika tersedia. Sebutkan identitas pemohon, informasi yang diminta, tujuan penggunaan informasi, dan kontak yang dapat dihubungi.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 78,
    isActive: true,
  },
  {
    id: "pqk-informasi-publik-keberatan",
    key: "keberatan_informasi_publik",
    title: "Keberatan atas Layanan Informasi",
    category: "informasi_publik",
    audience: "public",
    keywords: ["keberatan informasi", "ppid keberatan", "informasi tidak diberikan", "permohonan informasi ditolak"],
    answer:
      "Jika permohonan informasi belum dijawab atau ditolak, Bapak/Ibu dapat menanyakan alasan dan mekanisme keberatan melalui kanal PPID/layanan informasi pengadilan sesuai ketentuan keterbukaan informasi publik.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 66,
    isActive: true,
  },
  {
    id: "pqk-informasi-publik-statistik",
    key: "informasi_statistik_perkara",
    title: "Statistik Perkara",
    category: "informasi_publik",
    audience: "public",
    keywords: ["statistik perkara", "jumlah perkara", "data perkara pengadilan", "laporan perkara"],
    answer:
      "Statistik perkara biasanya tersedia melalui laporan resmi, website pengadilan, atau pusat data yang dikelola badan peradilan terkait. Untuk data rinci, ajukan permohonan informasi melalui kanal resmi.",
    sourceLabel: SOURCE_BADILAG,
    sourceUrl: "https://badilag.mahkamahagung.go.id/",
    priority: 64,
    isActive: true,
  },
  {
    id: "pqk-keamanan-data-pribadi",
    key: "keamanan_data_pribadi_layanan",
    title: "Keamanan Data Pribadi",
    category: "informasi_umum",
    audience: "public",
    keywords: ["data pribadi", "ktp aman", "kirim ktp", "rahasia data", "nomor hp"],
    answer:
      "Jangan mengirim KTP, KK, buku nikah, nomor rekening, atau dokumen pribadi melalui chat jika tidak diminta petugas resmi. Untuk verifikasi, gunakan kanal resmi pengadilan dan pastikan nomor/akun yang dihubungi benar.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 90,
    isActive: true,
  },
  {
    id: "pqk-keamanan-putusan-strategi",
    key: "batasan_bot_tidak_memberi_strategi",
    title: "Batasan Bot untuk Nasihat Hukum",
    category: "informasi_umum",
    audience: "public",
    keywords: ["cara menang perkara", "strategi sidang", "hakim memutus apa", "pasti menang", "nasihat hukum"],
    answer:
      "Bot tidak dapat memberi strategi memenangkan perkara, memprediksi putusan, atau menghubungkan ke hakim. Untuk bantuan administrasi, hubungi PTSP/Posbakum. Untuk nasihat hukum pribadi, silakan berkonsultasi dengan penasihat hukum yang berwenang.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 98,
    isActive: true,
  },
  {
    id: "pqk-fallback-info-resmi",
    key: "informasi_resmi_belum_tersedia",
    title: "Informasi Resmi Belum Tersedia",
    category: "fallback",
    audience: "public",
    keywords: ["tidak ada informasi", "belum ada info", "informasi belum tersedia", "saya tidak menemukan"],
    answer:
      "Saya belum menemukan informasi resmi yang cukup untuk menjawab detail tersebut. Agar tidak keliru, silakan cek website {{court_name}} di {{website}} atau hubungi CS WhatsApp resmi: {{cs_whatsapp_number}}.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 40,
    isActive: true,
  },
  {
    id: "pqk-fallback-layanan-umum",
    key: "tanya_layanan_umum_pengadilan",
    title: "Pertanyaan Layanan Umum",
    category: "fallback",
    audience: "public",
    keywords: ["layanan pengadilan", "informasi layanan", "butuh bantuan pengadilan", "bantuan layanan"],
    answer:
      "Untuk layanan umum pengadilan, Bapak/Ibu dapat menyebutkan kebutuhan secara singkat, misalnya pendaftaran perkara, akta cerai, salinan putusan, jadwal sidang, biaya perkara, e-Court, pengaduan, atau informasi PTSP.",
    sourceLabel: SOURCE_ALETA,
    sourceUrl: "{{website}}",
    priority: 42,
    isActive: true,
  },
  {
    id: "pqk-fallback-bahasa-formal",
    key: "peringatan_gunakan_bahasa_formal_baku",
    title: "Gunakan Bahasa Formal dan Jelas",
    category: "fallback",
    audience: "public",
    keywords: ["bahasa tidak jelas", "singkatan", "tmpt", "dmn", "gmn", "brp", "chat tidak jelas"],
    answer:
      "Mohon gunakan bahasa Indonesia yang lebih jelas, lengkap, dan baku agar bot dapat memahami pertanyaan Bapak/Ibu.\n\nContoh:\n- Bukan: tmpt pengadilan?\n- Tulis: Di mana alamat pengadilan?\n\nJika ingin bicara langsung dengan petugas, hubungi CS WhatsApp resmi: {{cs_whatsapp_number}}.",
    sourceLabel: SOURCE_IDENTITY,
    sourceUrl: "{{website}}",
    priority: 98,
    isActive: true,
  },
];
