import { type AletaDatabase } from "@/server/db/client";

const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS roles (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS positions (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    unit_kerja TEXT NOT NULL,
    level_hierarchy INTEGER NOT NULL,
    reports_to_position_id TEXT,
    disposition_target_position_ids_json TEXT NOT NULL DEFAULT '[]',
    can_forward_to_leadership SMALLINT NOT NULL DEFAULT 0,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_positions_reports_to
      FOREIGN KEY (reports_to_position_id) REFERENCES positions(id)
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    nip TEXT,
    email TEXT NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT TRUE,
    whatsapp_number TEXT NOT NULL,
    profile_photo_url TEXT,
    role_id TEXT NOT NULL,
    position_id TEXT NOT NULL,
    is_active SMALLINT NOT NULL DEFAULT 1,
    can_bypass_hierarchy SMALLINT NOT NULL DEFAULT 0,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_users_position FOREIGN KEY (position_id) REFERENCES positions(id)
  )`,
  `CREATE TABLE IF NOT EXISTS acting_assignments (
    id TEXT PRIMARY KEY,
    user_id_pengganti TEXT NOT NULL,
    jabatan_id_target TEXT NOT NULL,
    tipe TEXT NOT NULL CHECK (tipe IN ('PLH', 'PLT')),
    role_id_target TEXT NOT NULL,
    assigned_by_user_id TEXT NOT NULL,
    authorized_by_user_id TEXT NOT NULL,
    tanggal_mulai TEXT NOT NULL,
    tanggal_selesai TEXT,
    assigned_at TEXT NOT NULL,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_acting_user FOREIGN KEY (user_id_pengganti) REFERENCES users(id),
    CONSTRAINT fk_acting_position FOREIGN KEY (jabatan_id_target) REFERENCES positions(id),
    CONSTRAINT fk_acting_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_acting_authorized_by FOREIGN KEY (authorized_by_user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS ai_global_settings (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    enabled SMALLINT NOT NULL DEFAULT 1,
    active_provider_id TEXT NOT NULL,
    active_model_id TEXT NOT NULL,
    active_connection_id TEXT,
    primary_language TEXT NOT NULL DEFAULT 'id',
    feature_flags_json TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS ai_providers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    provider_id TEXT,
    endpoint_url TEXT,
    api_key TEXT NOT NULL DEFAULT '',
    masked_api_key TEXT NOT NULL DEFAULT '',
    models_json TEXT NOT NULL DEFAULT '[]',
    model_id TEXT,
    builtin SMALLINT NOT NULL DEFAULT 0,
    connection_status TEXT NOT NULL DEFAULT 'idle',
    is_active SMALLINT NOT NULL DEFAULT 0,
    last_tested_at TEXT,
    last_connection_message TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS ai_suggestion_logs (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    feature TEXT NOT NULL,
    status TEXT NOT NULL,
    provider_id TEXT,
    model_id TEXT,
    duration_ms INTEGER NOT NULL DEFAULT 0,
    fallback_reason TEXT NOT NULL DEFAULT '',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    CONSTRAINT fk_ai_suggestion_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS whatsapp_web_settings (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    phone_number TEXT NOT NULL DEFAULT '',
    session_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'inactive',
    last_connected_at TEXT,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS assistant_judge_settings (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    enabled SMALLINT NOT NULL DEFAULT 1,
    visible_roles_json TEXT NOT NULL DEFAULT '[]',
    links_json TEXT NOT NULL DEFAULT '{}',
    updated_by TEXT,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_assistant_judge_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_settings (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    bot_enabled SMALLINT NOT NULL DEFAULT 0,
    notifications_enabled SMALLINT NOT NULL DEFAULT 0,
    admin_whatsapp_number TEXT NOT NULL DEFAULT '',
    message_delay_ms INTEGER NOT NULL DEFAULT 1500,
    retry_limit INTEGER NOT NULL DEFAULT 2,
    dry_run_enabled SMALLINT NOT NULL DEFAULT 1,
    schedule_cron TEXT NOT NULL DEFAULT '00 07 * * Monday-Friday',
    test_target_number TEXT NOT NULL DEFAULT '',
    security_notes TEXT NOT NULL DEFAULT '',
    disposition_deadline_reminder_enabled SMALLINT NOT NULL DEFAULT 0,
    disposition_deadline_reminder_mode TEXT NOT NULL DEFAULT 'dry_run',
    disposition_deadline_reminder_approved_at TEXT,
    disposition_deadline_reminder_approved_by TEXT,
    disposition_deadline_reminder_last_run_at TEXT,
    disposition_deadline_reminder_last_status TEXT NOT NULL DEFAULT 'idle',
    disposition_deadline_reminder_last_message TEXT,
    disposition_deadline_reminder_pilot_user_ids_json TEXT NOT NULL DEFAULT '[]',
    disposition_deadline_reminder_pilot_role_ids_json TEXT NOT NULL DEFAULT '[]',
    disposition_deadline_reminder_pilot_position_ids_json TEXT NOT NULL DEFAULT '[]',
    disposition_deadline_reminder_scheduler_enabled SMALLINT NOT NULL DEFAULT 0,
    disposition_deadline_reminder_scheduler_mode TEXT NOT NULL DEFAULT 'dry_run',
    disposition_deadline_reminder_scheduler_time TEXT NOT NULL DEFAULT '08:00:00',
    disposition_deadline_reminder_scheduler_last_run_at TEXT,
    disposition_deadline_reminder_scheduler_last_message TEXT,
    disposition_deadline_reminder_kill_switch SMALLINT NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_templates (
    id TEXT PRIMARY KEY,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    placeholders_json TEXT NOT NULL DEFAULT '[]',
    editable SMALLINT NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_jobs (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    enabled SMALLINT NOT NULL DEFAULT 0,
    schedule_cron TEXT NOT NULL,
    last_run_at TEXT,
    last_status TEXT NOT NULL DEFAULT 'idle',
    last_message TEXT,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_queries (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL CHECK (category IN ('employee', 'party', 'system')),
    description TEXT NOT NULL DEFAULT '',
    sql_text TEXT NOT NULL,
    output_columns_json TEXT NOT NULL DEFAULT '[]',
    recipient_column TEXT NOT NULL DEFAULT '',
    connection_key TEXT NOT NULL DEFAULT 'sipp_primary',
    is_active SMALLINT NOT NULL DEFAULT 1,
    last_tested_at TEXT,
    last_test_status TEXT NOT NULL DEFAULT 'idle',
    last_test_error TEXT,
    created_by TEXT,
    updated_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_aleta_bot_queries_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_aleta_bot_queries_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_db_connections (
    id TEXT PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    driver TEXT NOT NULL DEFAULT 'mysql',
    host TEXT NOT NULL,
    port INTEGER NOT NULL DEFAULT 3306,
    database_name TEXT NOT NULL,
    username TEXT NOT NULL,
    password_env_key TEXT NOT NULL DEFAULT '',
    password_secret TEXT NOT NULL DEFAULT '',
    password_source TEXT NOT NULL DEFAULT 'env',
    ssl_enabled SMALLINT NOT NULL DEFAULT 0,
    connection_timeout_ms INTEGER NOT NULL DEFAULT 5000,
    is_active SMALLINT NOT NULL DEFAULT 1,
    is_default SMALLINT NOT NULL DEFAULT 0,
    legacy_source TEXT NOT NULL DEFAULT '',
    last_test_status TEXT NOT NULL DEFAULT 'idle',
    last_test_error TEXT,
    last_test_at TEXT,
    created_by TEXT,
    updated_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_aleta_bot_db_connections_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_aleta_bot_db_connections_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_public_qa_intents (
    id TEXT PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT 'informasi_umum',
    audience TEXT NOT NULL DEFAULT 'party',
    is_active SMALLINT NOT NULL DEFAULT 1,
    ai_enabled SMALLINT NOT NULL DEFAULT 0,
    exact_triggers_json TEXT NOT NULL DEFAULT '[]',
    example_questions_json TEXT NOT NULL DEFAULT '[]',
    required_parameters_json TEXT NOT NULL DEFAULT '[]',
    query_key TEXT NOT NULL DEFAULT '',
    legacy_handler TEXT NOT NULL DEFAULT '',
    legacy_command TEXT NOT NULL DEFAULT '',
    parameterized_legacy_command TEXT NOT NULL DEFAULT '',
    template_key TEXT NOT NULL DEFAULT '',
    response_mode TEXT NOT NULL DEFAULT 'legacy_handler',
    confidence_threshold REAL NOT NULL DEFAULT 0.65,
    requires_verification SMALLINT NOT NULL DEFAULT 0,
    requires_case_number SMALLINT NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 2,
    fallback_message TEXT NOT NULL DEFAULT '',
    risk_level TEXT NOT NULL DEFAULT 'low',
    notes TEXT NOT NULL DEFAULT '',
    created_by TEXT,
    updated_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_aleta_bot_public_qa_intents_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_aleta_bot_public_qa_intents_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_public_qa_examples (
    id TEXT PRIMARY KEY,
    intent_id TEXT NOT NULL,
    question_text TEXT NOT NULL,
    normalized_question TEXT NOT NULL DEFAULT '',
    is_active SMALLINT NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_aleta_bot_public_qa_examples_intent FOREIGN KEY (intent_id) REFERENCES aleta_bot_public_qa_intents(id)
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_public_qa_logs (
    id TEXT PRIMARY KEY,
    sender_number TEXT NOT NULL DEFAULT '',
    sender_name TEXT NOT NULL DEFAULT '',
    raw_message TEXT NOT NULL DEFAULT '',
    normalized_message TEXT NOT NULL DEFAULT '',
    matched_intent_key TEXT NOT NULL DEFAULT '',
    matched_method TEXT NOT NULL DEFAULT 'fallback',
    confidence REAL NOT NULL DEFAULT 0,
    parameters_json TEXT NOT NULL DEFAULT '{}',
    query_key TEXT NOT NULL DEFAULT '',
    response_preview TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'fallback',
    error_message TEXT,
    needs_human_review SMALLINT NOT NULL DEFAULT 0,
    review_status TEXT NOT NULL DEFAULT 'pending',
    reviewed_by_user_id TEXT,
    reviewed_at TEXT,
    review_note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_public_qa_sessions (
    id TEXT PRIMARY KEY,
    sender_number TEXT NOT NULL,
    current_intent_key TEXT NOT NULL DEFAULT '',
    state TEXT NOT NULL DEFAULT 'collecting',
    collected_params_json TEXT NOT NULL DEFAULT '{}',
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_notifications (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL CHECK (category IN ('employee', 'party')),
    description TEXT NOT NULL DEFAULT '',
    query_id TEXT NOT NULL,
    template_id TEXT NOT NULL,
    recipient_source TEXT NOT NULL,
    recipient_mapping_json TEXT NOT NULL DEFAULT '{}',
    schedule_config_json TEXT NOT NULL DEFAULT '{}',
    is_active SMALLINT NOT NULL DEFAULT 0,
    delay_ms INTEGER NOT NULL DEFAULT 1500,
    retry_limit INTEGER NOT NULL DEFAULT 2,
    last_run_at TEXT,
    last_status TEXT NOT NULL DEFAULT 'idle',
    last_message TEXT,
    created_by TEXT,
    updated_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_aleta_bot_notifications_query FOREIGN KEY (query_id) REFERENCES aleta_bot_queries(id),
    CONSTRAINT fk_aleta_bot_notifications_template FOREIGN KEY (template_id) REFERENCES aleta_bot_templates(id),
    CONSTRAINT fk_aleta_bot_notifications_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_aleta_bot_notifications_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_notification_logs (
    id TEXT PRIMARY KEY,
    notification_id TEXT,
    query_id TEXT,
    recipient_number TEXT NOT NULL DEFAULT '',
    recipient_name TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL,
    message_preview TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL,
    error_message TEXT,
    source_app TEXT NOT NULL DEFAULT '',
    source_feature TEXT NOT NULL DEFAULT '',
    entity_type TEXT NOT NULL DEFAULT '',
    entity_id TEXT NOT NULL DEFAULT '',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    sent_at TEXT,
    created_at TEXT NOT NULL,
    CONSTRAINT fk_aleta_bot_notification_logs_notification FOREIGN KEY (notification_id) REFERENCES aleta_bot_notifications(id),
    CONSTRAINT fk_aleta_bot_notification_logs_query FOREIGN KEY (query_id) REFERENCES aleta_bot_queries(id)
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_logs (
    id TEXT PRIMARY KEY,
    level TEXT NOT NULL,
    event_type TEXT NOT NULL,
    message TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    actor_user_id TEXT,
    created_at TEXT NOT NULL,
    CONSTRAINT fk_aleta_bot_logs_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_policy_skip_logs (
    id TEXT PRIMARY KEY,
    notification_key TEXT NOT NULL DEFAULT '',
    notification_id TEXT,
    category TEXT NOT NULL DEFAULT '',
    reason TEXT NOT NULL DEFAULT 'unknown',
    source_feature TEXT NOT NULL DEFAULT '',
    entity_type TEXT NOT NULL DEFAULT '',
    entity_id TEXT NOT NULL DEFAULT '',
    recipient_type TEXT NOT NULL DEFAULT '',
    recipient_count INTEGER NOT NULL DEFAULT 0,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS aleta_bot_disposition_reminder_runs (
    id TEXT PRIMARY KEY,
    mode TEXT NOT NULL DEFAULT 'dry_run',
    triggered_by TEXT NOT NULL DEFAULT 'manual',
    triggered_by_user_id TEXT,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    total_candidates INTEGER NOT NULL DEFAULT 0,
    dry_run_created INTEGER NOT NULL DEFAULT 0,
    sent_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    error_count INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'simulated',
    summary_json TEXT NOT NULL DEFAULT '{}',
    CONSTRAINT fk_aleta_bot_disposition_reminder_runs_actor FOREIGN KEY (triggered_by_user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS institution_identity (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    court_name TEXT NOT NULL,
    court_short_name TEXT NOT NULL,
    address TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    mobile_phone TEXT NOT NULL,
    email TEXT NOT NULL,
    instagram TEXT,
    facebook TEXT,
    youtube TEXT,
    website TEXT,
    map_url TEXT,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS institution_identity_enrichments (
    court_id TEXT PRIMARY KEY,
    query_text TEXT,
    court_name TEXT NOT NULL,
    court_short_name TEXT NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    phone_number TEXT NOT NULL DEFAULT '',
    mobile_phone TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    instagram TEXT,
    facebook TEXT,
    youtube TEXT,
    website TEXT,
    map_url TEXT,
    source_official_website TEXT,
    source_google_place TEXT,
    source_google_search TEXT,
    sources_json TEXT NOT NULL DEFAULT '[]',
    fields_found_json TEXT NOT NULL DEFAULT '[]',
    fields_missing_json TEXT NOT NULL DEFAULT '[]',
    warnings_json TEXT NOT NULL DEFAULT '[]',
    confidence TEXT NOT NULL DEFAULT 'low',
    field_sources_json TEXT NOT NULL DEFAULT '{}',
    field_confidence_json TEXT NOT NULL DEFAULT '{}',
    enrichment_status TEXT NOT NULL DEFAULT 'catalog_only',
    last_enriched_at TEXT,
    last_error_message TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS module_visibility_settings (
    role_id TEXT NOT NULL,
    module_id TEXT NOT NULL,
    enabled SMALLINT NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (role_id, module_id),
    CONSTRAINT fk_module_visibility_role FOREIGN KEY (role_id) REFERENCES roles(id)
  )`,
  `CREATE TABLE IF NOT EXISTS feedback_requests (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('bug', 'feature', 'app_idea')),
    title TEXT NOT NULL,
    app_area TEXT NOT NULL,
    category TEXT NOT NULL,
    priority TEXT NOT NULL CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    description TEXT NOT NULL,
    reproduction_steps TEXT NOT NULL DEFAULT '',
    expected_result TEXT NOT NULL DEFAULT '',
    attachment_url TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'reviewed', 'in_progress', 'needs_info', 'planned', 'done', 'rejected', 'postponed', 'duplicate')),
    reporter_user_id TEXT NOT NULL,
    reporter_name TEXT NOT NULL,
    reporter_role TEXT NOT NULL,
    reporter_unit TEXT NOT NULL DEFAULT '',
    assigned_to_user_id TEXT,
    admin_note TEXT NOT NULL DEFAULT '',
    resolution_note TEXT NOT NULL DEFAULT '',
    duplicate_of_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    reviewed_at TEXT,
    completed_at TEXT,
    CONSTRAINT fk_feedback_reporter FOREIGN KEY (reporter_user_id) REFERENCES users(id),
    CONSTRAINT fk_feedback_assigned_to FOREIGN KEY (assigned_to_user_id) REFERENCES users(id),
    CONSTRAINT fk_feedback_duplicate FOREIGN KEY (duplicate_of_id) REFERENCES feedback_requests(id)
  )`,
  `CREATE TABLE IF NOT EXISTS user_notification_reads (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    seen_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_user_notification_reads_user FOREIGN KEY (user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS knowledge_base_regulations (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    source TEXT NOT NULL,
    jurisdiction TEXT NOT NULL,
    module_ids_json TEXT NOT NULL DEFAULT '[]',
    keywords_json TEXT NOT NULL DEFAULT '[]',
    summary TEXT NOT NULL,
    citation TEXT NOT NULL,
    recommended_position_ids_json TEXT NOT NULL DEFAULT '[]',
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS letter_origin_references (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS classification_catalog (
    code TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    category TEXT NOT NULL,
    keywords_json TEXT NOT NULL DEFAULT '[]',
    is_system SMALLINT NOT NULL DEFAULT 1,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS letter_number_sequences (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('masuk', 'keluar')),
    year INTEGER NOT NULL,
    last_sequence INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS letter_templates (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    body TEXT NOT NULL,
    placeholders_json TEXT NOT NULL DEFAULT '[]',
    is_active SMALLINT NOT NULL DEFAULT 1,
    created_by_user_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_letter_templates_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS letters (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('masuk', 'keluar')),
    nomor_surat TEXT NOT NULL,
    nomor_urut TEXT,
    tanggal_surat TEXT NOT NULL,
    tanggal_terima TEXT,
    tanggal_kirim TEXT,
    tanggal_administratif TEXT,
    pengirim TEXT NOT NULL,
    perihal TEXT NOT NULL,
    status TEXT NOT NULL,
    workflow_status TEXT NOT NULL DEFAULT 'sent',
    submitted_at TEXT,
    submitted_by_user_id TEXT,
    approved_at TEXT,
    approved_by_user_id TEXT,
    sent_at TEXT,
    sent_by_user_id TEXT,
    rejected_at TEXT,
    rejected_by_user_id TEXT,
    rejection_note TEXT,
    assigned_unit TEXT NOT NULL,
    confidentiality TEXT NOT NULL,
    current_disposition_id TEXT,
    ringkasan TEXT NOT NULL,
    asal_surat TEXT NOT NULL,
    tujuan_surat TEXT NOT NULL,
    klasifikasi_utama TEXT NOT NULL,
    kode_klasifikasi TEXT,
    lampiran_json TEXT NOT NULL DEFAULT '[]',
    tags_json TEXT NOT NULL DEFAULT '[]',
    klasifikasi_tags_json TEXT NOT NULL DEFAULT '[]',
    viewer_mode TEXT NOT NULL DEFAULT 'download',
    qr_code_label TEXT NOT NULL,
    document_aspect_ratio DOUBLE PRECISION,
    document_file_name TEXT,
    document_size_mb DOUBLE PRECISION,
    document_text_extract TEXT,
    document_file_path TEXT,
    target_position_id TEXT,
    target_user_id TEXT,
    created_by_user_id TEXT,
    search_document TEXT NOT NULL DEFAULT '',
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_letters_target_position FOREIGN KEY (target_position_id) REFERENCES positions(id),
    CONSTRAINT fk_letters_target_user FOREIGN KEY (target_user_id) REFERENCES users(id),
    CONSTRAINT fk_letters_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_letters_submitted_by FOREIGN KEY (submitted_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_letters_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_letters_sent_by FOREIGN KEY (sent_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_letters_rejected_by FOREIGN KEY (rejected_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_letters_classification FOREIGN KEY (kode_klasifikasi) REFERENCES classification_catalog(code)
  )`,
  `CREATE TABLE IF NOT EXISTS letter_tags (
    letter_id TEXT NOT NULL,
    tag_value TEXT NOT NULL,
    PRIMARY KEY (letter_id, tag_value),
    CONSTRAINT fk_letter_tags_letter FOREIGN KEY (letter_id) REFERENCES letters(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS letter_classification_tags (
    letter_id TEXT NOT NULL,
    tag_value TEXT NOT NULL,
    PRIMARY KEY (letter_id, tag_value),
    CONSTRAINT fk_letter_class_tags_letter FOREIGN KEY (letter_id) REFERENCES letters(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS letter_attachments (
    letter_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    PRIMARY KEY (letter_id, file_name),
    CONSTRAINT fk_letter_attachments_letter FOREIGN KEY (letter_id) REFERENCES letters(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS letter_whatsapp_deliveries (
    id TEXT PRIMARY KEY,
    letter_id TEXT NOT NULL,
    recipient_name TEXT NOT NULL,
    recipient_whatsapp TEXT NOT NULL,
    status TEXT NOT NULL,
    last_attempt_at TEXT NOT NULL,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_letter_whatsapp_letter FOREIGN KEY (letter_id) REFERENCES letters(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS dispositions (
    id TEXT PRIMARY KEY,
    surat_id TEXT NOT NULL,
    pengirim_id TEXT NOT NULL,
    penerima_id TEXT NOT NULL,
    target_position_id TEXT NOT NULL,
    instruksi TEXT NOT NULL,
    parent_disposition_id TEXT,
    status TEXT NOT NULL,
    allow_download SMALLINT NOT NULL DEFAULT 0,
    approval_qr_code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    deadline_at TEXT,
    read_at TEXT,
    read_by_user_id TEXT,
    urgent SMALLINT NOT NULL DEFAULT 0,
    bypass SMALLINT NOT NULL DEFAULT 0,
    routing_type TEXT NOT NULL DEFAULT 'standard',
    follow_up_note TEXT,
    follow_up_file_name TEXT,
    deleted_at TEXT,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_dispositions_letter FOREIGN KEY (surat_id) REFERENCES letters(id) ON DELETE CASCADE,
    CONSTRAINT fk_dispositions_sender FOREIGN KEY (pengirim_id) REFERENCES users(id),
    CONSTRAINT fk_dispositions_recipient FOREIGN KEY (penerima_id) REFERENCES users(id),
    CONSTRAINT fk_dispositions_read_by FOREIGN KEY (read_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_dispositions_target_position FOREIGN KEY (target_position_id) REFERENCES positions(id),
    CONSTRAINT fk_dispositions_parent FOREIGN KEY (parent_disposition_id) REFERENCES dispositions(id)
  )`,
  `CREATE TABLE IF NOT EXISTS disposition_whatsapp_deliveries (
    id TEXT PRIMARY KEY,
    disposition_id TEXT NOT NULL,
    recipient_name TEXT NOT NULL,
    recipient_whatsapp TEXT NOT NULL,
    status TEXT NOT NULL,
    last_attempt_at TEXT NOT NULL,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_disposition_whatsapp_disposition
      FOREIGN KEY (disposition_id) REFERENCES dispositions(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id TEXT PRIMARY KEY,
    actor_user_id TEXT,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    payload_json TEXT,
    created_at TEXT NOT NULL,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    access_token TEXT,
    refresh_token TEXT,
    id_token TEXT,
    access_token_expires_at TEXT,
    refresh_token_expires_at TEXT,
    scope TEXT,
    password TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    expires_at TEXT NOT NULL,
    token TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    user_id TEXT NOT NULL,
    CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS verifications (
    id TEXT PRIMARY KEY,
    identifier TEXT NOT NULL,
    value TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    created_at TEXT,
    updated_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS password_reset_requests (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    resolved_by_user_id TEXT,
    note TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    CONSTRAINT fk_prr_user FOREIGN KEY (user_id) REFERENCES users(id)
  )`,
];

const indexStatements = [
  `CREATE INDEX IF NOT EXISTS idx_positions_reports_to ON positions(reports_to_position_id, level_hierarchy)`,
  `CREATE INDEX IF NOT EXISTS idx_users_position_role ON users(position_id, role_id, deleted_at)`,
  `CREATE INDEX IF NOT EXISTS idx_acting_assignments_target ON acting_assignments(user_id_pengganti, jabatan_id_target, deleted_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_letter_number_sequences_unique ON letter_number_sequences(type, year)`,
  `CREATE INDEX IF NOT EXISTS idx_letter_templates_active ON letter_templates(is_active, category)`,
  `CREATE INDEX IF NOT EXISTS idx_letters_type_status ON letters(type, status, deleted_at)`,
  `CREATE INDEX IF NOT EXISTS idx_letters_workflow_status ON letters(type, workflow_status, deleted_at)`,
  `CREATE INDEX IF NOT EXISTS idx_letters_dates ON letters(tanggal_surat, tanggal_terima, tanggal_kirim)`,
  `CREATE INDEX IF NOT EXISTS idx_letters_origin_code ON letters(asal_surat, kode_klasifikasi)`,
  `CREATE INDEX IF NOT EXISTS idx_letter_tags_value ON letter_tags(tag_value, letter_id)`,
  `CREATE INDEX IF NOT EXISTS idx_letter_classification_tags_value ON letter_classification_tags(tag_value, letter_id)`,
  `CREATE INDEX IF NOT EXISTS idx_dispositions_letter_status ON dispositions(surat_id, status, deleted_at)`,
  `CREATE INDEX IF NOT EXISTS idx_dispositions_recipient ON dispositions(penerima_id, target_position_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_letter_whatsapp_letter ON letter_whatsapp_deliveries(letter_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_disposition_whatsapp_disposition ON disposition_whatsapp_deliveries(disposition_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_dispositions_deadline ON dispositions(deadline_at, status, deleted_at)`,
  `CREATE INDEX IF NOT EXISTS idx_ai_suggestion_logs_created ON ai_suggestion_logs(created_at DESC, feature, status)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_logs_created ON aleta_bot_logs(created_at DESC, event_type)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_policy_skip_logs_created ON aleta_bot_policy_skip_logs(created_at DESC, reason)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_policy_skip_logs_notification ON aleta_bot_policy_skip_logs(notification_key, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_disposition_reminder_runs_created ON aleta_bot_disposition_reminder_runs(started_at DESC, mode, status)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_templates_category ON aleta_bot_templates(category)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_queries_category ON aleta_bot_queries(category, is_active)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_db_connections_key ON aleta_bot_db_connections(key)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_db_connections_active ON aleta_bot_db_connections(is_active, is_default)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_public_qa_intents_active ON aleta_bot_public_qa_intents(is_active, audience)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_public_qa_logs_created ON aleta_bot_public_qa_logs(created_at DESC, status)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_public_qa_logs_review ON aleta_bot_public_qa_logs(needs_human_review, review_status, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_public_qa_sessions_sender ON aleta_bot_public_qa_sessions(sender_number, expires_at)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_notifications_category ON aleta_bot_notifications(category, is_active)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_notification_logs_created ON aleta_bot_notification_logs(created_at DESC, status)`,
  `CREATE INDEX IF NOT EXISTS idx_aleta_bot_notification_logs_entity ON aleta_bot_notification_logs(entity_type, entity_id, source_feature)`,
  `CREATE INDEX IF NOT EXISTS idx_feedback_requests_reporter ON feedback_requests(reporter_user_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_feedback_requests_admin ON feedback_requests(status, type, priority, created_at DESC)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_user_notification_reads_unique ON user_notification_reads(user_id, entity_type, entity_id)`,
  `CREATE INDEX IF NOT EXISTS idx_user_notification_reads_user ON user_notification_reads(user_id, entity_type, seen_at DESC)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_accounts_provider_account ON accounts(provider_id, account_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token)`,
  `CREATE INDEX IF NOT EXISTS idx_password_reset_requests_status ON password_reset_requests(user_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_letters_search_document_fts
    ON letters USING GIN (to_tsvector('simple', search_document))`,
];

const migrationStatements = [
  `ALTER TABLE ai_global_settings ADD COLUMN IF NOT EXISTS active_connection_id TEXT`,
  `ALTER TABLE ai_providers ADD COLUMN IF NOT EXISTS provider_id TEXT`,
  `ALTER TABLE ai_providers ADD COLUMN IF NOT EXISTS masked_api_key TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE ai_providers ADD COLUMN IF NOT EXISTS model_id TEXT`,
  `ALTER TABLE ai_providers ADD COLUMN IF NOT EXISTS last_tested_at TEXT`,
  `ALTER TABLE ai_providers ADD COLUMN IF NOT EXISTS last_connection_message TEXT`,
  `ALTER TABLE ai_global_settings ADD COLUMN IF NOT EXISTS feature_disposition_ai SMALLINT NOT NULL DEFAULT 1`,
  `ALTER TABLE ai_global_settings ADD COLUMN IF NOT EXISTS feature_mail_intelligence SMALLINT NOT NULL DEFAULT 1`,
  `ALTER TABLE ai_global_settings ADD COLUMN IF NOT EXISTS feature_draft_metadata SMALLINT NOT NULL DEFAULT 1`,
  `ALTER TABLE ai_global_settings ADD COLUMN IF NOT EXISTS feature_manajemen_surat_ai SMALLINT NOT NULL DEFAULT 1`,
  `ALTER TABLE ai_global_settings ADD COLUMN IF NOT EXISTS feature_disposisi_ai SMALLINT NOT NULL DEFAULT 1`,
  `ALTER TABLE ai_global_settings ADD COLUMN IF NOT EXISTS feature_flags_json TEXT NOT NULL DEFAULT '{}'`,
  `ALTER TABLE institution_identity_enrichments ADD COLUMN IF NOT EXISTS query_text TEXT`,
  `ALTER TABLE institution_identity_enrichments ADD COLUMN IF NOT EXISTS source_google_place TEXT`,
  `ALTER TABLE institution_identity_enrichments ADD COLUMN IF NOT EXISTS source_google_search TEXT`,
  `ALTER TABLE institution_identity_enrichments ADD COLUMN IF NOT EXISTS sources_json TEXT NOT NULL DEFAULT '[]'`,
  `ALTER TABLE institution_identity_enrichments ADD COLUMN IF NOT EXISTS fields_found_json TEXT NOT NULL DEFAULT '[]'`,
  `ALTER TABLE institution_identity_enrichments ADD COLUMN IF NOT EXISTS fields_missing_json TEXT NOT NULL DEFAULT '[]'`,
  `ALTER TABLE institution_identity_enrichments ADD COLUMN IF NOT EXISTS warnings_json TEXT NOT NULL DEFAULT '[]'`,
  `ALTER TABLE institution_identity_enrichments ADD COLUMN IF NOT EXISTS confidence TEXT NOT NULL DEFAULT 'low'`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS test_target_number TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS security_notes TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_enabled SMALLINT NOT NULL DEFAULT 0`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_mode TEXT NOT NULL DEFAULT 'dry_run'`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_approved_at TEXT`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_approved_by TEXT`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_last_run_at TEXT`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_last_status TEXT NOT NULL DEFAULT 'idle'`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_last_message TEXT`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_pilot_user_ids_json TEXT NOT NULL DEFAULT '[]'`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_pilot_role_ids_json TEXT NOT NULL DEFAULT '[]'`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_pilot_position_ids_json TEXT NOT NULL DEFAULT '[]'`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_scheduler_enabled SMALLINT NOT NULL DEFAULT 0`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_scheduler_mode TEXT NOT NULL DEFAULT 'dry_run'`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_scheduler_time TEXT NOT NULL DEFAULT '08:00:00'`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_scheduler_last_run_at TEXT`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_scheduler_last_message TEXT`,
  `ALTER TABLE aleta_bot_settings ADD COLUMN IF NOT EXISTS disposition_deadline_reminder_kill_switch SMALLINT NOT NULL DEFAULT 0`,
  `ALTER TABLE aleta_bot_queries ADD COLUMN IF NOT EXISTS connection_key TEXT NOT NULL DEFAULT 'sipp_primary'`,
  `ALTER TABLE aleta_bot_public_qa_intents ADD COLUMN IF NOT EXISTS legacy_command TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE aleta_bot_public_qa_intents ADD COLUMN IF NOT EXISTS parameterized_legacy_command TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE aleta_bot_public_qa_logs ADD COLUMN IF NOT EXISTS needs_human_review SMALLINT NOT NULL DEFAULT 0`,
  `ALTER TABLE aleta_bot_public_qa_logs ADD COLUMN IF NOT EXISTS review_status TEXT NOT NULL DEFAULT 'pending'`,
  `ALTER TABLE aleta_bot_public_qa_logs ADD COLUMN IF NOT EXISTS reviewed_by_user_id TEXT`,
  `ALTER TABLE aleta_bot_public_qa_logs ADD COLUMN IF NOT EXISTS reviewed_at TEXT`,
  `ALTER TABLE aleta_bot_public_qa_logs ADD COLUMN IF NOT EXISTS review_note TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE aleta_bot_notification_logs ADD COLUMN IF NOT EXISTS source_app TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE aleta_bot_notification_logs ADD COLUMN IF NOT EXISTS source_feature TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE aleta_bot_notification_logs ADD COLUMN IF NOT EXISTS entity_type TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE aleta_bot_notification_logs ADD COLUMN IF NOT EXISTS entity_id TEXT NOT NULL DEFAULT ''`,
  `ALTER TABLE aleta_bot_notification_logs ADD COLUMN IF NOT EXISTS metadata_json TEXT NOT NULL DEFAULT '{}'`,
  `ALTER TABLE dispositions ADD COLUMN IF NOT EXISTS deadline_at TEXT`,
  `ALTER TABLE dispositions ADD COLUMN IF NOT EXISTS read_at TEXT`,
  `ALTER TABLE dispositions ADD COLUMN IF NOT EXISTS read_by_user_id TEXT`,
  `ALTER TABLE letters ADD COLUMN IF NOT EXISTS workflow_status TEXT NOT NULL DEFAULT 'sent'`,
  `ALTER TABLE letters ADD COLUMN IF NOT EXISTS submitted_at TEXT`,
  `ALTER TABLE letters ADD COLUMN IF NOT EXISTS submitted_by_user_id TEXT`,
  `ALTER TABLE letters ADD COLUMN IF NOT EXISTS approved_at TEXT`,
  `ALTER TABLE letters ADD COLUMN IF NOT EXISTS approved_by_user_id TEXT`,
  `ALTER TABLE letters ADD COLUMN IF NOT EXISTS sent_at TEXT`,
  `ALTER TABLE letters ADD COLUMN IF NOT EXISTS sent_by_user_id TEXT`,
  `ALTER TABLE letters ADD COLUMN IF NOT EXISTS rejected_at TEXT`,
  `ALTER TABLE letters ADD COLUMN IF NOT EXISTS rejected_by_user_id TEXT`,
  `ALTER TABLE letters ADD COLUMN IF NOT EXISTS rejection_note TEXT`,
];

export async function ensureAletaSchema(db: AletaDatabase) {
  for (const statement of schemaStatements) {
    await db.exec(statement);
  }

  for (const statement of migrationStatements) {
    await db.exec(statement);
  }

  for (const statement of indexStatements) {
    if (!db.supportsFullTextSearch() && statement.includes("idx_letters_search_document_fts")) {
      continue;
    }
    await db.exec(statement);
  }
}
