import {
  type AIGlobalConfig,
  type AuditPreview,
  type DispositionNode,
  type LetterDetail,
  type ModuleConfig,
  type ModuleId,
  type ModuleVisibility,
  type PortalAppConfig,
  type Position,
  type Role,
  type SearchResult,
  type UserPersona,
  type WhatsAppDelivery,
  type WhatsAppStatusPreview,
} from "@/lib/types";
import { defaultAIFeatureFlags } from "@/lib/ai-feature-flags";

function buildWhatsappDelivery(
  id: string,
  recipientName: string,
  recipientWhatsapp: string,
  status: WhatsAppDelivery["status"],
  lastAttemptAt: string
): WhatsAppDelivery {
  return {
    id,
    recipientName,
    recipientWhatsapp,
    status,
    lastAttemptAt,
  };
}

export const roles: Role[] = [
  {
    id: "super-admin",
    name: "Super Admin",
    description: "Kontrol penuh infrastruktur, modul, dan database global.",
  },
  {
    id: "admin",
    name: "Admin",
    description: "Operasional user, mapping jabatan, dan reset sandi.",
  },
  {
    id: "ketua",
    name: "Ketua",
    description: "Pimpinan utama dengan hak disposisi berjenjang dan bypass.",
  },
  {
    id: "wakil-ketua",
    name: "Wakil Ketua",
    description: "Pimpinan pendamping untuk monitoring dan disposisi prioritas.",
  },
  {
    id: "hakim",
    name: "Hakim",
    description: "Pejabat yudisial yang dapat menerima penugasan dan telaah tertentu sesuai hierarki kerja.",
  },
  {
    id: "sekretaris",
    name: "Sekretaris",
    description: "Telaah awal surat administratif dan pengantar ke pimpinan.",
  },
  {
    id: "panitera",
    name: "Panitera",
    description: "Koordinasi surat pada lingkup kepaniteraan.",
  },
  {
    id: "panitera-muda",
    name: "Panitera Muda",
    description: "Koordinator unit kepaniteraan seperti hukum, gugatan, dan permohonan.",
  },
  {
    id: "panitera-pengganti",
    name: "Panitera Pengganti",
    description: "Pejabat kepaniteraan pelaksana persidangan dan tindak lanjut perkara.",
  },
  {
    id: "kasubag",
    name: "Kepala Subbagian",
    description: "Pejabat struktural kesekretariatan untuk subbagian umum, kepegawaian, dan PTIP.",
  },
  {
    id: "jurusita",
    name: "Jurusita",
    description: "Pelaksana tugas jurusita pada lingkup kepaniteraan.",
  },
  {
    id: "pranata-komputer",
    name: "Pranata Komputer",
    description: "Pengelola layanan teknologi informasi, aplikasi, dan dukungan teknis.",
  },
  {
    id: "analis-keuangan",
    name: "Analis Keuangan",
    description: "Pelaksana analisis dan pengelolaan keuangan APBN.",
  },
  {
    id: "analis-perkara",
    name: "Analis Perkara",
    description: "Pelaksana analisis perkara peradilan pada unit kepaniteraan.",
  },
  {
    id: "pelaksana",
    name: "Pelaksana",
    description: "Pegawai pelaksana teknis dan administratif sesuai unit kerja.",
  },
  {
    id: "pppk",
    name: "PPPK",
    description: "ASN Pegawai Pemerintah dengan Perjanjian Kerja; akses dasar operasional mengikuti penugasan, tanpa kewenangan struktural atau approval bawaan.",
  },
  {
    id: "pejabat-struktural",
    name: "Pejabat Struktural",
    description: "Role lama untuk kompatibilitas Panitera Muda atau Kasubag.",
  },
  {
    id: "staf",
    name: "Staf Pelaksana",
    description: "Role lama untuk kompatibilitas pegawai pelaksana umum.",
  },
];

export const positions: Position[] = [
  {
    id: "pos-ketua",
    name: "Ketua Pengadilan",
    unitKerja: "Pimpinan",
    levelHierarchy: 1,
    reportsToPositionId: null,
    dispositionTargetPositionIds: ["pos-sekretaris", "pos-panitera", "pos-kasubag-umum", "pos-kasubag-kepegawaian", "pos-kasubag-ptip"],
  },
  {
    id: "pos-wakil",
    name: "Wakil Ketua",
    unitKerja: "Pimpinan",
    levelHierarchy: 1,
    reportsToPositionId: null,
    dispositionTargetPositionIds: ["pos-sekretaris", "pos-panitera", "pos-kasubag-umum", "pos-kasubag-kepegawaian", "pos-kasubag-ptip"],
  },
  {
    id: "pos-sekretaris",
    name: "Sekretaris",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 2,
    reportsToPositionId: "pos-ketua",
    dispositionTargetPositionIds: [
      "pos-kasubag-umum",
      "pos-kasubag-kepegawaian",
      "pos-kasubag-ptip",
      "pos-arsiparis",
      "pos-bendahara",
      "pos-ptsp",
      "pos-pranata-humas",
      "pos-staf-umum",
    ],
  },
  {
    id: "pos-hakim",
    name: "Hakim",
    unitKerja: "Yudisial",
    levelHierarchy: 2,
    reportsToPositionId: "pos-ketua",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-pppk",
    name: "PPPK",
    unitKerja: "Jabatan/Unit Tambahan",
    levelHierarchy: 2,
    reportsToPositionId: null,
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-panitera",
    name: "Panitera",
    unitKerja: "Kepaniteraan",
    levelHierarchy: 2,
    reportsToPositionId: "pos-ketua",
    dispositionTargetPositionIds: [
      "pos-panitera-muda-hukum",
      "pos-panitera-muda-gugatan",
      "pos-panitera-muda-permohonan",
      "pos-panitera-pengganti",
      "pos-analis-perkara",
      "pos-analis-perkara-hukum",
      "pos-analis-perkara-gugatan",
      "pos-pengelola-penanganan-perkara-gugatan",
      "pos-dokumentalis-hukum",
      "pos-pengelola-umum-operasional-hukum",
      "pos-jurusita",
      "pos-jurusita-pengganti",
    ],
  },
  {
    id: "pos-panitera-muda-hukum",
    name: "Panitera Muda Hukum",
    unitKerja: "Kepaniteraan",
    levelHierarchy: 3,
    reportsToPositionId: "pos-panitera",
    dispositionTargetPositionIds: [
      "pos-analis-perkara-hukum",
      "pos-dokumentalis-hukum",
      "pos-pengelola-umum-operasional-hukum",
      "pos-jurusita-pengganti",
    ],
  },
  {
    id: "pos-panitera-muda-gugatan",
    name: "Panitera Muda Gugatan",
    unitKerja: "Kepaniteraan",
    levelHierarchy: 3,
    reportsToPositionId: "pos-panitera",
    dispositionTargetPositionIds: [
      "pos-analis-perkara-gugatan",
      "pos-pengelola-penanganan-perkara-gugatan",
      "pos-panitera-pengganti",
      "pos-jurusita",
      "pos-jurusita-pengganti",
    ],
  },
  {
    id: "pos-panitera-muda-permohonan",
    name: "Panitera Muda Permohonan",
    unitKerja: "Kepaniteraan",
    levelHierarchy: 3,
    reportsToPositionId: "pos-panitera",
    dispositionTargetPositionIds: ["pos-analis-perkara", "pos-jurusita", "pos-jurusita-pengganti", "pos-panitera-pengganti"],
  },
  {
    id: "pos-panitera-pengganti",
    name: "Panitera Pengganti",
    unitKerja: "Kepaniteraan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-panitera",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-analis-perkara",
    name: "Analis Perkara Peradilan",
    unitKerja: "Kepaniteraan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-panitera",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-analis-perkara-hukum",
    name: "Analis Perkara Peradilan - Hukum",
    unitKerja: "Panitera Muda Hukum",
    levelHierarchy: 4,
    reportsToPositionId: "pos-panitera-muda-hukum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-analis-perkara-gugatan",
    name: "Analis Perkara Peradilan - Gugatan",
    unitKerja: "Panitera Muda Gugatan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-panitera-muda-gugatan",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-pengelola-penanganan-perkara-gugatan",
    name: "Pengelola Penanganan Perkara - Gugatan",
    unitKerja: "Panitera Muda Gugatan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-panitera-muda-gugatan",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-dokumentalis-hukum",
    name: "Dokumentalis Hukum",
    unitKerja: "Panitera Muda Hukum",
    levelHierarchy: 4,
    reportsToPositionId: "pos-panitera-muda-hukum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-pengelola-umum-operasional-hukum",
    name: "Pengelola Umum Operasional - Hukum",
    unitKerja: "Panitera Muda Hukum",
    levelHierarchy: 4,
    reportsToPositionId: "pos-panitera-muda-hukum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-kasubag-umum",
    name: "Kasubag Umum dan Keuangan",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 3,
    reportsToPositionId: "pos-sekretaris",
    dispositionTargetPositionIds: [
      "pos-arsiparis",
      "pos-bendahara",
      "pos-ptsp",
      "pos-pranata-humas",
      "pos-staf-umum",
      "pos-pengadministrasi-umum",
      "pos-teknisi-sarpras",
      "pos-penata-layanan-umum",
      "pos-operator-layanan-umum",
      "pos-pengelola-umum-operasional",
      "pos-pengolah-data-informasi",
    ],
    canForwardToLeadership: true,
  },
  {
    id: "pos-kasubag-kepegawaian",
    name: "Kasubag Kepegawaian",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 3,
    reportsToPositionId: "pos-sekretaris",
    dispositionTargetPositionIds: ["pos-staf-kepegawaian", "pos-analis-kepegawaian", "pos-penata-layanan-kepegawaian"],
  },
  {
    id: "pos-kasubag-ptip",
    name: "Kasubag Perencanaan, TI, dan Pelaporan",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 3,
    reportsToPositionId: "pos-sekretaris",
    dispositionTargetPositionIds: ["pos-pranata-komputer", "pos-penelaah-kebijakan", "pos-staf-ptip"],
  },
  {
    id: "pos-arsiparis",
    name: "Arsiparis",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-umum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-pranata-komputer",
    name: "Pranata Komputer",
    unitKerja: "Subbagian Perencanaan, Teknologi Informasi, dan Pelaporan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-ptip",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-penelaah-kebijakan",
    name: "Penelaah Teknis Kebijakan",
    unitKerja: "Subbagian Perencanaan, Teknologi Informasi, dan Pelaporan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-ptip",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-staf-ptip",
    name: "Staf PTIP",
    unitKerja: "Subbagian Perencanaan, Teknologi Informasi, dan Pelaporan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-ptip",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-analis-keuangan",
    name: "Analis Pengelolaan Keuangan APBN",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-umum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-bendahara",
    name: "Bendahara Pengeluaran",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-umum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-pranata-humas",
    name: "Pranata Humas",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-umum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-staf-umum",
    name: "Staf Umum",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-umum",
    dispositionTargetPositionIds: [],
    canForwardToLeadership: true,
  },
  {
    id: "pos-ptsp",
    name: "Petugas PTSP",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-umum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-pengadministrasi-umum",
    name: "Pengadministrasi Umum",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-umum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-teknisi-sarpras",
    name: "Teknisi Sarana dan Prasarana",
    unitKerja: "Subbagian Umum dan Keuangan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-umum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-penata-layanan-umum",
    name: "Penata Layanan Operasional - Umum",
    unitKerja: "Subbagian Umum dan Keuangan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-umum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-operator-layanan-umum",
    name: "Operator Layanan Operasional - Umum",
    unitKerja: "Subbagian Umum dan Keuangan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-umum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-pengelola-umum-operasional",
    name: "Pengelola Umum Operasional",
    unitKerja: "Subbagian Umum dan Keuangan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-umum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-pengolah-data-informasi",
    name: "Pengolah Data dan Informasi",
    unitKerja: "Subbagian Umum dan Keuangan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-umum",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-staf-kepegawaian",
    name: "Staf Kepegawaian",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-kepegawaian",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-analis-kepegawaian",
    name: "Analis Kepegawaian",
    unitKerja: "Kesekretariatan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-kepegawaian",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-penata-layanan-kepegawaian",
    name: "Penata Layanan Operasional - Kepegawaian",
    unitKerja: "Subbagian Kepegawaian, Organisasi, dan Tata Laksana",
    levelHierarchy: 4,
    reportsToPositionId: "pos-kasubag-kepegawaian",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-jurusita",
    name: "Jurusita",
    unitKerja: "Kepaniteraan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-panitera",
    dispositionTargetPositionIds: [],
  },
  {
    id: "pos-jurusita-pengganti",
    name: "Jurusita Pengganti",
    unitKerja: "Kepaniteraan",
    levelHierarchy: 4,
    reportsToPositionId: "pos-panitera",
    dispositionTargetPositionIds: [],
  },
];

export const defaultAIConfig: AIGlobalConfig = {
  enabled: true,
  modelId: "Gemini 2.0 Flash",
  primaryLanguage: "id",
  providerId: "gemini",
  activeConnectionId: null,
  providers: [],
  moduleConfigs: [],
  featureFlags: defaultAIFeatureFlags,
  featureDispositionAi: true,
  featureMailIntelligence: true,
  featureDraftMetadata: true,
  featureManajemenSuratAi: true,
  featureDisposisiAi: true,
};

export const defaultWhatsAppWeb = {
  phoneNumber: "",
  sessionName: "ALETA WhatsApp Web",
  status: "inactive" as const,
  lastConnectedAt: "",
};

export const defaultInstitutionIdentity = {
  courtName: "Pengadilan Agama Makassar Kelas IA",
  courtShortName: "PA Makassar",
  address: "Jl. Perintis Kemerdekaan Km. 14, Makassar, Sulawesi Selatan",
  phoneNumber: "(0411) 554122",
  mobilePhone: "0811-4411-2200",
  csWhatsappNumber: "0811-4411-2200",
  botWhatsappNumber: "",
  email: "pa.makassar@pta-makassar.go.id",
  instagram: "@pa_makassar",
  facebook: "Pengadilan Agama Makassar",
  youtube: "PA Makassar Official",
  website: "https://pa-makassar.go.id",
  mapUrl: "https://maps.google.com/?q=Pengadilan+Agama+Makassar",
  logoUrl: "",
};

export const personas: UserPersona[] = [
  {
    id: "usr-super",
    username: "superadmin",
    password: "super123",
    name: "SUPER ADMIN DERRY",
    nip: "198001012005012001",
    email: "superderry@gmail.com",
    whatsappNumber: "628123450001",
    roleId: "super-admin",
    positionId: "pos-pranata-komputer",
    isActive: true,
  },
  {
    id: "usr-admin",
    username: "adminit",
    password: "admin123",
    name: "Dian Saputra",
    nip: "198411182008011003",
    email: "dian.it@pa.go.id",
    whatsappNumber: "628123450002",
    roleId: "admin",
    positionId: "pos-pranata-komputer",
    isActive: true,
  },
  {
    id: "usr-ketua",
    username: "ketua",
    password: "ketua123",
    name: "Drs. H. Malik",
    nip: "197202051999031001",
    email: "ketua@pa.go.id",
    whatsappNumber: "628123450003",
    roleId: "ketua",
    positionId: "pos-ketua",
    isActive: true,
    canBypassHierarchy: true,
  },
  {
    id: "usr-wakil",
    username: "wakil",
    password: "wakil123",
    name: "Drs. H. Fauzi",
    nip: "197509182001121002",
    email: "wakil@pa.go.id",
    whatsappNumber: "628123450004",
    roleId: "wakil-ketua",
    positionId: "pos-wakil",
    isActive: true,
    canBypassHierarchy: true,
  },
  {
    id: "usr-sekretaris",
    username: "sekretaris",
    password: "sekretaris123",
    name: "Siti Nurhayati",
    nip: "198603012009022004",
    email: "sekretaris@pa.go.id",
    whatsappNumber: "628123450005",
    roleId: "sekretaris",
    positionId: "pos-sekretaris",
    isActive: true,
  },
  {
    id: "usr-panitera",
    username: "panitera",
    password: "panitera123",
    name: "M. Ridwan",
    nip: "197811102004121003",
    email: "panitera@pa.go.id",
    whatsappNumber: "628123450006",
    roleId: "panitera",
    positionId: "pos-panitera",
    isActive: true,
  },
  {
    id: "usr-hakim",
    username: "hakim",
    password: "hakim123",
    name: "Hj. Nur Aisyah",
    nip: "197912142006042001",
    email: "hakim@pa.go.id",
    whatsappNumber: "628123450021",
    roleId: "hakim",
    positionId: "pos-hakim",
    isActive: true,
  },
  {
    id: "usr-ahmad",
    username: "ahmad",
    password: "ahmad123",
    name: "Ahmad Rizki",
    nip: "199104122015031001",
    email: "ahmad@pa.go.id",
    whatsappNumber: "628123450007",
    roleId: "pejabat-struktural",
    positionId: "pos-panitera-muda-hukum",
    isActive: true,
  },
  {
    id: "usr-gugatan",
    username: "panmudgugatan",
    password: "panmud123",
    name: "R. Hidayat",
    nip: "198112112007011002",
    email: "panmud.gugatan@pa.go.id",
    whatsappNumber: "628123450011",
    roleId: "pejabat-struktural",
    positionId: "pos-panitera-muda-gugatan",
    isActive: true,
  },
  {
    id: "usr-permohonan",
    username: "panmudpermohonan",
    password: "panmud123",
    name: "Sri Lestari",
    nip: "198205192008012005",
    email: "panmud.permohonan@pa.go.id",
    whatsappNumber: "628123450012",
    roleId: "pejabat-struktural",
    positionId: "pos-panitera-muda-permohonan",
    isActive: true,
  },
  {
    id: "usr-ppg",
    username: "paniterapengganti",
    password: "ppg123",
    name: "Muhammad Taufik",
    nip: "198508222010121007",
    email: "panitera.pengganti@pa.go.id",
    whatsappNumber: "628123450022",
    roleId: "staf",
    positionId: "pos-panitera-pengganti",
    isActive: true,
  },
  {
    id: "usr-analisperkara",
    username: "analisperkara",
    password: "analis123",
    name: "Nadia Salma",
    nip: "199112102018122015",
    email: "analis.perkara@pa.go.id",
    whatsappNumber: "628123450023",
    roleId: "staf",
    positionId: "pos-analis-perkara",
    isActive: true,
  },
  {
    id: "usr-rina",
    username: "kasubag",
    password: "kasubag123",
    name: "Rina Kartika",
    nip: "198705032010122002",
    email: "kasubag.umum@pa.go.id",
    whatsappNumber: "628123450008",
    roleId: "pejabat-struktural",
    positionId: "pos-kasubag-umum",
    isActive: true,
  },
  {
    id: "usr-kepeg",
    username: "kasubagkepeg",
    password: "kepeg123",
    name: "Farhan Akbar",
    nip: "198706212011011006",
    email: "kasubag.kepegawaian@pa.go.id",
    whatsappNumber: "628123450013",
    roleId: "pejabat-struktural",
    positionId: "pos-kasubag-kepegawaian",
    isActive: true,
  },
  {
    id: "usr-dina",
    username: "stafumum",
    password: "stafumum123",
    name: "Dina Maharani",
    nip: "199502112019032005",
    email: "staf.umum@pa.go.id",
    whatsappNumber: "628123450009",
    roleId: "staf",
    positionId: "pos-staf-umum",
    isActive: true,
  },
  {
    id: "usr-kepeg-staff",
    username: "stafkepeg",
    password: "stafkepeg123",
    name: "Andi Fitriani",
    nip: "199311212019122004",
    email: "staf.kepegawaian@pa.go.id",
    whatsappNumber: "628123450014",
    roleId: "staf",
    positionId: "pos-staf-kepegawaian",
    isActive: true,
  },
  {
    id: "usr-budi",
    username: "staf",
    password: "staf123",
    name: "Budi Santoso",
    nip: "199308102017011004",
    email: "budi@pa.go.id",
    whatsappNumber: "628123450010",
    roleId: "staf",
    positionId: "pos-arsiparis",
    isActive: true,
  },
  {
    id: "usr-jurusita",
    username: "jurusita",
    password: "jurusita123",
    name: "Muh. Iqbal",
    nip: "198910112015031008",
    email: "jurusita@pa.go.id",
    whatsappNumber: "628123450015",
    roleId: "staf",
    positionId: "pos-jurusita",
    isActive: true,
  },
  {
    id: "usr-jsp",
    username: "jsp",
    password: "jsp123",
    name: "Nurhuda",
    nip: "199206022018031003",
    email: "jurusita.pengganti@pa.go.id",
    whatsappNumber: "628123450016",
    roleId: "staf",
    positionId: "pos-jurusita-pengganti",
    isActive: true,
  },
  {
    id: "usr-analiskeu",
    username: "analiskeu",
    password: "keu123",
    name: "Wulan Sari",
    nip: "199001142016122001",
    email: "analis.keuangan@pa.go.id",
    whatsappNumber: "628123450017",
    roleId: "staf",
    positionId: "pos-analis-keuangan",
    isActive: true,
  },
  {
    id: "usr-bendahara",
    username: "bendahara",
    password: "bendahara123",
    name: "Ridho Pratama",
    nip: "198906072014021009",
    email: "bendahara@pa.go.id",
    whatsappNumber: "628123450018",
    roleId: "staf",
    positionId: "pos-bendahara",
    isActive: true,
  },
  {
    id: "usr-humas",
    username: "humas",
    password: "humas123",
    name: "Rahmat Hidayat",
    nip: "199003112017121014",
    email: "humas@pa.go.id",
    whatsappNumber: "628123450024",
    roleId: "staf",
    positionId: "pos-pranata-humas",
    isActive: true,
  },
  {
    id: "usr-ptsp",
    username: "ptsp",
    password: "ptsp123",
    name: "Lina Octavia",
    nip: "199405172020122002",
    email: "ptsp@pa.go.id",
    whatsappNumber: "628123450019",
    roleId: "staf",
    positionId: "pos-ptsp",
    isActive: true,
  },
  {
    id: "usr-analiskp",
    username: "analiskp",
    password: "analiskp123",
    name: "Salsabila",
    nip: "199207052018122011",
    email: "analis.kepegawaian@pa.go.id",
    whatsappNumber: "628123450020",
    roleId: "staf",
    positionId: "pos-analis-kepegawaian",
    isActive: true,
  },
];

export const modules: ModuleConfig[] = [
  {
    id: "dashboard",
    label: "Dashboard Surat",
    description: "Ringkasan surat, tugas penting, dan aktivitas terbaru.",
    href: "/manajemen-surat",
    icon: "layout-dashboard",
    roleIds: roles.map((role) => role.id),
    showInHub: false,
    showInSidebar: true,
  },
  {
    id: "notifikasi",
    label: "Pusat Tugas",
    description: "Daftar tugas penting dan pemberitahuan yang perlu dicek.",
    href: "/tugas",
    icon: "bell",
    roleIds: roles.map((role) => role.id),
    showInHub: true,
    showInSidebar: true,
    iconBgClass: "bg-rose-100",
    iconFgClass: "text-rose-700",
    cardClass: "border-rose-200/80 bg-rose-50/70",
    badgeLabel: "Mendesak",
  },
  {
    id: "penugasan",
    label: "Kelola PLH/PLT",
    description: "Atur pejabat pengganti dan masa tugasnya.",
    href: "/penugasan",
    icon: "user-cog",
    roleIds: [
      "super-admin",
      "admin",
      "ketua",
      "wakil-ketua",
      "hakim",
      "sekretaris",
      "panitera",
      "panitera-muda",
      "kasubag",
      "pejabat-struktural",
    ],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-indigo-100",
    iconFgClass: "text-indigo-700",
    cardClass: "border-indigo-200/80 bg-indigo-50/70",
    badgeLabel: "Jabatan",
  },
  {
    id: "surat-masuk",
    label: "Surat Masuk",
    description: "Catat surat masuk dan ikuti tindak lanjutnya.",
    href: "/surat?type=masuk",
    icon: "inbox",
    roleIds: roles.map((role) => role.id),
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-sky-100",
    iconFgClass: "text-sky-700",
    cardClass: "border-sky-200/80 bg-sky-50/70",
    badgeLabel: "Surat",
  },
  {
    id: "surat-keluar",
    label: "Surat Keluar",
    description: "Daftar naskah dinas dan surat tugas keluar.",
    href: "/surat?type=keluar",
    icon: "send",
    roleIds: roles.map((role) => role.id),
    showInHub: false,
    showInSidebar: true,
  },
  {
    id: "arsip",
    label: "Arsip Surat",
    description: "Cari kembali surat masuk dan surat keluar yang tersimpan.",
    href: "/arsip",
    icon: "archive",
    roleIds: roles.map((role) => role.id),
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-orange-100",
    iconFgClass: "text-orange-700",
    cardClass: "border-orange-200/80 bg-orange-50/70",
    badgeLabel: "Arsip",
  },
  {
    id: "statistik",
    label: "Statistik",
    description: "Lihat jumlah dan perkembangan surat dalam bentuk grafik.",
    href: "/statistik",
    icon: "chart-column",
    roleIds: roles.map((role) => role.id),
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-rose-100",
    iconFgClass: "text-rose-700",
    cardClass: "border-rose-200/80 bg-rose-50/70",
    badgeLabel: "Grafik",
  },
  {
    id: "disposisi",
    label: "Disposisi Digital",
    description: "Teruskan disposisi dan pantau penyelesaiannya.",
    href: "/disposisi",
    icon: "git-branch-plus",
    roleIds: roles.map((role) => role.id),
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-emerald-100",
    iconFgClass: "text-emerald-700",
    cardClass: "border-emerald-200/80 bg-emerald-50/70",
    badgeLabel: "Disposisi",
  },
  {
    id: "search",
    label: "Pencarian Global",
    description: "Cari surat, disposisi, dan pengguna secara cepat.",
    href: "/search",
    icon: "search",
    roleIds: roles.map((role) => role.id),
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-amber-100",
    iconFgClass: "text-amber-700",
    cardClass: "border-amber-200/80 bg-amber-50/70",
    badgeLabel: "Indeks",
  },
  {
    id: "mapping-user-jabatan",
    label: "Manajemen Akun",
    description: "Kelola akun pengguna, nomor WhatsApp, dan jabatan.",
    href: "/admin/mapping-user-jabatan",
    icon: "users-round",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-violet-100",
    iconFgClass: "text-violet-700",
    cardClass: "border-violet-200/80 bg-violet-50/70",
    badgeLabel: "Admin",
  },
  {
    id: "visibility-role",
    label: "Akses Menu",
    description: "Atur menu yang terlihat untuk tiap peran.",
    href: "/admin/visibility-role",
    icon: "shield-check",
    roleIds: ["super-admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-indigo-100",
    iconFgClass: "text-indigo-700",
    cardClass: "border-indigo-200/80 bg-indigo-50/70",
    badgeLabel: "Kontrol",
  },
  {
    id: "laporan",
    label: "Laporan",
    description: "Ringkasan laporan kerja dan ketepatan tindak lanjut.",
    href: "/manajemen-surat",
    icon: "chart-column",
    roleIds: ["super-admin", "admin", "ketua", "wakil-ketua"],
    showInHub: true,
    showInSidebar: false,
    iconBgClass: "bg-rose-100",
    iconFgClass: "text-rose-700",
    cardClass: "border-rose-200/80 bg-rose-50/70",
    badgeLabel: "LKjIP",
  },
  {
    id: "audit",
    label: "Audit Trail",
    description: "Catatan aktivitas penting untuk pemeriksaan admin.",
    href: "/admin/audit-trail",
    icon: "scroll-text",
    roleIds: ["super-admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-slate-200",
    iconFgClass: "text-slate-700",
    cardClass: "border-slate-200/80 bg-slate-50/80",
    badgeLabel: "Admin",
  },
  {
    id: "kepegawaian",
    label: "E-Kepegawaian",
    description: "Kelola profil pegawai, cuti, PCK, SKP, WFA, izin, dokumen, dan rekap kepegawaian.",
    href: "/e-kepegawaian",
    icon: "briefcase-business",
    roleIds: roles.map((role) => role.id),
    showInHub: true,
    showInSidebar: true,
    iconBgClass: "bg-fuchsia-100",
    iconFgClass: "text-fuchsia-700",
    cardClass: "border-fuchsia-200/80 bg-fuchsia-50/70",
    badgeLabel: "Kepegawaian",
  },
  {
    id: "hr-settings",
    label: "Pengaturan E-Kepegawaian",
    description: "Atur jenis cuti, workflow approval, kalender libur, upload, dan rekap E-Kepegawaian.",
    href: "/admin/e-kepegawaian",
    icon: "briefcase-business",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-cyan-100",
    iconFgClass: "text-cyan-700",
    cardClass: "border-cyan-200/80 bg-cyan-50/70",
    badgeLabel: "Admin",
  },
  {
    id: "judicia-legal-form",
    label: "ALETA Judicia (Legal Form)",
    description: "Legal Form, dokumen perkara, template, variabel, dan data SIPP read-only.",
    href: "/judicia/legal-form",
    icon: "scale",
    roleIds: roles.map((role) => role.id),
    showInHub: true,
    showInSidebar: true,
    iconBgClass: "bg-teal-100",
    iconFgClass: "text-teal-700",
    cardClass: "border-teal-200/80 bg-teal-50/70",
    badgeLabel: "Perkara",
  },
  {
    id: "aleta-sipp",
    label: "ALETA x SIPP",
    description: "Kamus database SIPP, query registry, variabel ABT/SIPP, penilaian SIPP, dan PDF jadwal sidang.",
    href: "/aleta-sipp",
    icon: "database",
    roleIds: roles.map((role) => role.id),
    showInHub: true,
    showInSidebar: true,
    iconBgClass: "bg-cyan-100",
    iconFgClass: "text-cyan-700",
    cardClass: "border-cyan-200/80 bg-cyan-50/70",
    badgeLabel: "SIPP",
  },
  {
    id: "aleta-sipp-settings",
    label: "Pengaturan ALETA x SIPP",
    description: "Import dry-run, query registry, variable registry, penilaian, PDF jadwal sidang, AI, permission, dan audit.",
    href: "/admin/aleta-sipp",
    icon: "database",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-cyan-100",
    iconFgClass: "text-cyan-700",
    cardClass: "border-cyan-200/80 bg-cyan-50/70",
    badgeLabel: "SIPP",
  },
  {
    id: "judicia-legal-form-settings",
    label: "ALETA Judicia (Legal Form)",
    description: "Pengaturan modul JLF: template, variabel, SIPP, AI, ALETA Bot, KB hukum, QR, audit, dan importer legacy.",
    href: "/admin/judicia-legal-form",
    icon: "scale",
    roleIds: ["super-admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-teal-100",
    iconFgClass: "text-teal-700",
    cardClass: "border-teal-200/80 bg-teal-50/70",
    badgeLabel: "JLF",
  },
  {
    id: "e-status",
    label: "E-Status",
    description: "Sinkronisasi status perkawinan dari SIPP untuk Dukcapil, KUA, dan Kemenag dengan review, approval, dan audit.",
    href: "/e-status",
    icon: "database",
    roleIds: [
      "super-admin",
      "admin",
      "ketua",
      "wakil-ketua",
      "panitera",
      "panitera-muda",
      "panitera-pengganti",
      "analis-perkara",
      "pejabat-struktural",
      "staf",
    ],
    showInHub: true,
    showInSidebar: true,
    iconBgClass: "bg-emerald-100",
    iconFgClass: "text-emerald-700",
    cardClass: "border-emerald-200/80 bg-emerald-50/70",
    badgeLabel: "Status",
  },
  {
    id: "e-status-settings",
    label: "Pengaturan E-Status",
    description: "Atur koneksi SIPP read-only, mapping, instansi mitra, template ekspor, keamanan, dan audit E-Status.",
    href: "/e-status?section=pengaturan",
    icon: "database",
    roleIds: ["super-admin", "admin", "panitera", "panitera-muda"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-emerald-100",
    iconFgClass: "text-emerald-700",
    cardClass: "border-emerald-200/80 bg-emerald-50/70",
    badgeLabel: "Admin",
  },
  {
    id: "keuangan",
    label: "Keuangan",
    description: "Menu rencana untuk anggaran dan transaksi internal.",
    href: "/manajemen-surat#keuangan",
    icon: "wallet",
    roleIds: ["super-admin"],
    showInHub: true,
    showInSidebar: false,
    iconBgClass: "bg-green-100",
    iconFgClass: "text-green-700",
    cardClass: "border-green-200/80 bg-green-50/70",
    badgeLabel: "Rencana",
  },
  {
    id: "aset",
    label: "Aset",
    description: "Menu rencana untuk inventaris, BMN, dan dokumen barang.",
    href: "/manajemen-surat#aset",
    icon: "archive",
    roleIds: ["super-admin"],
    showInHub: true,
    showInSidebar: false,
    iconBgClass: "bg-orange-100",
    iconFgClass: "text-orange-700",
    cardClass: "border-orange-200/80 bg-orange-50/70",
    badgeLabel: "Rencana",
  },
  {
    id: "admin-hub",
    label: "Pusat Kendali",
    description: "Pusat pengaturan akun, identitas, WhatsApp, dan layanan penting.",
    href: "/admin",
    icon: "layout-dashboard",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-indigo-100",
    iconFgClass: "text-indigo-700",
    cardClass: "border-indigo-200/80 bg-indigo-50/70",
    badgeLabel: "Admin",
  },
  {
    id: "identity",
    label: "Identitas Instansi",
    description: "Atur nama instansi, logo, alamat, dan kanal resmi.",
    href: "/admin/identitas-instansi",
    icon: "landmark",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-cyan-100",
    iconFgClass: "text-cyan-700",
    cardClass: "border-cyan-200/80 bg-cyan-50/70",
    badgeLabel: "Identitas",
  },
  {
    id: "panel-settings",
    label: "Pengaturan Panel",
    description: "Atur tampilan global panel aplikasi, footer, dan preferensi antarmuka.",
    href: "/admin/pengaturan-panel",
    icon: "settings",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-slate-200",
    iconFgClass: "text-slate-700",
    cardClass: "border-slate-200/80 bg-slate-50/80",
    badgeLabel: "Panel",
  },
  {
    id: "public-access",
    label: "Akses Publik",
    description: "Simpan alamat domain publik ALETA dan panduan akses dari internet.",
    href: "/admin/akses-publik",
    icon: "globe",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-sky-100",
    iconFgClass: "text-sky-700",
    cardClass: "border-sky-200/80 bg-sky-50/70",
    badgeLabel: "Publik",
  },
  {
    id: "ai-settings",
    label: "Pengaturan AI",
    description: "Konfigurasi API Key, pemilihan model AI, dan parameter otentikasi AI global.",
    href: "/admin/pengaturan-ai",
    icon: "sparkles",
    roleIds: ["super-admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-amber-100",
    iconFgClass: "text-amber-700",
    cardClass: "border-amber-200/80 bg-amber-50/70",
    badgeLabel: "Intelligence",
  },
  {
    id: "assistant-judge-settings",
    label: "Asisten Hakim",
    description: "Atur tautan Asisten Hakim dan siapa saja yang bisa melihatnya.",
    href: "/admin/asisten-hakim",
    icon: "scale",
    roleIds: ["super-admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-violet-100",
    iconFgClass: "text-violet-700",
    cardClass: "border-violet-200/80 bg-violet-50/70",
    badgeLabel: "AI Yudisial",
  },
  {
    id: "whatsapp-settings",
    label: "Status WhatsApp",
    description: "Cek koneksi WhatsApp kantor dan tampilkan QR bila diperlukan.",
    href: "/admin/status-whatsapp",
    icon: "message-circle-more",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-emerald-100",
    iconFgClass: "text-emerald-700",
    cardClass: "border-emerald-200/80 bg-emerald-50/70",
    badgeLabel: "WhatsApp",
  },
  {
    id: "feedback",
    label: "Masukan Pengguna",
    description: "Tinjau laporan kendala, saran fitur, dan usulan dari pengguna.",
    href: "/admin/feedback",
    icon: "message-circle-more",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-blue-100",
    iconFgClass: "text-blue-700",
    cardClass: "border-blue-200/80 bg-blue-50/70",
    badgeLabel: "Masukan",
  },
  {
    id: "system-updates",
    label: "Pembaruan Sistem",
    description: "Cek versi aplikasi dan paket pembaruan server.",
    href: "/admin/pembaruan-sistem",
    icon: "package-check",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-emerald-100",
    iconFgClass: "text-emerald-700",
    cardClass: "border-emerald-200/80 bg-emerald-50/70",
    badgeLabel: "Versi",
  },
  {
    id: "backup-system",
    label: "Backup Sistem",
    description: "Unduh backup database dan source aplikasi.",
    href: "/admin/backup",
    icon: "database-backup",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-cyan-100",
    iconFgClass: "text-cyan-700",
    cardClass: "border-cyan-200/80 bg-cyan-50/70",
    badgeLabel: "Backup",
  },
  {
    id: "database-viewer",
    label: "Database",
    description: "Lihat dan edit data PostgreSQL aktif secara terbatas.",
    href: "/admin/database",
    icon: "database",
    roleIds: ["super-admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-sky-100",
    iconFgClass: "text-sky-700",
    cardClass: "border-sky-200/80 bg-sky-50/70",
    badgeLabel: "PostgreSQL",
  },
  {
    // Ruang kerja perkara: berkas, riwayat, pemeriksaan, draf, dan jejaknya di
    // satu layar. Susunan panelnya mengikuti peran - hakim membuka pemeriksaan
    // lebih dulu, panitera membuka riwayat - tetapi tidak ada bagian yang
    // disembunyikan dari peran mana pun. Kewenangan dijaga peladen; layar yang
    // menyembunyikan hal yang sebenarnya boleh dilihat hanya membuat orang
    // meminta kewenangan lebih besar daripada yang ia perlukan.
    id: "perkara",
    label: "Ruang Kerja Perkara",
    description: "Buka satu perkara, lalu berkas, riwayat, pemeriksaan, draf, dan jejaknya ada di layar yang sama.",
    href: "/perkara",
    icon: "briefcase-business",
    roleIds: [
      "super-admin",
      "admin",
      "ketua",
      "wakil-ketua",
      "hakim",
      "panitera",
      "panitera-muda",
      "panitera-pengganti",
      "analis-perkara",
    ],
    showInHub: true,
    showInSidebar: true,
    iconBgClass: "bg-teal-100",
    iconFgClass: "text-teal-700",
    cardClass: "border-teal-200/80 bg-teal-50/70",
    badgeLabel: "Perkara",
  },
  {
    // Alat bantu tulis BAS untuk kepaniteraan. Diletakkan di sidebar, bukan
    // hanya di hub: ini alat yang dibuka berkali-kali dalam sehari sidang,
    // dan alat sehari-hari yang harus dicari dulu akan berhenti dipakai.
    id: "bas",
    label: "Alat Bantu Tulis BAS",
    description: "Buka perkaranya, pilih pemeriksaan hari ini, dan lembar tanya-jawabnya terbuka sudah terisi dari SIPP.",
    href: "/bas",
    icon: "file-text",
    roleIds: roles.map((role) => role.id),
    showInHub: true,
    showInSidebar: true,
    iconBgClass: "bg-emerald-100",
    iconFgClass: "text-emerald-700",
    cardClass: "border-emerald-200/80 bg-emerald-50/70",
    badgeLabel: "Kepaniteraan",
  },
  {
    // Untuk seluruh pegawai: mengunduh ekstensi dan melihat keadaan
    // penghubung e-Court. Tidak ada pengaturan apa pun di sini.
    id: "aleta-ecourt",
    label: "ALETA e-Court",
    description: "Penghubung e-Court dan SIPP. Unduh ekstensi peramban dan lihat keadaan penghubungnya.",
    href: "/aleta-ecourt",
    icon: "link",
    roleIds: roles.map((role) => role.id),
    showInHub: true,
    showInSidebar: false,
    iconBgClass: "bg-emerald-100",
    iconFgClass: "text-emerald-700",
    cardClass: "border-emerald-200/80 bg-emerald-50/70",
    badgeLabel: "e-Court",
  },
  {
    // Menu admin di sidebar. Berbeda dengan "aleta-ecourt" yang untuk seluruh
    // pegawai, yang ini mengatur penghubungnya: sesi login e-Court, penarikan
    // berkala, arsip, dan kaitannya dengan pemberitahuan WhatsApp ALETA Bot.
    id: "aleta-ecourt-admin",
    label: "Integrasi e-Court",
    description: "Pengaturan penghubung e-Court, SIPP, dan pemberitahuan WhatsApp ALETA Bot.",
    href: "/admin/aleta-ecourt",
    icon: "link-2",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-emerald-100",
    iconFgClass: "text-emerald-700",
    cardClass: "border-emerald-200/80 bg-emerald-50/70",
    badgeLabel: "Integrasi",
  },
  {
    id: "aleta-bot",
    label: "ALETA Bot",
    description: "Pengaturan bot WhatsApp notifikasi perkara, template pesan, query, log, dan manual test.",
    href: "/admin/aleta-bot",
    icon: "bot",
    roleIds: ["super-admin", "admin"],
    showInHub: false,
    showInSidebar: true,
    iconBgClass: "bg-cyan-100",
    iconFgClass: "text-cyan-700",
    cardClass: "border-cyan-200/80 bg-cyan-50/70",
    badgeLabel: "Bot",
  },
  {
    id: "notifikasi-wa",
    label: "Notifikasi WA",
    description: "Menu rencana untuk melihat pemberitahuan WhatsApp dan email.",
    href: "/manajemen-surat#notifikasi",
    icon: "message-circle-more",
    roleIds: ["super-admin", "admin"],
    showInHub: true,
    showInSidebar: false,
    iconBgClass: "bg-lime-100",
    iconFgClass: "text-lime-700",
    cardClass: "border-lime-200/80 bg-lime-50/70",
    badgeLabel: "Rencana",
  },
];

export const portalApps: PortalAppConfig[] = [
  {
    id: "manajemen-surat",
    label: "Manajemen Surat",
    description: "Kelola surat masuk, surat keluar, disposisi, dan arsip.",
    href: "/manajemen-surat",
    icon: "inbox",
    roleIds: roles.map((role) => role.id),
    badgeLabel: "Menu Utama",
    iconBgClass: "bg-sky-100 dark:bg-sky-500/15",
    iconFgClass: "text-sky-700 dark:text-sky-200",
    cardClass: "border-sky-200/80 bg-sky-50/80 dark:border-sky-500/20 dark:bg-slate-900/80",
  },
  {
    id: "aleta-bot",
    label: "ALETA Bot",
    description: "Lihat kondisi WhatsApp Bot dan riwayat pesan yang dikirim.",
    href: "/aleta-bot",
    icon: "bot",
    roleIds: roles.map((role) => role.id),
    badgeLabel: "Bot Notifikasi",
    iconBgClass: "bg-cyan-100 dark:bg-cyan-500/15",
    iconFgClass: "text-cyan-700 dark:text-cyan-200",
    cardClass: "border-cyan-200/80 bg-cyan-50/80 dark:border-cyan-500/20 dark:bg-slate-900/80",
  },
  {
    // Kartu untuk seluruh pegawai: mengunduh ekstensi peramban SIPP dan
    // melihat keadaan penghubung e-Court. Pengaturannya sendiri ada di menu
    // admin (/admin/aleta-ecourt), bukan di sini.
    id: "aleta-ecourt",
    label: "ALETA e-Court",
    description: "Penghubung e-Court dan SIPP. Unduh ekstensi peramban dan lihat keadaan penghubungnya.",
    href: "/aleta-ecourt",
    icon: "link",
    roleIds: roles.map((role) => role.id),
    badgeLabel: "e-Court",
    iconBgClass: "bg-emerald-100 dark:bg-emerald-500/15",
    iconFgClass: "text-emerald-700 dark:text-emerald-200",
    cardClass: "border-emerald-200/80 bg-emerald-50/80 dark:border-emerald-500/20 dark:bg-slate-900/80",
  },
  {
    id: "judicia-legal-form",
    label: "ALETA Judicia (Legal Form)",
    description: "Legal Form untuk dokumen perkara, template, variabel, data SIPP, dan validasi berbasis human-in-the-loop.",
    href: "/judicia/legal-form",
    icon: "scale",
    roleIds: roles.map((role) => role.id),
    badgeLabel: "Perkara",
    iconBgClass: "bg-teal-100 dark:bg-teal-500/15",
    iconFgClass: "text-teal-700 dark:text-teal-200",
    cardClass: "border-teal-200/80 bg-teal-50/80 dark:border-teal-500/20 dark:bg-slate-900/80",
  },
  {
    id: "aleta-sipp",
    label: "ALETA x SIPP",
    description: "Pusat pengetahuan SIPP: kamus database, query registry, variable registry, penilaian, dan PDF jadwal sidang.",
    href: "/aleta-sipp",
    icon: "database",
    roleIds: roles.map((role) => role.id),
    badgeLabel: "SIPP Knowledge",
    iconBgClass: "bg-cyan-100 dark:bg-cyan-500/15",
    iconFgClass: "text-cyan-700 dark:text-cyan-200",
    cardClass: "border-cyan-200/80 bg-cyan-50/80 dark:border-cyan-500/20 dark:bg-slate-900/80",
  },
  {
    id: "sipp",
    label: "SIPP",
    description: "Buka SIPP dengan kredensial yang tersimpan aman di akun ALETA.",
    href: "/api/external-apps/sipp/launch",
    icon: "database",
    roleIds: roles.map((role) => role.id),
    badgeLabel: "SSO",
    iconBgClass: "bg-blue-100 dark:bg-blue-500/15",
    iconFgClass: "text-blue-700 dark:text-blue-200",
    cardClass: "border-blue-200/80 bg-blue-50/80 dark:border-blue-500/20 dark:bg-slate-900/80",
  },
  {
    id: "aps-badilag",
    label: "APS Badilag",
    description: "Buka APS Badilag memakai akun yang terhubung dengan database SIPP.",
    href: "/api/external-apps/aps-badilag/launch",
    icon: "database",
    roleIds: roles.map((role) => role.id),
    badgeLabel: "SSO",
    iconBgClass: "bg-indigo-100 dark:bg-indigo-500/15",
    iconFgClass: "text-indigo-700 dark:text-indigo-200",
    cardClass: "border-indigo-200/80 bg-indigo-50/80 dark:border-indigo-500/20 dark:bg-slate-900/80",
  },
  {
    id: "e-status",
    label: "E-Status",
    description: "Validasi, batch, approval, ekspor, dan tracking data perubahan status perkawinan kepada instansi mitra.",
    href: "/e-status",
    icon: "database",
    roleIds: [
      "super-admin",
      "admin",
      "ketua",
      "wakil-ketua",
      "panitera",
      "panitera-muda",
      "panitera-pengganti",
      "analis-perkara",
      "pejabat-struktural",
      "staf",
    ],
    badgeLabel: "Baru",
    iconBgClass: "bg-emerald-100 dark:bg-emerald-500/15",
    iconFgClass: "text-emerald-700 dark:text-emerald-200",
    cardClass: "border-emerald-200/80 bg-emerald-50/80 dark:border-emerald-500/20 dark:bg-slate-900/80",
  },
  {
    id: "asisten-hakim",
    label: "Asisten Hakim",
    description: "Buka Asisten Hakim yang tersedia sesuai akses Anda.",
    href: "/asisten-hakim",
    icon: "scale",
    roleIds: ["super-admin", "admin", "ketua", "wakil-ketua", "hakim"],
    badgeLabel: "Asisten",
    iconBgClass: "bg-violet-100 dark:bg-violet-500/15",
    iconFgClass: "text-violet-700 dark:text-violet-200",
    cardClass: "border-violet-200/80 bg-violet-50/80 dark:border-violet-500/20 dark:bg-slate-900/80",
  },
  {
    // Ruang kerja perkara: berkas, riwayat, pemeriksaan, draf, dan jejaknya di
    // satu layar. Susunan panelnya mengikuti peran - hakim membuka pemeriksaan
    // lebih dulu, panitera membuka riwayat - tetapi tidak ada bagian yang
    // disembunyikan dari peran mana pun. Kewenangan dijaga peladen; layar yang
    // menyembunyikan hal yang sebenarnya boleh dilihat hanya membuat orang
    // meminta kewenangan lebih besar daripada yang ia perlukan.
    id: "perkara",
    label: "Ruang Kerja Perkara",
    description: "Buka satu perkara, lalu berkas, riwayat, pemeriksaan, draf, dan jejaknya ada di layar yang sama.",
    href: "/perkara",
    icon: "briefcase-business",
    roleIds: [
      "super-admin",
      "admin",
      "ketua",
      "wakil-ketua",
      "hakim",
      "panitera",
      "panitera-muda",
      "panitera-pengganti",
      "analis-perkara",
    ],
    iconBgClass: "bg-teal-100",
    iconFgClass: "text-teal-700",
    cardClass: "border-teal-200/80 bg-teal-50/70",
    badgeLabel: "Perkara",
  },
  {
    // Alat kerja harian kepaniteraan, jadi kartunya ada di dasbor - bukan hanya
    // dapat dicapai lewat alamat. Alat sehari-hari yang harus diingat
    // alamatnya akan berhenti dipakai.
    id: "bas",
    label: "Alat Bantu Tulis BAS",
    description: "Buka perkaranya, pilih pemeriksaan hari ini, lalu blangko BAS terbuka sudah terisi dari SIPP.",
    href: "/bas",
    icon: "file-text",
    roleIds: roles.map((role) => role.id),
    badgeLabel: "Kepaniteraan",
    iconBgClass: "bg-emerald-100 dark:bg-emerald-500/15",
    iconFgClass: "text-emerald-700 dark:text-emerald-200",
    cardClass: "border-emerald-200/80 bg-emerald-50/80 dark:border-emerald-500/20 dark:bg-slate-900/80",
  },
  {
    id: "e-kepegawaian",
    label: "E-Kepegawaian",
    description: "Administrasi pegawai, cuti, PCK, SKP, WFA, izin kehadiran, hasil rapat, dan dokumen internal.",
    href: "/e-kepegawaian",
    icon: "briefcase-business",
    roleIds: roles.map((role) => role.id),
    badgeLabel: "Aktif",
    iconBgClass: "bg-fuchsia-100 dark:bg-fuchsia-500/15",
    iconFgClass: "text-fuchsia-700 dark:text-fuchsia-200",
    cardClass: "border-fuchsia-200/80 bg-fuchsia-50/80 dark:border-fuchsia-500/20 dark:bg-slate-900/80",
  },
  {
    id: "e-keuangan",
    label: "E-Keuangan",
    description: "Contoh menu untuk pagu, realisasi, dan persetujuan transaksi.",
    href: "/apps/e-keuangan",
    icon: "wallet",
    roleIds: ["super-admin", "admin"],
    badgeLabel: "Rencana",
    iconBgClass: "bg-emerald-100 dark:bg-emerald-500/15",
    iconFgClass: "text-emerald-700 dark:text-emerald-200",
    cardClass: "border-emerald-200/80 bg-emerald-50/80 dark:border-emerald-500/20 dark:bg-slate-900/80",
    isDummy: true,
  },
  {
    id: "manajemen-aset",
    label: "Manajemen Aset",
    description: "Contoh menu untuk inventaris BMN, kendaraan dinas, dan dokumen pengadaan.",
    href: "/apps/manajemen-aset",
    icon: "archive",
    roleIds: ["super-admin", "admin"],
    badgeLabel: "Rencana",
    iconBgClass: "bg-amber-100 dark:bg-amber-500/15",
    iconFgClass: "text-amber-700 dark:text-amber-200",
    cardClass: "border-amber-200/80 bg-amber-50/80 dark:border-amber-500/20 dark:bg-slate-900/80",
    isDummy: true,
  },
  {
    id: "perpustakaan",
    label: "Perpustakaan",
    description: "Contoh menu untuk regulasi, SOP, dan pustaka digital internal.",
    href: "/apps/perpustakaan",
    icon: "book-open-text",
    roleIds: ["super-admin", "admin", "ketua", "wakil-ketua", "sekretaris", "panitera", "panitera-muda", "kasubag"],
    badgeLabel: "Rencana",
    iconBgClass: "bg-violet-100 dark:bg-violet-500/15",
    iconFgClass: "text-violet-700 dark:text-violet-200",
    cardClass: "border-violet-200/80 bg-violet-50/80 dark:border-violet-500/20 dark:bg-slate-900/80",
    isDummy: true,
  },
  {
    id: "audit-trail",
    label: "Audit Trail",
    description: "Catatan aktivitas penting untuk admin.",
    href: "/admin/audit-trail",
    icon: "scroll-text",
    roleIds: ["super-admin", "admin"],
    badgeLabel: "Internal",
    iconBgClass: "bg-slate-200 dark:bg-slate-500/15",
    iconFgClass: "text-slate-700 dark:text-slate-200",
    cardClass: "border-slate-200/80 bg-slate-50/80 dark:border-slate-500/20 dark:bg-slate-900/80",
  },
  {
    id: "gateway-notifikasi",
    label: "Notifikasi",
    description: "Contoh menu untuk pemberitahuan WhatsApp, email, dan pesan internal.",
    href: "/apps/gateway-notifikasi",
    icon: "message-circle-more",
    roleIds: ["super-admin", "admin"],
    badgeLabel: "Rencana",
    iconBgClass: "bg-lime-100 dark:bg-lime-500/15",
    iconFgClass: "text-lime-700 dark:text-lime-200",
    cardClass: "border-lime-200/80 bg-lime-50/80 dark:border-lime-500/20 dark:bg-slate-900/80",
    isDummy: true,
  },
];

function buildVisibility(roleId: Role["id"], enabledModuleIds: ModuleId[]): ModuleVisibility {
  const enabledSet = new Set(enabledModuleIds);
  const modulesState = Object.fromEntries(
    modules.map((module) => [module.id, enabledModuleIds.includes(module.id)])
  ) as Record<ModuleId, boolean>;
  const registeredModuleIds = new Set(modules.map((module) => module.id));

  for (const app of portalApps) {
    if (registeredModuleIds.has(app.id as ModuleId)) continue;
    modulesState[app.id as ModuleId] = enabledSet.has(app.id as ModuleId) || app.roleIds.includes(roleId);
  }

  return { roleId, modules: modulesState };
}

export const moduleVisibility: ModuleVisibility[] = [
  buildVisibility("super-admin", modules.map((module) => module.id)),
  buildVisibility("admin", [
    "aleta-ecourt-admin",
    "dashboard",
    "penugasan",
    "surat-masuk",
    "surat-keluar",
    "arsip",
    "statistik",
    "disposisi",
    "search",
    "mapping-user-jabatan",
    "audit",
    "laporan",
    "kepegawaian",
    "hr-settings",
    "judicia-legal-form",
    "aleta-bot", "aleta-ecourt",
    "e-status",
    "e-status-settings",
    "identity",
    "panel-settings",
    "public-access",
    "whatsapp-settings",
    "feedback",
    "system-updates",
    "backup-system",
    "database-viewer",
    "notifikasi",
    "notifikasi-wa",
    "admin-hub",
  ]),
  buildVisibility("ketua", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "judicia-legal-form", "e-status", "notifikasi", "penugasan", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search", "laporan"]),
  buildVisibility("wakil-ketua", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "judicia-legal-form", "e-status", "notifikasi", "penugasan", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search", "laporan"]),
  buildVisibility("hakim", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "judicia-legal-form", "notifikasi", "penugasan", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search"]),
  buildVisibility("sekretaris", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "notifikasi", "penugasan", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search"]),
  buildVisibility("panitera", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "judicia-legal-form", "e-status", "e-status-settings", "notifikasi", "penugasan", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search"]),
  buildVisibility("panitera-muda", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "judicia-legal-form", "e-status", "e-status-settings", "notifikasi", "penugasan", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search"]),
  buildVisibility("panitera-pengganti", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "judicia-legal-form", "e-status", "notifikasi", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search"]),
  buildVisibility("kasubag", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "notifikasi", "penugasan", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search"]),
  buildVisibility("jurusita", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "judicia-legal-form", "notifikasi", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search"]),
  buildVisibility("pranata-komputer", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "notifikasi", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search"]),
  buildVisibility("analis-keuangan", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "notifikasi", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search"]),
  buildVisibility("analis-perkara", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "judicia-legal-form", "e-status", "notifikasi", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search"]),
  buildVisibility("pelaksana", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "judicia-legal-form", "e-status", "notifikasi", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search"]),
  buildVisibility("pppk", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "notifikasi", "surat-masuk", "surat-keluar", "arsip", "statistik"]),
  buildVisibility("pejabat-struktural", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "judicia-legal-form", "e-status", "notifikasi", "penugasan", "surat-masuk", "surat-keluar", "arsip", "statistik", "disposisi", "search"]),
  buildVisibility("staf", ["dashboard", "aleta-bot", "aleta-ecourt", "kepegawaian", "judicia-legal-form", "e-status", "notifikasi", "surat-masuk", "surat-keluar", "arsip", "statistik"]),
];

export const letters: LetterDetail[] = [
  {
    id: "srt-001",
    type: "masuk",
    nomorSurat: "W21-A9/102/HM.01/IV/2026",
    tanggal: "2026-04-08T09:00:00+08:00",
    pengirim: "Pengadilan Tinggi Agama Makassar",
    perihal: "Permintaan laporan percepatan penyelesaian perkara triwulan I",
    status: "Dalam Disposisi",
    assignedUnit: "Kepaniteraan",
    confidentiality: "Penting",
    currentDispositionId: "dsp-003",
    tags: ["Triwulan I", "Prioritas", "Monitoring"],
    ringkasan:
      "Surat meminta rekap data penyelesaian perkara, rata-rata SLA disposisi, dan tindak lanjut perkara prioritas untuk bahan evaluasi triwulan I.",
    asalSurat: "PTA Makassar",
    tujuanSurat: "Ketua Pengadilan Agama",
    klasifikasi: "Laporan Kinerja",
    lampiran: ["rekap-template.xlsx", "petunjuk-pengisian.pdf"],
    viewerMode: "preview",
    qrCodeLabel: "Validasi internal Ketua PA - 8 Apr 2026",
    documentAspectRatio: 210 / 297,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-srt-001-a", "Drs. H. Malik", "628123450003", "Terkirim", "2026-04-08T09:18:00+08:00"),
      buildWhatsappDelivery("wa-srt-001-b", "M. Ridwan", "628123450006", "Terkirim", "2026-04-08T10:04:00+08:00"),
    ],
    documentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
  },
  {
    id: "srt-002",
    type: "keluar",
    nomorSurat: "W21-A9/154/KU.00/IV/2026",
    tanggal: "2026-04-07T14:30:00+08:00",
    pengirim: "Sekretariat Pengadilan Agama",
    perihal: "Surat tugas verifikasi arsip digital semester I",
    status: "Selesai",
    assignedUnit: "Kesekretariatan",
    confidentiality: "Biasa",
    currentDispositionId: "dsp-005",
    tags: ["Arsip", "Internal"],
    ringkasan:
      "Surat tugas internal terkait verifikasi dan penataan arsip digital semester I, termasuk pengecekan watermark dan indeks pencarian.",
    asalSurat: "Sekretaris",
    tujuanSurat: "Arsiparis",
    klasifikasi: "Surat Tugas",
    lampiran: ["jadwal-verifikasi.pdf"],
    viewerMode: "download",
    qrCodeLabel: "QR verifikasi Sekretaris - 7 Apr 2026",
    documentAspectRatio: 210 / 297,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-srt-002-a", "Budi Santoso", "628123450010", "Terkirim", "2026-04-07T15:02:00+08:00"),
    ],
    documentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
  },
  {
    id: "srt-003",
    type: "masuk",
    nomorSurat: "B-44/Bua.2/PL.09/IV/2026",
    tanggal: "2026-04-09T10:45:00+08:00",
    pengirim: "Badan Urusan Administrasi Mahkamah Agung",
    perihal: "Permintaan kesiapan audit keamanan aplikasi internal",
    status: "Baru",
    assignedUnit: "TI",
    confidentiality: "Rahasia",
    currentDispositionId: "dsp-006",
    tags: ["Keamanan", "Audit", "TI"],
    ringkasan:
      "Permintaan kesiapan audit keamanan aplikasi internal, termasuk status backup lokal, enkripsi, dan rekam jejak audit.",
    asalSurat: "BUA MA RI",
    tujuanSurat: "Super Admin dan Ketua",
    klasifikasi: "Audit Internal",
    lampiran: ["checklist-audit.pdf", "jadwal-audit.pdf"],
    viewerMode: "preview",
    qrCodeLabel: "Validasi audit internal - 9 Apr 2026",
    documentAspectRatio: 210 / 297,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-srt-003-a", "Drs. H. Malik", "628123450003", "Gagal", "2026-04-09T11:03:00+08:00"),
      buildWhatsappDelivery("wa-srt-003-b", "Drs. H. Fauzi", "628123450004", "Terkirim", "2026-04-09T11:04:00+08:00"),
    ],
  },
  {
    id: "srt-004",
    type: "keluar",
    nomorSurat: "W21-A9/160/OT.01/IV/2026",
    tanggal: "2026-04-10T08:10:00+08:00",
    pengirim: "Ketua Pengadilan Agama",
    perihal: "Instruksi pembaruan dashboard monitoring surat",
    status: "Dalam Disposisi",
    assignedUnit: "TI",
    confidentiality: "Penting",
    currentDispositionId: "dsp-007",
    tags: ["Dashboard", "TI", "Monitoring"],
    ringkasan:
      "Instruksi pimpinan untuk menata ulang dashboard monitoring surat dengan indikator WA, statistik disposisi, dan pencarian cepat.",
    asalSurat: "Ketua",
    tujuanSurat: "Pranata Komputer",
    klasifikasi: "Instruksi Pimpinan",
    lampiran: ["mockup-monitoring.pdf"],
    viewerMode: "download",
    qrCodeLabel: "QR validasi Ketua - 10 Apr 2026",
    documentAspectRatio: 210 / 297,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-srt-004-a", "Dian Saputra", "628123450002", "Terkirim", "2026-04-10T08:28:00+08:00"),
    ],
  },
  {
    id: "srt-005",
    type: "masuk",
    nomorSurat: "W21-A9/177/UM.02/IV/2026",
    tanggal: "2026-04-10T09:10:00+08:00",
    pengirim: "Badan Peradilan Agama",
    perihal: "Permintaan percepatan inventarisasi kebutuhan sarpras layanan",
    status: "Dalam Disposisi",
    assignedUnit: "Kesekretariatan",
    confidentiality: "Penting",
    currentDispositionId: "dsp-009",
    tags: ["Sarpras", "Kesekretariatan", "Prioritas"],
    ringkasan:
      "Surat meminta pembaruan data kebutuhan sarana prasarana layanan dan penjadwalan verifikasi lapangan dalam tiga hari kerja.",
    asalSurat: "Badilag MA",
    tujuanSurat: "Sekretaris / Kasubag Umum",
    klasifikasi: "Permintaan Data",
    lampiran: ["format-inventarisasi.xlsx", "pedoman-sarpras.pdf"],
    viewerMode: "preview",
    qrCodeLabel: "Validasi internal Sekretariat - 10 Apr 2026",
    documentAspectRatio: 210 / 297,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-srt-005-a", "Rina Kartika", "628123450008", "Terkirim", "2026-04-10T09:18:00+08:00"),
      buildWhatsappDelivery("wa-srt-005-b", "Dina Maharani", "628123450009", "Gagal", "2026-04-10T09:46:00+08:00"),
    ],
  },
];

export const dispositions: DispositionNode[] = [
  {
    id: "dsp-001",
    suratId: "srt-001",
    pengirimId: "usr-sekretaris",
    penerimaId: "usr-ketua",
    targetPositionId: "pos-ketua",
    instruksi: "Mohon arahan pimpinan terkait tenggat laporan kinerja triwulan I.",
    parentDispositionId: null,
    status: "Diteruskan",
    allowDownload: false,
    approvalQrCode: "QR-DSP-001",
    createdAt: "2026-04-08T09:20:00+08:00",
    urgent: true,
    bypass: false,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-dsp-001-a", "Drs. H. Malik", "628123450003", "Terkirim", "2026-04-08T09:20:00+08:00"),
    ],
  },
  {
    id: "dsp-002",
    suratId: "srt-001",
    pengirimId: "usr-ketua",
    penerimaId: "usr-panitera",
    targetPositionId: "pos-panitera",
    instruksi: "Koordinasikan rekap SLA dan kirim ke Panitera Muda Hukum untuk finalisasi data.",
    parentDispositionId: "dsp-001",
    status: "Diteruskan",
    allowDownload: true,
    approvalQrCode: "QR-DSP-002",
    createdAt: "2026-04-08T10:05:00+08:00",
    urgent: true,
    bypass: false,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-dsp-002-a", "M. Ridwan", "628123450006", "Terkirim", "2026-04-08T10:06:00+08:00"),
    ],
  },
  {
    id: "dsp-003",
    suratId: "srt-001",
    pengirimId: "usr-panitera",
    penerimaId: "usr-ahmad",
    targetPositionId: "pos-panitera-muda-hukum",
    instruksi: "Siapkan draf tanggapan, lampirkan rekap 3 perkara prioritas dan update status penanganan.",
    parentDispositionId: "dsp-002",
    status: "Sedang Dikerjakan",
    allowDownload: true,
    approvalQrCode: "QR-DSP-003",
    createdAt: "2026-04-08T11:00:00+08:00",
    urgent: true,
    bypass: false,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-dsp-003-a", "Ahmad Rizki", "628123450007", "Terkirim", "2026-04-08T11:01:00+08:00"),
    ],
  },
  {
    id: "dsp-004",
    suratId: "srt-002",
    pengirimId: "usr-sekretaris",
    penerimaId: "usr-budi",
    targetPositionId: "pos-arsiparis",
    instruksi: "Verifikasi folder arsip digital semester I dan unggah checklist penyelesaian.",
    parentDispositionId: null,
    status: "Selesai",
    allowDownload: true,
    approvalQrCode: "QR-DSP-004",
    createdAt: "2026-04-07T15:00:00+08:00",
    urgent: false,
    bypass: false,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-dsp-004-a", "Budi Santoso", "628123450010", "Terkirim", "2026-04-07T15:01:00+08:00"),
    ],
    followUpNote: "Checklist verifikasi arsip telah dilengkapi dan folder indeks diperbarui.",
    followUpFileName: "checklist-verifikasi-arsip.pdf",
  },
  {
    id: "dsp-005",
    suratId: "srt-002",
    pengirimId: "usr-budi",
    penerimaId: "usr-sekretaris",
    targetPositionId: "pos-sekretaris",
    instruksi: "Pelaporan penyelesaian verifikasi arsip semester I.",
    parentDispositionId: "dsp-004",
    status: "Selesai",
    allowDownload: true,
    approvalQrCode: "QR-DSP-005",
    createdAt: "2026-04-08T08:10:00+08:00",
    urgent: false,
    bypass: false,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-dsp-005-a", "Siti Nurhayati", "628123450005", "Terkirim", "2026-04-08T08:11:00+08:00"),
    ],
    followUpNote: "Seluruh arsip semester I sudah diverifikasi dan ditandai sesuai klasifikasi.",
    followUpFileName: "laporan-verifikasi-semester-1.pdf",
  },
  {
    id: "dsp-006",
    suratId: "srt-003",
    pengirimId: "usr-super",
    penerimaId: "usr-ketua",
    targetPositionId: "pos-ketua",
    instruksi: "Mohon penetapan PIC audit keamanan dan jadwal koordinasi internal.",
    parentDispositionId: null,
    status: "Menunggu Tindak Lanjut",
    allowDownload: false,
    approvalQrCode: "QR-DSP-006",
    createdAt: "2026-04-09T11:05:00+08:00",
    urgent: true,
    bypass: false,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-dsp-006-a", "Drs. H. Malik", "628123450003", "Gagal", "2026-04-09T11:05:00+08:00"),
    ],
  },
  {
    id: "dsp-007",
    suratId: "srt-004",
    pengirimId: "usr-ketua",
    penerimaId: "usr-admin",
    targetPositionId: "pos-pranata-komputer",
    instruksi: "Lakukan pembaruan tampilan dashboard monitoring dengan indikator WA dan quick search.",
    parentDispositionId: null,
    status: "Sedang Dikerjakan",
    allowDownload: true,
    approvalQrCode: "QR-DSP-007",
    createdAt: "2026-04-10T08:30:00+08:00",
    urgent: true,
    bypass: true,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-dsp-007-a", "Dian Saputra", "628123450002", "Terkirim", "2026-04-10T08:31:00+08:00"),
    ],
  },
  {
    id: "dsp-008",
    suratId: "srt-005",
    pengirimId: "usr-sekretaris",
    penerimaId: "usr-rina",
    targetPositionId: "pos-kasubag-umum",
    instruksi: "Telaah kebutuhan sarpras, sinkronkan dengan Staf Umum, lalu teruskan ke pimpinan bila ada item prioritas.",
    parentDispositionId: null,
    status: "Diteruskan",
    allowDownload: false,
    approvalQrCode: "QR-DSP-008",
    createdAt: "2026-04-10T09:20:00+08:00",
    urgent: true,
    bypass: false,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-dsp-008-a", "Rina Kartika", "628123450008", "Terkirim", "2026-04-10T09:21:00+08:00"),
    ],
  },
  {
    id: "dsp-009",
    suratId: "srt-005",
    pengirimId: "usr-rina",
    penerimaId: "usr-dina",
    targetPositionId: "pos-staf-umum",
    instruksi: "Siapkan daftar inventarisasi awal dan tandai kebutuhan yang perlu eskalasi ke pimpinan hari ini.",
    parentDispositionId: "dsp-008",
    status: "Sedang Dikerjakan",
    allowDownload: false,
    approvalQrCode: "QR-DSP-009",
    createdAt: "2026-04-10T09:45:00+08:00",
    urgent: true,
    bypass: false,
    whatsappDeliveries: [
      buildWhatsappDelivery("wa-dsp-009-a", "Dina Maharani", "628123450009", "Gagal", "2026-04-10T09:46:00+08:00"),
    ],
  },
];

export const auditPreviews: AuditPreview[] = [
  {
    id: "adt-001",
    action: "LOGIN_SUCCESS",
    entity: "auth.session",
    userNameSnapshot: "Drs. H. Malik",
    userPositionSnapshot: "Ketua Pengadilan",
    ipAddress: "10.10.0.12",
    timestamp: "2026-04-10T08:05:00+08:00",
  },
  {
    id: "adt-002",
    action: "CREATE_DISPOSITION",
    entity: "disposisi.dsp-007",
    userNameSnapshot: "Drs. H. Malik",
    userPositionSnapshot: "Ketua Pengadilan",
    ipAddress: "10.10.0.12",
    timestamp: "2026-04-10T08:30:00+08:00",
  },
  {
    id: "adt-003",
    action: "UPLOAD_FOLLOW_UP",
    entity: "surat.srt-002",
    userNameSnapshot: "Budi Santoso",
    userPositionSnapshot: "Arsiparis",
    ipAddress: "10.10.0.31",
    timestamp: "2026-04-08T08:09:00+08:00",
  },
];

export const waStatusPreview: WhatsAppStatusPreview = {
  id: "wa-main",
  sessionName: "PA-MAKASSAR-NOTIF",
  status: "Online",
  lastConnected: "2026-04-10T07:50:00+08:00",
};

export const quickSearchSeeds: SearchResult[] = [
  {
    id: "srch-001",
    type: "surat",
    title: "Permintaan laporan percepatan penyelesaian perkara triwulan I",
    excerpt: "Surat dari PTA Makassar dengan fokus pada rekap SLA dan penyelesaian perkara prioritas.",
    href: "/surat/srt-001",
    keywords: ["laporan", "triwulan", "perkara", "sla"],
  },
  {
    id: "srch-002",
    type: "surat",
    title: "Permintaan kesiapan audit keamanan aplikasi internal",
    excerpt: "Surat rahasia terkait audit keamanan, backup, dan kesiapan enkripsi data.",
    href: "/surat/srt-003",
    keywords: ["audit", "keamanan", "backup", "enkripsi"],
  },
  {
    id: "srch-003",
    type: "disposisi",
    title: "Disposisi Panitera Muda Hukum - rekap 3 perkara prioritas",
    excerpt: "Tindak lanjut aktif yang sedang dikerjakan oleh Ahmad Rizki.",
    href: "/disposisi/dsp-003",
    keywords: ["ahmad", "perkara", "prioritas", "rekap"],
  },
  {
    id: "srch-004",
    type: "pengguna",
    title: "Ahmad Rizki",
    excerpt: "Panitera Muda Hukum, unit Kepaniteraan.",
    href: "/admin/mapping-user-jabatan",
    keywords: ["ahmad", "panitera", "kepaniteraan"],
  },
];
