export const APP_VERSION = "0.1.0-beta.7";
export const APP_VERSION_LABEL = "ALETA 0.1.0 Beta - Pengiriman WhatsApp Otomatis Aktif";

export type PatchNote = {
  version: string;
  title: string;
  date: string;
  status: string;
  summary: string;
  added: string[];
  changed: string[];
  fixed: string[];
  security: string[];
  operationalNotes: string[];
  knownLimitations: string[];
  details?: Array<{
    title: string;
    items: string[];
  }>;
};

export const PATCH_NOTES: PatchNote[] = [
  {
    version: "0.1.0-beta.7",
    title: "ALETA 0.1.0-beta.7 - Pengiriman WhatsApp Otomatis Aktif dengan Pengamanan",
    date: "2026-05-03",
    status: "Aktif dengan Pengamanan",
    summary:
      "Rilis ini menetapkan status operasional terbaru: pengiriman WhatsApp otomatis sudah aktif dengan pengamanan. Uji terbatas berhasil, pemeriksaan keamanan lulus, dan operator tetap wajib memantau Antrean Pesan, Pesan Gagal, Persetujuan, serta Jam Aman Pengiriman.",
    added: [
      "Status resmi baru: Pengiriman WhatsApp Otomatis Aktif dengan Pengamanan.",
      "Catatan operator yang menjelaskan bahwa uji terbatas sudah berhasil dan pengiriman otomatis dapat berjalan sesuai aturan keamanan.",
      "Panduan monitoring hari pertama dengan bahasa yang lebih mudah dipahami admin.",
      "Penjelasan mode aman bila terjadi gangguan pada WhatsApp, Antrean Pesan, atau Pesan Gagal.",
    ],
    changed: [
      "Narasi status WhatsApp diperbarui dari tahap kesiapan menjadi aktif operasional dengan pengamanan.",
      "Panduan pengguna menjelaskan bahwa user tidak perlu scan QR atau menghubungkan WhatsApp sendiri.",
      "Panduan admin menekankan pemantauan WhatsApp Gateway, Pemroses Pesan, Antrean Pesan, Pesan Gagal, Persetujuan, Jam Aman Pengiriman, dan batas pengiriman.",
      "Runbook operator diselaraskan dengan kondisi production aktif, bukan lagi tahap kesiapan awal.",
    ],
    fixed: [
      "Narasi lama dari tahap kesiapan awal sudah diperbaiki agar sesuai runtime aktual.",
      "Status operasional kini konsisten: WhatsApp terhubung, Pemroses Pesan aktif, Antrean Pesan sehat, Pesan Gagal aktif 0, dan Persetujuan tertunda 0.",
      "Istilah teknis di area pengguna diganti dengan padanan yang lebih mudah dipahami, seperti Pengiriman WhatsApp otomatis, Pengamanan pengiriman, Batas pengiriman, dan Wajib persetujuan.",
    ],
    security: [
      "Pengiriman otomatis aktif dengan pengamanan untuk mencegah salah kirim, kirim ganda, dan pengiriman massal tanpa persetujuan.",
      "Broadcast tetap wajib persetujuan.",
      "Notifikasi pihak luar tetap wajib persetujuan.",
      "Kirim ulang massal tetap wajib persetujuan.",
      "Batas pengiriman aktif: maksimal 5 penerima per alur biasa, 10 pesan per batch, 5 pesan per menit, 20 pesan per jam, dan 50 pesan per hari.",
      "Jika ada Pesan Gagal atau antrean bermasalah, operator harus menahan pengiriman dan memeriksa penyebabnya sebelum tindakan lanjut.",
    ],
    operationalNotes: [
      "Uji terbatas pengiriman WhatsApp sudah berhasil.",
      "Data pegawai 42/42 siap menerima notifikasi WhatsApp sesuai alur kerja dan hak akses.",
      "Pemeriksaan keamanan berhasil dan simulasi tanpa kirim berhasil.",
      "Penjadwal dan pengingat berjalan sesuai aturan keamanan, Jam Aman Pengiriman, dan kebijakan backlog.",
      "Full production bukan broadcast bebas; pengiriman berisiko tetap harus disetujui terlebih dahulu.",
    ],
    knownLimitations: [
      "Monitoring hari pertama tetap wajib, terutama untuk WhatsApp terhubung, Pemroses Pesan, Antrean Pesan, Pesan Gagal, Persetujuan, dan batas pengiriman.",
      "Jika ditemukan salah penerima, kirim ganda, antrean gagal, atau Pesan Gagal aktif, segera kembali ke mode aman dan jangan kirim ulang otomatis.",
      "Broadcast, pengiriman ke pihak luar, kirim ulang massal, pengiriman tidak wajar, dan backlog penjadwal tetap tidak boleh berjalan bebas.",
    ],
    details: [
      {
        title: "Status Operasional Terbaru",
        items: [
          "Pengiriman WhatsApp otomatis sudah aktif dengan pengamanan.",
          "Uji terbatas sudah berhasil.",
          "WhatsApp Gateway terhubung.",
          "Pemroses Pesan aktif.",
          "Antrean Pesan sehat.",
          "Pesan Gagal aktif 0.",
          "Persetujuan tertunda 0.",
          "Data pegawai 42/42 siap menerima notifikasi.",
          "Jam Aman Pengiriman aktif.",
          "Batas pengiriman aktif.",
          "Pencegahan kirim ganda aktif.",
          "Mode aman tersedia bila terjadi gangguan.",
        ],
      },
      {
        title: "Pengamanan Pengiriman",
        items: [
          "Sistem membatasi jumlah pesan agar tidak terjadi pengiriman massal yang keliru.",
          "Sistem mencegah pesan yang sama terkirim berulang kepada penerima yang sama.",
          "Pengiriman berisiko tetap harus disetujui terlebih dahulu.",
          "Semua pengiriman penting dicatat untuk audit.",
          "Jika ada anomali, operator dapat kembali ke mode aman.",
        ],
      },
      {
        title: "Tetap Wajib Persetujuan",
        items: [
          "Broadcast.",
          "Notifikasi pihak luar.",
          "Kirim ulang massal.",
          "Pengiriman tidak wajar.",
          "Backlog dari penjadwal.",
        ],
      },
      {
        title: "Yang Harus Dipantau Operator",
        items: [
          "WhatsApp Gateway tetap terhubung.",
          "Pemroses Pesan tetap aktif.",
          "Antrean Pesan tidak menumpuk.",
          "Pesan Gagal aktif tetap 0.",
          "Persetujuan tertunda dipantau.",
          "Batas pengiriman tidak terlampaui.",
          "Penjadwal dan pengingat berjalan dalam Jam Aman Pengiriman.",
          "Masukan pengguna dan tinjauan Pertanyaan Publik dipantau.",
        ],
      },
    ],
  },
  {
    version: "0.1.0-beta.6",
    title: "ALETA 0.1.0-beta.6 - Launch Internal & Pengaman WhatsApp",
    date: "2026-05-03",
    status: "Full Internal Operational Launch Ready",
    summary:
      "Rilis ini menstabilkan ALETA untuk penggunaan operasional internal kantor, memperbaiki WhatsApp Gateway, menambahkan pemeriksaan otomatis, memperbaiki login 1 klik, mempercepat render portal, menyiapkan server kantor, serta menambahkan pengaman WhatsApp untuk mencegah salah kirim, kirim ganda, dan pengiriman massal keliru.",
    added: [
      "Kesiapan Launch Operasional Internal untuk Portal ALETA, Manajemen Surat, Pusat Tugas, Patch Notes, Panduan, Pusat Masukan, dan Admin Monitoring.",
      "Pemeriksaan otomatis untuk portal, ALETA Bot, Layanan WhatsApp, Pemroses Pesan, Antrean Pesan, Pesan Gagal, Persetujuan, nomor WhatsApp pegawai, Jam Aman Pengiriman, Jembatan AI, Penjadwal/Pengingat, dan tinjauan Pertanyaan Publik.",
      "Kesiapan server kantor, runbook deployment, checklist launch, rencana rollback, monitoring hari pertama, dan SOP operasional.",
      "Pengaman WhatsApp dengan pencegahan kirim ganda, batas pengiriman, persetujuan wajib, audit log, simulasi tanpa kirim, pemeriksaan risiko, audit jalur kirim lama, dan kontrol rollback.",
      "Kualitas data WhatsApp: 42/42 pegawai aktif eligible, nomor dummy 0, duplikasi 0, format invalid 0, excluded 0.",
    ],
    changed: [
      "WhatsApp Gateway distabilkan dengan pengaman satu koneksi, tombol hubungkan yang aman diulang, pencegahan koneksi ganda, status sesi WhatsApp yang lebih jelas, dan endpoint diagnostik.",
      "Login kini lebih stabil dalam 1 klik: field/tombol menunggu halaman siap, klik ganda diabaikan, sesi diperbarui setelah login, dan pengguna diarahkan stabil ke /portal.",
      "Portal lebih cepat karena data utama dimuat terlebih dahulu dan data berat dimuat bertahap di belakang layar.",
      "Riwayat beta.6: Pengiriman Bot saat itu masih dikelola sebagai tahap kesiapan dan hanya dinyalakan sementara untuk uji terbatas.",
      "Riwayat beta.6: Penjadwal/Pengingat saat itu dicatat dalam mode kesiapan sebelum status aktif operasional terbaru ditetapkan di beta.7.",
    ],
    fixed: [
      "Pesan gagal dari validasi Phase 4 tidak lagi menjadi penghambat: masuk riwayat sudah ditangani tanpa kirim ulang, tanpa antrean baru, dan tanpa hapus permanen.",
      "Persetujuan Phase 4 sudah ditolak/dibatalkan sebagai artefak validasi dan tidak memicu pengiriman.",
      "Antrean Pesan tetap sehat setelah pilot WhatsApp internal: menunggu 0, diproses 0, gagal 0, Pesan Gagal aktif 0, Persetujuan menunggu 0.",
      "Status Layanan WhatsApp tidak mengekspos QR mentah dan kendala sesi browser ditampilkan lebih manusiawi.",
      "Shutdown/cleanup WhatsApp menggunakan client.destroy() secara aman, bukan logout, tanpa menghapus .wwebjs_auth dan tanpa mengganti session name.",
    ],
    security: [
      "Riwayat beta.6: saat catatan ini pertama dibuat, pengiriman otomatis masih tahap kesiapan. Status terbaru ada di 0.1.0-beta.7.",
      "Broadcast, notifikasi pihak luar, kirim ulang massal, pengiriman tidak wajar, dan backlog penjadwal tetap membutuhkan persetujuan.",
      "Pengaman aktif operasional mencegah salah kirim, kirim ganda, pengiriman massal keliru, jalur kirim langsung tanpa pengaman, penjadwal liar, kirim ulang massal, broadcast tanpa persetujuan, dan notifikasi pihak luar tanpa persetujuan.",
      "Cap awal konservatif: maxRecipientsPerEvent 5, maxMessagesPerBatch 10, maxMessagesPerMinute 5, maxMessagesPerHour 20, maxMessagesPerDay 50.",
      "Mode aman Pertanyaan Publik hanya memakai aturan/template/kueri resmi; pertanyaan yang belum dikenali masuk tinjauan admin dan tidak dijawab bebas.",
    ],
    operationalNotes: [
      "Office Server Launch berstatus GO untuk penggunaan internal: portal dapat diakses, Manajemen Surat siap, ALETA Bot dapat diakses, WhatsApp terhubung, Pemroses Pesan aktif, Antrean Pesan sehat, dan Jembatan AI tersinkron.",
      "Pilot WhatsApp 1 pesan internal ke DERRY BRIANTONO (Hakim), 628****6962 berhasil terkirim dengan Pengiriman Bot dinyalakan sementara lalu dikembalikan nonaktif.",
      "Pilot WhatsApp kecil 3 penerima internal berhasil: DERRY BRIANTONO, S.H. (Hakim) 628****6962; ABDUL SALAM, S.HI. MH. (Ketua) 628****3055; AKBAR ALI, S.H.I. (Wakil Ketua) 628****1382.",
      "Pilot kecil menghasilkan 3 pesan masuk antrean, 3 terkirim, 0 gagal, 0 dilewati, Pesan Gagal aktif 0, Persetujuan menunggu 0.",
      "Jika ada pesan gagal atau Pesan Gagal aktif, tahan pengiriman otomatis, matikan Pengiriman Bot, jangan kirim ulang otomatis, dan tinjau item satu per satu.",
    ],
    knownLimitations: [
      "Riwayat beta.6: pengiriman otomatis saat itu masih dicatat sebagai tahap kesiapan. Status terbaru setelah uji terbatas berhasil ada di 0.1.0-beta.7.",
      "Riwayat beta.6: Jam Aman Pengiriman tetap menjadi syarat penting. Status terbaru menyatakan uji terbatas sudah berhasil.",
      "Perubahan berikut belum dimasukkan sebagai selesai di patch notes ini karena belum ada laporan hasil eksekusi final: optimasi /api/surat pagination 5/10/25/50/100/Semua, grid Dashboard Manajemen Surat, Admin Asisten Hakim, dan perbaikan PLH/PLT Hakim untuk Ketua/Wakil Ketua.",
      "Aktif operasional bukan broadcast bebas; broadcast, notifikasi pihak luar, kirim ulang massal, pengiriman tidak wajar, dan backlog penjadwal tetap perlu persetujuan.",
      "Monitoring hari pertama tetap wajib untuk WhatsApp terhubung, Pemroses Pesan aktif, Antrean Pesan menunggu/diproses/gagal, Pesan Gagal aktif, Persetujuan menunggu, batas pengiriman, dan Penjadwal/Pengingat.",
    ],
    details: [
      {
        title: "Highlights",
        items: [
          "ALETA siap untuk Full Internal Operational Launch.",
          "Portal, Manajemen Surat, Pusat Tugas, Patch Notes, Panduan, Pusat Masukan, dan Admin Monitoring siap digunakan internal.",
          "WhatsApp Gateway distabilkan.",
          "Preflight dan smoke dry-run otomatis tersedia.",
          "Pilot WhatsApp internal berhasil.",
          "Login 1 klik diperbaiki.",
          "Portal lebih cepat karena data berat tidak lagi memblokir shell awal.",
          "Office Server readiness dan runbook dibuat.",
          "WhatsApp Production Guard ditambahkan.",
          "Data nomor WhatsApp pegawai sudah 42/42 eligible.",
          "Riwayat beta.6: pengiriman otomatis masih tahap kesiapan. Status terbaru ada di 0.1.0-beta.7.",
        ],
      },
      {
        title: "WhatsApp Gateway Stabilization",
        items: [
          "Singleton guard untuk WhatsApp client.",
          "Connect endpoint idempotent.",
          "Pencegahan initialize dobel.",
          "Status browser_locked.",
          "Error browser/session lock ditampilkan manusiawi.",
          "Cleanup shutdown aman dengan client.destroy(), bukan logout.",
          "Tidak hapus .wwebjs_auth.",
          "Tidak ganti session name.",
          "Diagnostics endpoint: GET /internal/aleta-bot/whatsapp/diagnostics.",
          "Status runtime tidak mengekspos QR raw.",
        ],
      },
      {
        title: "Queue, Dead-letter, dan Approval Cleanup",
        items: [
          "Phase 4 Validation dead-letter sudah tidak aktif.",
          "Dead-letter aktif 0.",
          "Phase 4 masuk resolved history.",
          "Approval Phase 4 sudah ditolak/cancel.",
          "Tidak ada resend.",
          "Tidak ada enqueue real.",
          "Tidak ada hard-delete.",
          "Queue tetap sehat.",
        ],
      },
      {
        title: "Automated Preflight & Smoke Test",
        items: [
          "Script: scripts/aleta-preflight.mjs.",
          "Script: scripts/aleta-smoke-dry-run.mjs.",
          "Script: scripts/aleta-whatsapp-limited-test.mjs.",
          "Script: scripts/aleta-whatsapp-bot-enabled-test.mjs.",
          "Script: scripts/aleta-whatsapp-small-pilot.mjs.",
          "Laporan: reports/aleta-preflight-latest.md/json.",
          "Laporan: reports/aleta-smoke-dry-run-latest.md/json.",
          "Laporan: reports/aleta-whatsapp-limited-test-latest.md/json.",
          "Laporan: reports/aleta-whatsapp-bot-enabled-test-latest.md/json.",
          "Laporan: reports/aleta-whatsapp-small-pilot-latest.md/json.",
          "Preflight/smoke mengecek portal, ALETA Bot, WhatsApp runtime, worker, queue, dead-letter, approval pending, nomor WhatsApp pegawai, safe sending window, AI Bridge, scheduler/reminder, dan Public Q&A review.",
        ],
      },
      {
        title: "Pilot WhatsApp Internal",
        items: [
          "Uji 1 pesan internal ke DERRY BRIANTONO (Hakim), 628****6962 berhasil.",
          "botEnabled hanya dinyalakan sementara.",
          "Pesan sent.",
          "Tidak broadcast.",
          "Tidak resend.",
          "Tidak scheduler production.",
          "botEnabled dikembalikan false.",
          "Pilot kecil 3 penerima: DERRY BRIANTONO, S.H. - Hakim - 628****6962.",
          "Pilot kecil 3 penerima: ABDUL SALAM, S.HI. MH. - Ketua - 628****3055.",
          "Pilot kecil 3 penerima: AKBAR ALI, S.H.I. - Wakil Ketua - 628****1382.",
          "Hasil pilot kecil: enqueued 3, sent 3, failed 0, skipped 0, dead-letter aktif 0, approval pending 0.",
        ],
      },
      {
        title: "Office Server Launch Readiness",
        items: [
          "Office Server Launch: GO.",
          "Portal reachable.",
          "Manajemen Surat siap dipakai internal.",
          "ALETA Bot runtime reachable.",
          "WhatsApp connected.",
          "Worker aktif.",
          "Queue sehat.",
          "Dead-letter aktif 0.",
          "Approval pending 0.",
          "AI Bridge synced.",
          "Riwayat beta.6: Pengiriman Bot dan Penjadwal/Pengingat masih berada di tahap kesiapan.",
          "Script: scripts/start-aleta-office.ps1.",
          "Script: scripts/stop-aleta-office.ps1.",
          "Script: scripts/status-aleta-office.ps1.",
          "Script: scripts/restart-aleta-office-safe.ps1.",
          "Script: scripts/aleta-office-server-readiness.mjs.",
          "Runbook/SOP: reports/aleta-office-server-deployment-runbook.md.",
          "Runbook/SOP: reports/aleta-office-server-launch-checklist.md.",
          "Runbook/SOP: reports/aleta-office-server-rollback-plan.md.",
          "Runbook/SOP: reports/aleta-office-server-day-one-monitoring.md.",
          "Runbook/SOP: reports/aleta-sop-whatsapp-disconnected.md.",
          "Runbook/SOP: reports/aleta-sop-dead-letter.md.",
          "Runbook/SOP: reports/aleta-sop-queue-failed.md.",
          "Runbook/SOP: reports/aleta-sop-rollback-safe-mode.md.",
        ],
      },
      {
        title: "WhatsApp Production Guard",
        items: [
          "Production guard untuk mencegah salah kirim, kirim ganda, mass-send keliru, direct-send bypass, scheduler liar, resend massal, broadcast tanpa approval, dan external notification tanpa approval.",
          "Service: aleta_bot/services/productionGuardService.js.",
          "Service: aleta_bot/services/idempotencyService.js.",
          "Service: aleta_bot/services/messageService.js.",
          "Config: aleta_bot/config/aleta-runtime.json.",
          "Validator: scripts/aleta-whatsapp-production-risk-check.mjs.",
          "Validator: scripts/aleta-whatsapp-production-shadow-run.mjs.",
          "Validator: scripts/aleta-whatsapp-production-canary.mjs.",
          "Validator: scripts/aleta-whatsapp-production-launch.mjs.",
          "Validator: scripts/aleta-whatsapp-number-quality.mjs.",
          "Validator: scripts/aleta-idempotency-production-proof.mjs.",
          "Validator: scripts/aleta-legacy-send-path-audit.mjs.",
          "Validator: scripts/aleta-production-gate-rerun.mjs.",
          "Validator: scripts/aleta-production-config-prepare.mjs.",
        ],
      },
      {
        title: "Data Hygiene Nomor WhatsApp",
        items: [
          "Sebelumnya ditemukan 2 nomor dummy.",
          "Sebelumnya ditemukan 2 duplicate groups.",
          "Sebelumnya ditemukan 6 excluded recipients.",
          "Setelah koreksi: pegawai aktif 42.",
          "Eligible WhatsApp production 42/42.",
          "Missing WA 0.",
          "Priority missing 0.",
          "Dummy number 0.",
          "Duplicate groups 0.",
          "Invalid format 0.",
          "Excluded recipients 0.",
          "All 42 active employees are eligible for WhatsApp production.",
        ],
      },
      {
        title: "Production Risk Gate & Shadow-run",
        items: [
          "Risk gate PASS untuk runtime.",
          "Risk gate PASS untuk queue.",
          "Risk gate PASS untuk data.",
          "Risk gate PASS untuk recipient resolver.",
          "Risk gate PASS untuk template.",
          "Risk gate PASS untuk idempotency.",
          "Risk gate PASS untuk duplicate prevention.",
          "Risk gate PASS untuk cap/outlier.",
          "Risk gate PASS untuk scheduler/reminder readiness.",
          "Risk gate PASS untuk approval.",
          "Risk gate PASS untuk Public Q&A safe mode.",
          "Risk gate PASS untuk rollback.",
          "Shadow-run PASS untuk Internal disposition notification.",
          "Shadow-run PASS untuk Internal incoming letter notification.",
          "Shadow-run PASS untuk Deadline H-1 reminder.",
          "Shadow-run PASS untuk Public Q&A safe mode.",
          "Shadow-run PASS untuk Broadcast capability gate.",
          "Shadow-run PASS untuk External notification gate.",
          "Shadow-run PASS untuk Mass resend capability gate.",
          "Shadow-run tidak mengirim WhatsApp real.",
        ],
      },
      {
        title: "Cap, Rate Limit, dan Approval Gate",
        items: [
          "maxRecipientsPerEvent: 5.",
          "maxMessagesPerBatch: 10.",
          "maxMessagesPerMinute: 5.",
          "maxMessagesPerHour: 20.",
          "maxMessagesPerDay: 50.",
          "broadcastRequiresApproval: true.",
          "externalNotificationRequiresApproval: true.",
          "massResendRequiresApproval: true.",
          "outlierRequiresApproval: true.",
          "Full production bukan broadcast bebas.",
          "Broadcast/external/mass resend tetap approval-gated.",
        ],
      },
      {
        title: "Public Q&A Safe Mode",
        items: [
          "Hanya intent/template/query resmi.",
          "Unknown/fallback masuk human review.",
          "Tidak menjawab bebas.",
          "Tidak membocorkan data internal.",
          "Tidak memakai query DB liar.",
          "Intent tidak eligible tidak masuk production.",
        ],
      },
      {
        title: "Login dan Navigasi Portal",
        items: [
          "Login 1 klik diperbaiki.",
          "Root cause: field/tombol bisa aktif sebelum hydration selesai.",
          "Root cause: klik/input pertama bisa hilang atau terbaca kosong.",
          "Root cause: race antara router.replace('/portal') dan router.refresh().",
          "Perbaikan: field/tombol disabled sampai client siap.",
          "Perbaikan: submit terkontrol.",
          "Perbaikan: duplicate submit diabaikan.",
          "Perbaikan: session refetch setelah sign-in.",
          "Perbaikan: redirect stabil ke /portal.",
          "Perbaikan: router.refresh() dihapus dari success path.",
          "PortalProvider tidak lagi memblokir shell sampai data berat selesai.",
          "Data critical dimuat dulu.",
          "Data berat dimuat background.",
          "Portal shell tampil lebih cepat.",
        ],
      },
      {
        title: "Validasi",
        items: [
          "node --check app.js.",
          "node --check whatsapp.js.",
          "node --check services/whatsappStatusService.js.",
          "node --check routes/internalGatewayRoutes.js.",
          "node --check services/productionGuardService.js.",
          "node --check services/messageService.js.",
          "node --check services/idempotencyService.js.",
          "npx tsc --noEmit --pretty false.",
          "npm run lint.",
          "npm run build.",
          "npm test.",
          "Validasi terakhir PASS.",
        ],
      },
      {
        title: "Status Akhir Rilis",
        items: [
          "Boleh dipakai: Portal ALETA.",
          "Boleh dipakai: Manajemen Surat.",
          "Boleh dipakai: Pusat Tugas.",
          "Boleh dipakai: Patch Notes.",
          "Boleh dipakai: Panduan.",
          "Boleh dipakai: Pusat Masukan.",
          "Boleh dipakai: Admin monitoring.",
          "Boleh dipakai: ALETA Bot runtime.",
          "Boleh dipakai: WhatsApp connected.",
          "Boleh dipakai: Preflight.",
          "Boleh dipakai: Smoke dry-run.",
          "Boleh dipakai: Office server internal launch.",
          "Riwayat beta.6: WhatsApp otomatis, Penjadwal/Pengingat, dan mode aman Pertanyaan Publik masih dicatat sebagai siap gate.",
          "Tetap approval-gated: Broadcast.",
          "Tetap approval-gated: External notification.",
          "Tetap approval-gated: Mass resend.",
          "Tetap approval-gated: Outlier send.",
          "Tetap approval-gated: Scheduler backlog.",
        ],
      },
      {
        title: "Risiko Tersisa dan Langkah Lanjutan",
        items: [
          "Riwayat beta.6: uji terbatas dijadwalkan dalam Jam Aman Pengiriman 07:30-21:00.",
          "Status terbaru: uji terbatas sudah berhasil dan pengiriman otomatis aktif dengan pengamanan.",
          "Pantau hari pertama: WhatsApp connected.",
          "Pantau hari pertama: worker aktif.",
          "Pantau hari pertama: queue pending/processing/failed.",
          "Pantau hari pertama: dead-letter aktif.",
          "Pantau hari pertama: approval pending.",
          "Pantau hari pertama: cap/rate-limit.",
          "Pantau hari pertama: scheduler/reminder.",
          "Jika queue failed atau dead-letter muncul: pause automation.",
          "Jika queue failed atau dead-letter muncul: set botEnabled=false.",
          "Jika queue failed atau dead-letter muncul: jangan resend otomatis.",
          "Jika queue failed atau dead-letter muncul: review item satu per satu.",
        ],
      },
      {
        title: "Not Yet Included / Pending Execution",
        items: [
          "Optimasi /api/surat dengan pagination 5/10/25/50/100/Semua.",
          "Perbaikan grid Dashboard Manajemen Surat.",
          "Admin fitur Asisten Hakim untuk edit URL AI dan role/user toggle.",
          "Perbaikan PLH/PLT agar Hakim bisa menjadi kandidat Ketua/Wakil Ketua.",
        ],
      },
    ],
  },
  {
    version: "0.1.0-beta.5",
    title: "Final Pilot Verification dan Data Readiness",
    date: "2026-05-01",
    status: "Beta",
    summary:
      "Rilis beta internal untuk memperketat verifikasi pilot terbatas, readiness report, smoke test final, runbook pilot, dan data readiness nomor WhatsApp sebelum operasional terbatas.",
    added: [
      "Runbook Pilot Terbatas ALETA di Panduan Penggunaan.",
      "Smoke test final dengan pemeriksaan auth guard, queue, safe sending window, pilot readiness, dan no-secret response.",
      "Readiness report yang memuat safe sending window, AI Bridge, legacy fallback terbaru, smoke test availability, dan prioritas nomor WhatsApp kosong.",
    ],
    changed: [
      "Kesiapan Pilot di Admin ALETA Bot dibuat lebih jelas dengan timestamp, tombol Jalankan Smoke Test, dan Export Readiness.",
      "Blocker readiness diperketat agar status Siap tidak muncul saat ada blocker kritis seperti safe sending window nonaktif, kill switch aktif, legacy fallback baru, atau AI Public Q&A needs_sync.",
      "Run history reminder menampilkan ringkasan aman dari hasil run tanpa nomor penuh, isi pesan penuh, atau secret.",
    ],
    fixed: [
      "Operational smoke test kini membaca pilot readiness dan queue state tanpa melakukan enqueue atau pengiriman WhatsApp.",
      "Readiness CSV mencantumkan status safe sending window, AI Bridge, legacy fallback, dan smoke test availability.",
    ],
    security: [
      "Smoke test tetap baca-saja: tidak scan QR, tidak enqueue, dan tidak mengirim WhatsApp.",
      "Readiness report tidak mengekspor token, QR raw, session, password, API key, atau nomor WhatsApp penuh.",
      "Reminder production tetap terkunci oleh approval, Super Admin, idempotency, dan konfirmasi eksplisit.",
    ],
    operationalNotes: [
      "Gunakan Kesiapan Pilot dan Export Readiness sebelum memulai pilot harian.",
      "Jalankan Smoke Test dari Admin ALETA Bot untuk memeriksa koneksi dan guard tanpa aksi berisiko.",
      "Lengkapi nomor WhatsApp pegawai prioritas sebelum melepas pilot lebih luas.",
    ],
    knownLimitations: [
      "Scheduler production tetap belum dilepas otomatis.",
      "Smoke test tidak menggantikan uji pilot manual dengan skenario operasional nyata.",
      "Status Siap tetap bergantung pada data runtime terbaru dan kelengkapan nomor WhatsApp pegawai.",
    ],
  },
  {
    version: "0.1.0-beta.4",
    title: "Finalisasi Pilot Readiness, KPI Pimpinan, dan Smoke Test Operasional",
    date: "2026-05-01",
    status: "Beta",
    summary:
      "Rilis beta internal untuk menyelesaikan finishing pilot: KPI pimpinan, scheduler dry-run reminder H-1, run history, export readiness, smoke test operasional, dan logging saran AI yang lebih aman.",
    added: [
      "Dashboard KPI Pimpinan di halaman Statistik.",
      "Scheduler dry-run reminder deadline disposisi H-1 yang bisa diuji dari admin.",
      "Run history reminder deadline disposisi.",
      "Export CSV Pilot Readiness.",
      "Operational Smoke Test baca-saja tanpa scan QR, tanpa enqueue, dan tanpa kirim WhatsApp.",
      "Logging penggunaan saran AI klasifikasi dan ringkasan surat.",
    ],
    changed: [
      "Panel Reminder Deadline Disposisi menampilkan status scheduler, kill switch, dan riwayat run lebih jelas.",
      "Fallback saran AI kini membedakan AI disabled, perlu sinkronisasi, dan kondisi error/provider belum siap.",
      "Pilot readiness dapat diekspor untuk bahan koordinasi internal.",
    ],
    fixed: [
      "Insight run reminder tidak hanya terlihat pada preview sesaat, tetapi tersimpan sebagai run history.",
      "Smoke test operasional tidak memicu aksi berisiko pada WhatsApp Gateway.",
    ],
    security: [
      "Scheduler otomatis tetap dibatasi pada dry-run; production tetap membutuhkan Super Admin, approval, dan konfirmasi eksplisit.",
      "AI suggestion log tidak menyimpan prompt penuh, API key, token, atau data sensitif mentah.",
      "Export readiness tidak menyertakan secret, QR raw, session WhatsApp, atau nomor penuh.",
    ],
    operationalNotes: [
      "Jalankan Operational Smoke Test sebelum pilot harian.",
      "Gunakan Export Readiness untuk melaporkan blocker pilot kepada tim internal.",
      "Gunakan Run History Reminder untuk memastikan dry-run scheduler berjalan tanpa pengiriman real.",
    ],
    knownLimitations: [
      "Reminder production belum dilepas otomatis dan tetap harus diaktifkan melalui gate Super Admin.",
      "AI klasifikasi/ringkasan tetap berupa saran manual, bukan keputusan otomatis.",
      "Smoke test membaca status runtime, tetapi tidak menggantikan uji pilot operasional terjadwal.",
    ],
  },
  {
    version: "0.1.0-beta.3",
    title: "Pilot Control, SLA, Analytics, dan Saran AI Administrasi",
    date: "2026-05-01",
    status: "Beta",
    summary:
      "Rilis beta internal untuk memperkuat kontrol pilot reminder, laporan policy skip, SLA disposisi, analitik ALETA Bot/Public Q&A, dan saran AI manual untuk klasifikasi serta ringkasan surat.",
    added: [
      "Pilot whitelist untuk reminder deadline disposisi H-1.",
      "Scheduler reminder H-1 dengan default disabled/dry-run dan kill switch khusus reminder.",
      "Report dan export CSV Policy Skip.",
      "Filter pegawai tanpa nomor WhatsApp di Mapping User/Jabatan.",
      "Dashboard SLA Disposisi.",
      "Analitik Pengiriman ALETA Bot.",
      "Analitik Public Q&A.",
      "Endpoint saran AI klasifikasi surat dan ringkasan surat.",
    ],
    changed: [
      "Pilot readiness dibuat lebih actionable dengan tombol menuju area perbaikan.",
      "Reminder H-1 tetap aman: production membutuhkan approval, konfirmasi, idempotency, dan blocker clear.",
      "Admin ALETA Bot menampilkan kontrol whitelist, scheduler, dan emergency stop reminder.",
    ],
    fixed: [
      "Insight policy skip tidak hanya bergantung pada runtime memory.",
      "Link missingWhatsapp=true kini memfilter daftar akun yang belum memiliki nomor WhatsApp.",
      "SLA disposisi lebih mudah dipantau dari halaman statistik.",
    ],
    security: [
      "Reminder tetap default dry-run dan tidak aktif production tanpa Super Admin.",
      "Nomor WhatsApp tetap dimasking di area analitik dan preview.",
      "Saran AI tidak auto-apply dan tidak menyimpan perubahan tanpa konfirmasi manusia.",
      "Kill switch reminder hanya memengaruhi reminder deadline, bukan fitur lain.",
    ],
    operationalNotes: [
      "Gunakan mode dry-run untuk menguji reminder deadline sebelum pilot terbatas.",
      "Lengkapi nomor WhatsApp pegawai dari Mapping User/Jabatan agar fallback legacy bisa dikurangi.",
      "Pantau Policy Skip dan SLA Disposisi sebelum menyatakan pilot siap.",
    ],
    knownLimitations: [
      "Reminder production belum dijalankan otomatis pada validasi.",
      "AI klasifikasi/ringkasan masih berupa saran manual dan bukan keputusan final.",
      "Legacy mapping WhatsApp tetap ada sebagai fallback sampai data nomor pegawai lengkap.",
    ],
  },
  {
    version: "0.1.0-beta.2",
    title: "UX, Navigasi Aplikasi, Feedback, dan Penguatan ALETA Bot",
    date: "2026-05-01",
    status: "Beta",
    summary:
      "Rilis beta internal yang memperhalus navigasi aplikasi, memperkuat pengalaman ALETA Bot, menambahkan pusat masukan, dan merapikan dokumentasi/operator UX sebelum pilot terbatas.",
    added: [
      "Dashboard ALETA Bot untuk semua user.",
      "Riwayat Pengiriman Pesan ALETA Bot.",
      "Sidebar berbeda per aplikasi.",
      "Asisten Hakim di Grid Aplikasi.",
      "Pusat Masukan ALETA.",
      "Panduan Penggunaan ALETA.",
      "Jadwal/Cron dengan tampilan manusiawi.",
      "Koneksi Database tersedia di Mode Sederhana.",
      "Pengaturan password koneksi database dengan hidden/toggle mata.",
    ],
    changed: [
      "Footer dibuat lebih universal.",
      "Header /patch-notes, /panduan, dan /masukan disesuaikan konteks.",
      "Mode Sederhana/Lanjutan ALETA Bot diperhalus.",
      "Tab Notifikasi dan Kueri Terdaftar dibuat fit tanpa horizontal scroll.",
      "ALETA Bot umum dipisahkan dari Admin ALETA Bot.",
      "Istilah teknis disederhanakan.",
    ],
    fixed: [
      "Double footer pada tab Status WhatsApp Gateway.",
      "Konsistensi pairing WhatsApp Gateway dan ALETA Bot.",
      "Konsistensi session name WhatsApp.",
      "Judul Patch Notes/Panduan tidak lagi Manajemen Surat.",
      "Horizontal scroll pada Notifikasi dan Kueri Terdaftar.",
      "Fallback AI key .env diperjelas.",
    ],
    security: [
      "Role-aware masking untuk riwayat pesan.",
      "Admin settings tetap dibatasi.",
      "Asisten Hakim dibatasi role.",
      "Pusat Masukan role-aware.",
      "Manajemen akun diperkuat.",
      "Password koneksi database tidak diekspos.",
      "Session WhatsApp/token/API key tidak diekspos.",
    ],
    operationalNotes: [
      "Gunakan Pusat Masukan untuk melaporkan bug, saran fitur, atau usulan aplikasi baru dari footer aplikasi.",
      "Gunakan Mode Sederhana untuk pekerjaan harian operator dan Mode Lanjutan untuk konfigurasi teknis.",
      "Pastikan perubahan koneksi database diuji dari modal sebelum dipakai untuk query atau notifikasi.",
      "Gunakan Patch Notes dan Panduan Penggunaan sebagai rujukan internal saat pilot.",
    ],
    knownLimitations: [
      "Masih internal pilot.",
      "Notifikasi pihak tetap perlu dry-run sebelum aktif massal.",
      "Legacy app.js/notifikasi.js/query.js masih fallback bertahap.",
      "Archive legacy penuh belum selesai.",
      "Asisten Hakim memakai layanan AI eksternal.",
    ],
  },
  {
    version: "0.1.0-beta.1",
    title: "Internal Pilot Build",
    date: "2026-04-30",
    status: "Beta",
    summary:
      "Rilis awal internal ALETA yang menggabungkan portal Manajemen Surat, ALETA Bot, WhatsApp Gateway tunggal, AI Config Bridge, antrean pesan, Public Q&A, migrasi legacy bertahap, dan perapian UX untuk operator.",
    added: [
      "Portal utama manajemen_surat sebagai pusat aplikasi internal ALETA.",
      "Modul ALETA Bot Admin Panel.",
      "Single WhatsApp Gateway dengan aleta_bot sebagai runtime utama WhatsApp dan manajemen_surat sebagai control panel.",
      "Connect WhatsApp Gateway dari portal dengan QR WhatsApp dari runtime aleta_bot.",
      "Queue/antrean pesan, worker pemroses antrean, dead-letter, dan resend pesan gagal dengan konfirmasi.",
      "AI Config Bridge agar provider, model, dan API key dikontrol dari menu AI portal, sementara aleta_bot menjadi runtime executor.",
      "Public Q&A / Pertanyaan dan Jawaban Publik dengan safety guard AI untuk mencegah jawaban bebas atau berisiko.",
      "Legacy Migration Tracker, Duplicate Path Guard, Rollback State Machine, dan Archive Readiness.",
      "Release Readiness, smoke test tanpa pengiriman WhatsApp sungguhan, export config non-secret, dan runbook operasional.",
      "Mode Sederhana / Mode Lanjutan untuk membedakan tampilan operator dan admin teknis.",
      "Jadwal/Cron dengan tampilan manusiawi: jam, tanggal, hari, bulan, dan opsi Setiap.",
    ],
    changed: [
      "Portal tidak lagi membuat WhatsApp client produksi sendiri dalam mode aleta_bot.",
      "Tombol Connect WhatsApp sekarang memanggil runtime connect di aleta_bot dan UI melakukan polling status/QR setelah Connect.",
      "Status teknis diterjemahkan ke bahasa operasional dan fitur teknis disembunyikan di Mode Sederhana.",
      "Notifikasi Pegawai/Pihak dikelompokkan dalam satu menu Notifikasi tanpa menggabungkan tabel internalnya.",
      "Migration row tidak lagi menampilkan semua tombol dengan bobot setara.",
      "Log aktivitas diberi filter awal dan dibatasi agar tidak terlalu padat.",
      "API key AI di aleta_bot tidak lagi menjadi syarat utama production.",
      "OPENAI_API_KEY, GEMINI_API_KEY, dan ANTHROPIC_API_KEY hanya fallback development.",
      "Password SQL connection tidak ditampilkan kembali saat edit.",
      "Cron mentah tidak menjadi tampilan utama user/admin.",
    ],
    fixed: [
      "QR WhatsApp tidak muncul saat Connect.",
      "Portal /api/whatsapp/init sekarang benar-benar memanggil connect runtime di aleta_bot.",
      "Token guard internal endpoint: tanpa token 401, token salah 403.",
      "Queue response dimasking agar tidak membocorkan nomor penuh atau pesan mentah.",
      "AI disabled fallback tidak throw error.",
      "RBAC visibility untuk portal apps sudah diperbaiki.",
      "Lint/test lama dibersihkan.",
      "Rollback modal menampilkan transisi lebih jelas.",
      "Purge logs memakai konfirmasi teks.",
      "Dead-letter resend menampilkan nomor masked dan preview pesan.",
    ],
    security: [
      "Internal API dilindungi token.",
      "Admin route sensitif membutuhkan login.",
      "High-risk action tetap memakai modal/konfirmasi.",
      "API key AI tidak ditampilkan di UI, API response, atau log.",
      "DB password tidak ditampilkan ulang di edit modal.",
      "Export config tidak membawa API key, DB password, internal token, WhatsApp session, atau QR raw.",
      "Nomor penerima dimasking di UI sensitif.",
      "Query SQL tetap divalidasi read-only.",
      "Public Q&A tetap dibatasi oleh intent, template, dan query resmi.",
    ],
    operationalNotes: [
      "Untuk menggunakan WhatsApp: jalankan aleta_bot, jalankan manajemen_surat, login sebagai Super Admin, buka ALETA Bot, klik Connect WhatsApp Gateway, tunggu QR muncul, lalu scan QR dengan WhatsApp kantor.",
      "Jika AI Bridge berstatus needs_sync, klik Sync AI ke ALETA Bot.",
      "Setelah restart aleta_bot, AI secret runtime bisa perlu sync ulang.",
      "Notifikasi pihak sebaiknya tetap dry-run sampai pilot selesai.",
      "Gunakan Mode Lanjutan hanya untuk konfigurasi teknis.",
      "Jalankan smoke test sebelum pilot.",
    ],
    knownLimitations: [
      "WhatsApp harus discan manual oleh admin.",
      "Status disconnected masih normal sebelum WhatsApp dihubungkan.",
      "AI Bridge bisa needs_sync setelah restart.",
      "Notifikasi pihak belum disarankan aktif massal.",
      "Legacy app.js, notifikasi.js, dan query.js masih ada sebagai fallback bertahap.",
      "Archive legacy penuh belum dilakukan.",
      "Visual operator pilot masih perlu diuji langsung di kantor.",
    ],
  },
];
