import { type KnowledgeBaseEntry } from "@/lib/types";

export const regulationsKnowledgeBase: KnowledgeBaseEntry[] = [
  {
    id: "reg-int-001",
    title: "SOP Disposisi Surat Masuk Pimpinan",
    source: "internal",
    jurisdiction: "Pengadilan Agama",
    moduleIds: ["manajemen-surat", "dashboard"],
    keywords: ["disposisi", "surat masuk", "pimpinan", "ketua", "wakil", "instruksi"],
    summary: "Mengatur jalur telaah surat masuk dari pimpinan ke pejabat terkait berikut standar instruksi singkat dan monitoring tindak lanjut.",
    citation: "SOP Internal Persuratan Bab II",
    recommendedPositionIds: ["pos-ketua", "pos-wakil", "pos-sekretaris", "pos-panitera", "pos-kasubag-umum"],
  },
  {
    id: "reg-int-002",
    title: "Pedoman Audit Keamanan Aplikasi Internal",
    source: "internal",
    jurisdiction: "Pengadilan Agama",
    moduleIds: ["manajemen-surat", "dashboard", "sop"],
    keywords: ["audit", "keamanan", "aplikasi", "backup", "enkripsi", "ti"],
    summary: "Menetapkan PIC audit keamanan, jadwal verifikasi, dan kewajiban bukti kontrol TI untuk aplikasi internal.",
    citation: "Pedoman Audit TI Pasal 4-8",
    recommendedPositionIds: ["pos-ketua", "pos-pranata-komputer", "pos-kasubag-umum"],
  },
  {
    id: "reg-int-003",
    title: "SOP Inventarisasi Sarpras dan Umum",
    source: "internal",
    jurisdiction: "Pengadilan Agama",
    moduleIds: ["manajemen-surat", "dashboard", "sop"],
    keywords: ["sarpras", "inventarisasi", "umum", "verifikasi", "lapangan", "kesekretariatan"],
    summary: "Memuat pembagian tugas inventarisasi sarana prasarana antara Kasubag Umum dan Staf Umum beserta eskalasi ke pimpinan.",
    citation: "SOP Umum dan Keuangan Lampiran A",
    recommendedPositionIds: ["pos-kasubag-umum", "pos-staf-umum", "pos-sekretaris"],
  },
  {
    id: "reg-int-004",
    title: "Pedoman Rekap Laporan Perkara Triwulanan",
    source: "internal",
    jurisdiction: "Badan Peradilan Agama",
    moduleIds: ["manajemen-surat", "sop"],
    keywords: ["laporan", "perkara", "triwulan", "sla", "kepaniteraan", "rekap"],
    summary: "Mengatur penyusunan rekap SLA, perkara prioritas, dan alur validasi data pada unit kepaniteraan.",
    citation: "Pedoman Pelaporan Kinerja Triwulan Bab III",
    recommendedPositionIds: ["pos-panitera", "pos-panitera-muda-hukum"],
  },
  {
    id: "reg-ext-001",
    title: "Undang-Undang Keterbukaan Informasi Publik",
    source: "external",
    jurisdiction: "Nasional",
    moduleIds: ["manajemen-surat", "sop"],
    keywords: ["informasi", "publik", "rahasia", "klasifikasi", "akses"],
    summary: "Menjadi dasar penetapan klasifikasi keterbukaan dan pembatasan akses dokumen yang memuat informasi dikecualikan.",
    citation: "UU No. 14 Tahun 2008",
    recommendedPositionIds: ["pos-sekretaris", "pos-ketua"],
  },
  {
    id: "reg-ext-002",
    title: "Pedoman Naskah Dinas dan Arsip Elektronik",
    source: "external",
    jurisdiction: "Mahkamah Agung RI",
    moduleIds: ["manajemen-surat", "sop", "dashboard"],
    keywords: ["naskah dinas", "arsip", "elektronik", "watermark", "dokumen"],
    summary: "Mengatur pencatatan naskah dinas, keamanan arsip elektronik, dan validitas dokumen digital internal.",
    citation: "Pedoman Naskah Dinas MA RI",
    recommendedPositionIds: ["pos-sekretaris", "pos-arsiparis", "pos-pranata-komputer"],
  },
  {
    id: "reg-int-005",
    title: "SOP Penyusunan dan Pemutakhiran SOP",
    source: "internal",
    jurisdiction: "Pengadilan Agama",
    moduleIds: ["sop"],
    keywords: ["sop", "prosedur", "pemutakhiran", "standar operasional", "review"],
    summary: "Menjadi acuan penyusunan SOP baru, penelusuran dasar hukum, dan siklus review berkala lintas unit.",
    citation: "SOP Tata Kelola Dokumen Internal",
    recommendedPositionIds: ["pos-sekretaris", "pos-kasubag-umum"],
  },
];
