type BasQaSeedItem = {
  id: string;
  order: number;
  question: string;
  answer: string;
};

type BasQaSeedTemplate = {
  id: string;
  code: string;
  name: string;
  caseType: string;
  paperSize: string;
  isActive: boolean;
  updatedAt: string;
  items: BasQaSeedItem[];
};

type ScenarioSeed = {
  slug: string;
  title: string;
  scenario: string;
  factFocus: string;
  evidenceFocus: string;
  legalFocus: string;
};

type ScenarioGroup = {
  prefix: string;
  caseType: string;
  subject: string;
  scenarios: ScenarioSeed[];
};

const UPDATED_AT = "2026-05-25T00:00:00.000Z";

const scenarioGroups: ScenarioGroup[] = [
  {
    prefix: "cg",
    caseType: "Cerai Gugat",
    subject: "Cerai Gugat",
    scenarios: [
      {
        slug: "kdrt",
        title: "Kekerasan Fisik/Psikis",
        scenario: "dalil kekerasan fisik atau psikis dalam rumah tangga",
        factFocus: "peristiwa kekerasan, waktu kejadian, tempat kejadian, dan akibat yang dialami pihak istri",
        evidenceFocus: "visum, foto, pesan, laporan, atau keterangan keluarga/tetangga",
        legalFocus: "apakah kekerasan tersebut membuat tujuan perkawinan tidak dapat dicapai",
      },
      {
        slug: "penelantaran",
        title: "Penelantaran dan Tidak Ada Nafkah",
        scenario: "dalil penelantaran lahir batin dan tidak dipenuhinya nafkah",
        factFocus: "sejak kapan suami meninggalkan kewajiban nafkah dan komunikasi keluarga",
        evidenceFocus: "bukti kebutuhan rumah tangga, transfer, saksi lingkungan, atau catatan keluarga",
        legalFocus: "apakah penelantaran berlangsung terus-menerus dan sulit diperbaiki",
      },
      {
        slug: "perselingkuhan",
        title: "Perselingkuhan atau Pihak Ketiga",
        scenario: "dalil hubungan dengan pihak ketiga yang memicu perselisihan",
        factFocus: "peristiwa yang menunjukkan hubungan pihak ketiga dan pengaruhnya pada rumah tangga",
        evidenceFocus: "pesan, foto, pengakuan, atau keterangan saksi yang melihat langsung",
        legalFocus: "apakah hubungan tersebut menimbulkan syiqaq dan hilangnya kepercayaan",
      },
      {
        slug: "pisah-rumah",
        title: "Pisah Rumah Lama",
        scenario: "pisah tempat tinggal dalam waktu lama tanpa pemulihan rumah tangga",
        factFocus: "tanggal mulai pisah rumah, penyebab, dan keadaan anak/keluarga setelah pisah",
        evidenceFocus: "alamat tempat tinggal, keterangan keluarga, dan riwayat komunikasi",
        legalFocus: "apakah pisah rumah menunjukkan rumah tangga pecah secara nyata",
      },
      {
        slug: "ekonomi",
        title: "Konflik Ekonomi Keluarga",
        scenario: "perselisihan karena pengelolaan ekonomi, hutang, atau kebutuhan keluarga",
        factFocus: "pola penghasilan, pengeluaran, hutang, dan tanggung jawab ekonomi para pihak",
        evidenceFocus: "catatan hutang, rekening, transaksi, atau keterangan pihak yang mengetahui",
        legalFocus: "apakah konflik ekonomi sudah menjadi perselisihan terus-menerus",
      },
    ],
  },
  {
    prefix: "ct",
    caseType: "Cerai Talak",
    subject: "Cerai Talak",
    scenarios: [
      {
        slug: "talak-perselisihan",
        title: "Perselisihan Terus-Menerus",
        scenario: "permohonan talak karena perselisihan terus-menerus",
        factFocus: "sebab perselisihan, frekuensi pertengkaran, dan riwayat pisah rumah",
        evidenceFocus: "keterangan keluarga, tetangga, atau riwayat mediasi",
        legalFocus: "apakah rumah tangga tidak mungkin dirukunkan kembali",
      },
      {
        slug: "nusyuz",
        title: "Dalil Nusyuz",
        scenario: "dalil nusyuz atau tidak terpenuhinya kewajiban rumah tangga",
        factFocus: "perilaku yang dianggap tidak memenuhi kewajiban dan dampaknya terhadap keluarga",
        evidenceFocus: "keterangan saksi keluarga, komunikasi, atau upaya nasihat",
        legalFocus: "apakah dalil tersebut terbukti dan relevan dengan permohonan talak",
      },
      {
        slug: "istri-pergi",
        title: "Istri Meninggalkan Rumah",
        scenario: "Termohon meninggalkan rumah bersama tanpa kesepakatan",
        factFocus: "kapan Termohon pergi, alasan pergi, dan upaya Pemohon menjemput atau menghubungi",
        evidenceFocus: "alamat Termohon, komunikasi, dan saksi yang mengetahui perpindahan",
        legalFocus: "apakah kondisi tersebut menyebabkan perkawinan tidak harmonis",
      },
      {
        slug: "nafkah-akibat-talak",
        title: "Kemampuan Nafkah Akibat Talak",
        scenario: "pemeriksaan kemampuan Pemohon untuk nafkah akibat talak",
        factFocus: "pekerjaan, penghasilan, tanggungan, dan kebutuhan Termohon/anak",
        evidenceFocus: "slip gaji, usaha, rekening, saksi pekerjaan, atau bukti biaya anak",
        legalFocus: "kewajaran nafkah iddah, mutah, madhiyah, dan nafkah anak",
      },
      {
        slug: "ikrar-talak",
        title: "Kelayakan Ikrar Talak",
        scenario: "kesiapan dan kelayakan ikrar talak setelah putusan berkekuatan hukum",
        factFocus: "kehadiran pihak, pemenuhan kewajiban, dan tidak adanya paksaan",
        evidenceFocus: "putusan, bukti pembayaran kewajiban, dan relas panggilan",
        legalFocus: "apakah ikrar dapat dilaksanakan sesuai amar dan prosedur",
      },
    ],
  },
  {
    prefix: "relas",
    caseType: "Ghaib, Verstek, dan Relas",
    subject: "Pemanggilan dan Kehadiran",
    scenarios: [
      {
        slug: "alamat-tidak-dikenal",
        title: "Alamat Tidak Dikenal",
        scenario: "pihak tidak diketahui alamatnya secara pasti",
        factFocus: "alamat terakhir, kapan pergi, dan pihak yang pernah mencari",
        evidenceFocus: "surat keterangan desa, keterangan keluarga, atau relas panggilan",
        legalFocus: "apakah panggilan ghaib atau cara pemanggilan lain sudah layak",
      },
      {
        slug: "tidak-hadir",
        title: "Tidak Hadir Meski Dipanggil",
        scenario: "pihak tidak hadir setelah dipanggil secara patut",
        factFocus: "tanggal panggilan, penerima relas, dan alasan ketidakhadiran jika diketahui",
        evidenceFocus: "relaas panggilan, bukti penerimaan, atau keterangan jurusita",
        legalFocus: "apakah pemeriksaan dapat dilanjutkan tanpa kehadiran pihak",
      },
      {
        slug: "luar-negeri",
        title: "Pihak di Luar Negeri",
        scenario: "pihak berada atau diduga berada di luar negeri",
        factFocus: "negara/tempat kerja, kontak terakhir, dan informasi keluarga",
        evidenceFocus: "paspor, kontrak kerja, komunikasi, atau keterangan keluarga",
        legalFocus: "apakah pemanggilan dan tenggang waktu sudah proporsional",
      },
      {
        slug: "ecourt",
        title: "Panggilan Elektronik",
        scenario: "pemanggilan atau pemberitahuan melalui e-Court",
        factFocus: "akun elektronik, domisili elektronik, dan penerimaan notifikasi",
        evidenceFocus: "riwayat e-Court, email, sistem informasi, atau tangkapan layar",
        legalFocus: "apakah pemberitahuan elektronik cukup untuk melanjutkan proses",
      },
      {
        slug: "delegasi",
        title: "Panggilan Delegasi",
        scenario: "pemanggilan melalui bantuan pengadilan lain",
        factFocus: "wilayah pihak, alamat delegasi, dan pelaksanaan panggilan",
        evidenceFocus: "surat delegasi, relas dari pengadilan tujuan, atau bukti pengiriman",
        legalFocus: "apakah panggilan delegasi sah dan patut",
      },
    ],
  },
  {
    prefix: "nafkah",
    caseType: "Nafkah",
    subject: "Nafkah",
    scenarios: [
      {
        slug: "madhiyah",
        title: "Nafkah Madhiyah",
        scenario: "tuntutan nafkah lampau yang tidak dibayarkan",
        factFocus: "periode tidak diberi nafkah, jumlah kebutuhan, dan kemampuan pihak yang wajib",
        evidenceFocus: "bukti transfer, catatan belanja, saksi keluarga, atau pengakuan",
        legalFocus: "kewajaran jumlah nafkah lampau berdasarkan kebutuhan dan kemampuan",
      },
      {
        slug: "iddah",
        title: "Nafkah Iddah",
        scenario: "nafkah iddah setelah perceraian",
        factFocus: "lama masa iddah, kebutuhan hidup, dan kemampuan ekonomi suami",
        evidenceFocus: "bukti penghasilan, kebutuhan bulanan, dan tanggungan keluarga",
        legalFocus: "kelayakan nafkah iddah sesuai keadaan para pihak",
      },
      {
        slug: "mutah",
        title: "Mutah",
        scenario: "pemberian mutah yang layak setelah talak",
        factFocus: "lama perkawinan, keadaan ekonomi, dan dampak perceraian",
        evidenceFocus: "pekerjaan, penghasilan, aset, dan kebutuhan pihak istri",
        legalFocus: "kelayakan mutah secara patut dan manusiawi",
      },
      {
        slug: "anak",
        title: "Nafkah Anak",
        scenario: "nafkah anak setelah perceraian atau sengketa pemeliharaan",
        factFocus: "umur anak, sekolah, kesehatan, kebutuhan harian, dan pihak yang mengasuh",
        evidenceFocus: "biaya sekolah, kesehatan, kebutuhan bulanan, atau saksi pengasuh",
        legalFocus: "kepentingan terbaik anak dan kemampuan orang tua",
      },
      {
        slug: "hadhanah-biaya",
        title: "Biaya Pengasuhan",
        scenario: "biaya pengasuhan anak dalam perkara hadhanah",
        factFocus: "biaya makan, pendidikan, kesehatan, tempat tinggal, dan kegiatan anak",
        evidenceFocus: "kuitansi, daftar biaya, laporan sekolah, atau catatan kesehatan",
        legalFocus: "apakah biaya yang diminta wajar dan diperlukan",
      },
    ],
  },
  {
    prefix: "hadhanah",
    caseType: "Hadhanah",
    subject: "Pengasuhan Anak",
    scenarios: [
      {
        slug: "anak-belum-mumayyiz",
        title: "Anak Belum Mumayyiz",
        scenario: "anak belum mumayyiz dan membutuhkan pengasuhan harian",
        factFocus: "umur anak, kebutuhan harian, dan pihak yang paling dekat dengan anak",
        evidenceFocus: "keterangan pengasuh, keluarga, sekolah, atau tenaga kesehatan",
        legalFocus: "kepentingan terbaik anak dan stabilitas pengasuhan",
      },
      {
        slug: "anak-mumayyiz",
        title: "Anak Mumayyiz",
        scenario: "anak sudah mumayyiz dan memiliki kehendak tinggal dengan salah satu pihak",
        factFocus: "kedekatan anak, alasan pilihan anak, dan kondisi psikologisnya",
        evidenceFocus: "keterangan anak, guru, keluarga, atau konselor jika ada",
        legalFocus: "apakah pilihan anak selaras dengan perlindungan dan kemaslahatan",
      },
      {
        slug: "akses-bertemu",
        title: "Hak Akses Bertemu",
        scenario: "perselisihan hak bertemu anak",
        factFocus: "riwayat kunjungan, hambatan komunikasi, dan dampaknya bagi anak",
        evidenceFocus: "pesan, jadwal kunjungan, atau saksi keluarga",
        legalFocus: "hak anak untuk mendapat kasih sayang kedua orang tua",
      },
      {
        slug: "relokasi-anak",
        title: "Relokasi Anak",
        scenario: "rencana memindahkan anak ke luar daerah",
        factFocus: "alasan relokasi, sekolah, lingkungan baru, dan akses orang tua lain",
        evidenceFocus: "surat sekolah, alamat baru, pekerjaan, atau rencana pengasuhan",
        legalFocus: "apakah relokasi tidak merugikan kepentingan anak",
      },
      {
        slug: "risiko-pengasuhan",
        title: "Risiko Pengasuhan",
        scenario: "dugaan lingkungan pengasuhan tidak aman",
        factFocus: "risiko kekerasan, penelantaran, narkoba, judi, atau lingkungan buruk",
        evidenceFocus: "laporan, saksi lingkungan, catatan sekolah, atau catatan kesehatan",
        legalFocus: "perlindungan anak dari bahaya fisik, psikis, dan moral",
      },
    ],
  },
  {
    prefix: "hb",
    caseType: "Harta Bersama",
    subject: "Harta Bersama",
    scenarios: [
      {
        slug: "tanah-rumah",
        title: "Tanah dan Rumah",
        scenario: "sengketa tanah dan rumah yang diperoleh selama perkawinan",
        factFocus: "waktu perolehan, sumber dana, status sertifikat, dan penguasaan objek",
        evidenceFocus: "sertifikat, AJB, kuitansi, PBB, saksi transaksi, atau foto objek",
        legalFocus: "apakah objek termasuk harta bersama atau harta pribadi",
      },
      {
        slug: "kendaraan",
        title: "Kendaraan",
        scenario: "sengketa kendaraan bermotor sebagai harta bersama",
        factFocus: "waktu pembelian, sumber pembayaran, BPKB/STNK, dan pengguna kendaraan",
        evidenceFocus: "BPKB, STNK, kuitansi, transfer cicilan, atau saksi pembelian",
        legalFocus: "status kepemilikan dan nilai kendaraan yang patut dibagi",
      },
      {
        slug: "usaha",
        title: "Usaha dan Aset Produktif",
        scenario: "sengketa usaha, toko, kebun, atau aset produktif",
        factFocus: "siapa yang mengelola, sumber modal, laba, hutang, dan perkembangan usaha",
        evidenceFocus: "pembukuan, izin usaha, rekening, stok, atau saksi pekerja",
        legalFocus: "kontribusi para pihak dan nilai ekonomi yang dapat dibagi",
      },
      {
        slug: "hutang",
        title: "Hutang Bersama",
        scenario: "hutang yang diklaim sebagai beban bersama",
        factFocus: "tujuan hutang, waktu hutang, siapa yang menikmati, dan sisa kewajiban",
        evidenceFocus: "perjanjian kredit, kuitansi, rekening, atau saksi pemberi pinjaman",
        legalFocus: "apakah hutang menjadi kewajiban bersama atau pribadi",
      },
      {
        slug: "pengalihan",
        title: "Pengalihan Harta",
        scenario: "dugaan penjualan atau pengalihan harta tanpa persetujuan",
        factFocus: "waktu pengalihan, pihak penerima, harga, dan penggunaan hasil penjualan",
        evidenceFocus: "akta jual beli, kuitansi, saksi transaksi, atau riwayat rekening",
        legalFocus: "akibat hukum pengalihan terhadap hak pihak lain",
      },
    ],
  },
  {
    prefix: "itsbat",
    caseType: "Itsbat Nikah",
    subject: "Itsbat Nikah",
    scenarios: [
      {
        slug: "nikah-sirri",
        title: "Nikah Tidak Tercatat",
        scenario: "pernikahan sah menurut agama tetapi belum tercatat",
        factFocus: "waktu akad, tempat akad, wali, saksi, mahar, dan ijab kabul",
        evidenceFocus: "saksi akad, surat keterangan, foto, atau keterangan keluarga",
        legalFocus: "terpenuhinya rukun dan syarat perkawinan",
      },
      {
        slug: "buku-nikah-hilang",
        title: "Buku Nikah Hilang",
        scenario: "buku nikah hilang atau tidak ditemukan",
        factFocus: "riwayat pencatatan, KUA tempat menikah, dan sebab dokumen hilang",
        evidenceFocus: "arsip KUA, surat kehilangan, kartu keluarga, atau akta kelahiran anak",
        legalFocus: "kepastian status perkawinan dan kebutuhan administrasi",
      },
      {
        slug: "poligami-sirri",
        title: "Nikah Poligami Tidak Tercatat",
        scenario: "perkawinan poligami yang belum tercatat",
        factFocus: "status perkawinan sebelumnya, izin, wali, saksi, dan keadaan para pihak",
        evidenceFocus: "keterangan istri pertama, keluarga, KUA, atau dokumen pendukung",
        legalFocus: "tidak adanya halangan hukum dan perlindungan pihak terkait",
      },
      {
        slug: "anak-administrasi",
        title: "Keperluan Akta Anak",
        scenario: "itsbat diajukan untuk kepentingan akta kelahiran anak",
        factFocus: "kelahiran anak, pengakuan orang tua, dan kehidupan sebagai keluarga",
        evidenceFocus: "surat lahir, kartu keluarga, sekolah, atau keterangan bidan",
        legalFocus: "perlindungan status hukum anak",
      },
      {
        slug: "nikah-lama",
        title: "Pernikahan Lama",
        scenario: "perkawinan lama yang tidak tercatat karena kondisi administratif masa lalu",
        factFocus: "waktu lama perkawinan, sebab tidak tercatat, dan pengakuan masyarakat",
        evidenceFocus: "saksi keluarga/tokoh masyarakat, anak, kartu keluarga, atau dokumen desa",
        legalFocus: "rekonstruksi fakta perkawinan secara hati-hati",
      },
    ],
  },
  {
    prefix: "dk",
    caseType: "Dispensasi Kawin",
    subject: "Dispensasi Kawin",
    scenarios: [
      {
        slug: "hamil",
        title: "Kehamilan Anak",
        scenario: "permohonan karena anak telah hamil",
        factFocus: "usia anak, kondisi kehamilan, calon pasangan, dan tanggung jawab keluarga",
        evidenceFocus: "surat dokter/bidan, kartu identitas, dan keterangan orang tua",
        legalFocus: "perlindungan anak, kesehatan, dan alasan mendesak",
      },
      {
        slug: "hubungan-dekat",
        title: "Hubungan Dekat Berisiko",
        scenario: "hubungan anak dan calon pasangan sudah sangat dekat",
        factFocus: "lama hubungan, pengawasan orang tua, dan risiko sosial/psikologis",
        evidenceFocus: "keterangan orang tua, lingkungan, atau tokoh masyarakat",
        legalFocus: "apakah perkawinan benar menjadi pilihan paling melindungi anak",
      },
      {
        slug: "kesiapan-ekonomi",
        title: "Kesiapan Ekonomi Calon Suami",
        scenario: "pemeriksaan kemampuan ekonomi calon suami",
        factFocus: "pekerjaan, penghasilan, tempat tinggal, dan tanggungan calon suami",
        evidenceFocus: "surat kerja, penghasilan, usaha, atau saksi pekerjaan",
        legalFocus: "kemampuan menafkahi tanpa mengorbankan pendidikan dan kesehatan anak",
      },
      {
        slug: "pendidikan",
        title: "Keberlanjutan Pendidikan",
        scenario: "risiko putus sekolah setelah perkawinan anak",
        factFocus: "status sekolah, rencana pendidikan, dan dukungan keluarga",
        evidenceFocus: "surat sekolah, rapor, atau keterangan wali kelas",
        legalFocus: "hak pendidikan anak tetap terlindungi",
      },
      {
        slug: "pencegahan-eksploitasi",
        title: "Pencegahan Eksploitasi",
        scenario: "pemeriksaan apakah ada paksaan, tekanan, atau eksploitasi",
        factFocus: "kehendak anak, tekanan keluarga, perbedaan usia, dan alasan menikah",
        evidenceFocus: "keterangan anak, orang tua, calon pasangan, atau pendamping",
        legalFocus: "perkawinan tidak boleh menjadi hasil paksaan atau eksploitasi",
      },
    ],
  },
  {
    prefix: "wa",
    caseType: "Wali Adhal",
    subject: "Wali Adhal",
    scenarios: [
      {
        slug: "wali-menolak-tanpa-alasan",
        title: "Wali Menolak Tanpa Alasan Syar'i",
        scenario: "wali menolak menikahkan tanpa alasan yang jelas secara hukum",
        factFocus: "permintaan nikah kepada wali, alasan penolakan, dan sikap wali",
        evidenceFocus: "saksi keluarga, komunikasi, atau keterangan tokoh masyarakat",
        legalFocus: "apakah wali dapat dinyatakan adhal",
      },
      {
        slug: "calon-suami-diragukan",
        title: "Kelayakan Calon Suami Dipersoalkan",
        scenario: "wali menolak karena meragukan calon suami",
        factFocus: "agama, akhlak, pekerjaan, status perkawinan, dan tanggung jawab calon suami",
        evidenceFocus: "KTP, status nikah, surat kerja, atau saksi lingkungan",
        legalFocus: "apakah alasan wali objektif dan berdasar",
      },
      {
        slug: "wali-tidak-hadir",
        title: "Wali Tidak Dapat Dihubungi",
        scenario: "wali tidak hadir atau sulit dihubungi",
        factFocus: "alamat wali, upaya menghubungi, dan alasan tidak hadir",
        evidenceFocus: "surat panggilan, pesan, keterangan keluarga, atau surat desa",
        legalFocus: "kelayakan pemeriksaan tanpa kehadiran wali",
      },
      {
        slug: "wali-minta-syarat",
        title: "Wali Mengajukan Syarat Berlebihan",
        scenario: "wali mensyaratkan hal yang memberatkan atau tidak relevan",
        factFocus: "syarat yang diminta, kemampuan para pihak, dan dampaknya",
        evidenceFocus: "pesan, saksi musyawarah, atau keterangan keluarga",
        legalFocus: "apakah syarat wali menghalangi hak menikah secara tidak patut",
      },
      {
        slug: "nasab-wali",
        title: "Urutan dan Kewenangan Wali",
        scenario: "perselisihan tentang siapa wali nasab yang berwenang",
        factFocus: "silsilah keluarga, urutan wali, dan keberadaan wali lebih dekat",
        evidenceFocus: "akta kelahiran, kartu keluarga, surat kematian, atau saksi keluarga",
        legalFocus: "penentuan wali yang sah menurut hukum Islam",
      },
    ],
  },
  {
    prefix: "aua",
    caseType: "Asal Usul Anak",
    subject: "Asal Usul Anak",
    scenarios: [
      {
        slug: "anak-dalam-perkawinan",
        title: "Anak Dalam Perkawinan",
        scenario: "penetapan anak lahir dari perkawinan para pihak",
        factFocus: "tanggal nikah, tanggal lahir, dan kehidupan keluarga",
        evidenceFocus: "surat lahir, buku nikah, kartu keluarga, atau saksi keluarga",
        legalFocus: "hubungan nasab dan status hukum anak",
      },
      {
        slug: "anak-sebelum-akta",
        title: "Anak Belum Memiliki Akta",
        scenario: "anak belum memiliki akta kelahiran karena kendala administrasi",
        factFocus: "identitas orang tua, tempat lahir, dan alasan akta belum dibuat",
        evidenceFocus: "surat lahir, keterangan bidan, sekolah, atau kartu keluarga",
        legalFocus: "kepastian identitas dan perlindungan administrasi anak",
      },
      {
        slug: "pengakuan-ayah",
        title: "Pengakuan Ayah",
        scenario: "ayah mengakui anak dan meminta penetapan hukum",
        factFocus: "hubungan orang tua, pengakuan ayah, pengasuhan, dan nafkah",
        evidenceFocus: "surat pernyataan, saksi keluarga, atau dokumen keluarga",
        legalFocus: "apakah pengakuan selaras dengan ketentuan nasab",
      },
      {
        slug: "perbedaan-data",
        title: "Perbedaan Data Anak",
        scenario: "perbedaan data orang tua atau tanggal lahir pada dokumen",
        factFocus: "dokumen yang berbeda, sebab perbedaan, dan data yang benar",
        evidenceFocus: "akta, KK, KTP, ijazah, surat lahir, atau keterangan pejabat",
        legalFocus: "penegasan data hukum anak secara konsisten",
      },
      {
        slug: "anak-hasil-itsbat",
        title: "Anak Terkait Itsbat Nikah",
        scenario: "status anak bergantung pada penetapan perkawinan orang tua",
        factFocus: "akad nikah orang tua, kelahiran anak, dan pengakuan keluarga",
        evidenceFocus: "saksi akad, surat lahir, kartu keluarga, atau keterangan masyarakat",
        legalFocus: "hubungan antara sahnya perkawinan dan status anak",
      },
    ],
  },
  {
    prefix: "batal-nikah",
    caseType: "Pembatalan dan Pencegahan Nikah",
    subject: "Pembatalan Nikah",
    scenarios: [
      {
        slug: "pemalsuan-identitas",
        title: "Pemalsuan Identitas",
        scenario: "dugaan pemalsuan identitas atau status perkawinan",
        factFocus: "identitas yang dipakai saat nikah dan data yang sebenarnya",
        evidenceFocus: "KTP, KK, akta cerai, buku nikah, atau saksi keluarga",
        legalFocus: "apakah cacat identitas mempengaruhi keabsahan perkawinan",
      },
      {
        slug: "halangan-nasab",
        title: "Halangan Nasab/Semenda/Sesusuan",
        scenario: "dugaan hubungan yang menjadi halangan perkawinan",
        factFocus: "silsilah keluarga, hubungan susuan, atau hubungan semenda",
        evidenceFocus: "akta kelahiran, keterangan keluarga, atau saksi yang mengetahui",
        legalFocus: "apakah ada larangan perkawinan menurut hukum",
      },
      {
        slug: "perkawinan-ganda",
        title: "Perkawinan Ganda",
        scenario: "salah satu pihak masih terikat perkawinan lain",
        factFocus: "status perkawinan sebelumnya dan izin yang ada atau tidak ada",
        evidenceFocus: "buku nikah, akta cerai, putusan, atau data KUA",
        legalFocus: "akibat hukum dari status perkawinan ganda",
      },
      {
        slug: "cacat-wali",
        title: "Cacat Wali",
        scenario: "wali yang menikahkan diduga tidak berwenang",
        factFocus: "urutan wali, keberadaan wali nasab, dan alasan memakai wali tertentu",
        evidenceFocus: "silsilah, surat kematian, akta keluarga, atau saksi akad",
        legalFocus: "apakah wali nikah sah menurut hukum",
      },
      {
        slug: "paksaan",
        title: "Perkawinan Karena Paksaan",
        scenario: "perkawinan dilakukan karena tekanan atau paksaan",
        factFocus: "bentuk tekanan, pihak yang memaksa, dan kondisi saat akad",
        evidenceFocus: "keterangan keluarga, pesan, laporan, atau saksi acara akad",
        legalFocus: "apakah kehendak bebas para pihak terpenuhi",
      },
    ],
  },
  {
    prefix: "poligami",
    caseType: "Izin Poligami",
    subject: "Poligami",
    scenarios: [
      {
        slug: "istri-sakit",
        title: "Istri Sakit",
        scenario: "permohonan poligami karena istri mengalami sakit atau keterbatasan",
        factFocus: "keadaan kesehatan istri, perawatan, dan dampak pada rumah tangga",
        evidenceFocus: "surat dokter, saksi keluarga, atau riwayat perawatan",
        legalFocus: "alasan izin poligami dan perlindungan martabat istri",
      },
      {
        slug: "tidak-punya-keturunan",
        title: "Tidak Memiliki Keturunan",
        scenario: "permohonan poligami karena belum memiliki keturunan",
        factFocus: "lama perkawinan, upaya pengobatan, dan sikap istri",
        evidenceFocus: "surat medis, keterangan keluarga, atau bukti konsultasi",
        legalFocus: "apakah alasan tersebut cukup dan tidak merugikan istri",
      },
      {
        slug: "persetujuan-istri",
        title: "Persetujuan Istri",
        scenario: "pemeriksaan persetujuan istri terhadap poligami",
        factFocus: "apakah persetujuan diberikan sadar, bebas, dan tanpa tekanan",
        evidenceFocus: "pernyataan istri, saksi keluarga, atau berita acara persetujuan",
        legalFocus: "keabsahan persetujuan dan perlindungan hak istri",
      },
      {
        slug: "kemampuan-adil",
        title: "Kemampuan Berlaku Adil",
        scenario: "kemampuan Pemohon berlaku adil kepada istri-istri dan anak",
        factFocus: "penghasilan, tempat tinggal, pembagian waktu, dan tanggungan",
        evidenceFocus: "slip gaji, aset, rencana nafkah, atau saksi pekerjaan",
        legalFocus: "kemampuan ekonomi dan keadilan lahiriah",
      },
      {
        slug: "perlindungan-harta",
        title: "Perlindungan Harta Bersama",
        scenario: "perlindungan hak harta bersama sebelum poligami",
        factFocus: "daftar harta bersama, hutang, dan kesepakatan para pihak",
        evidenceFocus: "sertifikat, BPKB, rekening, atau pernyataan harta",
        legalFocus: "hak istri dan anak tidak boleh terabaikan",
      },
    ],
  },
  {
    prefix: "waris",
    caseType: "Waris",
    subject: "Waris",
    scenarios: [
      {
        slug: "ahli-waris",
        title: "Penetapan Ahli Waris",
        scenario: "penetapan siapa saja ahli waris pewaris",
        factFocus: "tanggal wafat pewaris, agama pewaris, dan susunan keluarga",
        evidenceFocus: "surat kematian, KK, akta kelahiran, buku nikah, atau saksi keluarga",
        legalFocus: "kelayakan masing-masing pihak sebagai ahli waris",
      },
      {
        slug: "ahli-waris-pengganti",
        title: "Ahli Waris Pengganti",
        scenario: "kedudukan ahli waris pengganti",
        factFocus: "ahli waris yang meninggal lebih dahulu dan keturunannya",
        evidenceFocus: "surat kematian, akta kelahiran, silsilah, atau saksi keluarga",
        legalFocus: "apakah ahli waris pengganti berhak menurut ketentuan",
      },
      {
        slug: "sengketa-objek",
        title: "Sengketa Objek Waris",
        scenario: "sengketa mengenai daftar dan status objek waris",
        factFocus: "asal-usul harta, penguasaan, dan klaim harta pribadi",
        evidenceFocus: "sertifikat, rekening, surat tanah, atau saksi penguasaan",
        legalFocus: "apakah objek termasuk tirkah pewaris",
      },
      {
        slug: "hutang-wasiat",
        title: "Hutang dan Wasiat Pewaris",
        scenario: "penyelesaian hutang, biaya, dan wasiat sebelum pembagian",
        factFocus: "hutang pewaris, biaya pemakaman, wasiat, dan pihak penerima",
        evidenceFocus: "kuitansi, perjanjian hutang, surat wasiat, atau saksi transaksi",
        legalFocus: "prioritas penyelesaian kewajiban pewaris",
      },
      {
        slug: "pembagian-sebelumnya",
        title: "Pembagian Waris Sebelumnya",
        scenario: "pernah ada pembagian atau kesepakatan keluarga",
        factFocus: "tanggal pembagian, pihak yang hadir, dan objek yang dibagikan",
        evidenceFocus: "akta pembagian, surat pernyataan, saksi musyawarah, atau bukti penguasaan",
        legalFocus: "apakah pembagian sebelumnya sah dan mengikat",
      },
    ],
  },
  {
    prefix: "hibah",
    caseType: "Hibah, Wasiat, dan Wakaf",
    subject: "Hibah/Wasiat/Wakaf",
    scenarios: [
      {
        slug: "hibah-orang-tua",
        title: "Hibah Orang Tua kepada Anak",
        scenario: "hibah dari orang tua kepada salah satu anak",
        factFocus: "waktu hibah, objek, penerimaan, dan pengetahuan ahli waris lain",
        evidenceFocus: "akta hibah, sertifikat, saksi keluarga, atau bukti penguasaan",
        legalFocus: "keadilan dan keabsahan hibah dalam keluarga",
      },
      {
        slug: "pencabutan-hibah",
        title: "Pencabutan Hibah",
        scenario: "permintaan pembatalan atau pencabutan hibah",
        factFocus: "alasan pencabutan, penyerahan objek, dan perubahan penguasaan",
        evidenceFocus: "akta, surat, saksi penyerahan, atau bukti penguasaan",
        legalFocus: "apakah hibah dapat dibatalkan menurut keadaan perkara",
      },
      {
        slug: "wasiat-lebih-sepertiga",
        title: "Wasiat Lebih dari Sepertiga",
        scenario: "wasiat diduga melebihi batas yang diperbolehkan",
        factFocus: "nilai harta, isi wasiat, ahli waris, dan persetujuan ahli waris",
        evidenceFocus: "surat wasiat, daftar harta, dan keterangan ahli waris",
        legalFocus: "batas wasiat dan persetujuan ahli waris",
      },
      {
        slug: "wakaf-tanah",
        title: "Wakaf Tanah",
        scenario: "wakaf tanah yang perlu penegasan atau disengketakan",
        factFocus: "ikrar wakaf, nazhir, peruntukan, dan penggunaan tanah",
        evidenceFocus: "AIW, sertifikat wakaf, saksi ikrar, atau bukti penggunaan",
        legalFocus: "kelangsungan manfaat wakaf dan kewenangan nazhir",
      },
      {
        slug: "nazhir",
        title: "Pergantian Nazhir",
        scenario: "pergantian atau sengketa pengelolaan nazhir",
        factFocus: "kinerja nazhir, alasan pergantian, dan kepentingan mauquf alaih",
        evidenceFocus: "laporan pengelolaan, surat nazhir, atau saksi masyarakat",
        legalFocus: "pengelolaan wakaf harus sesuai peruntukan dan amanah",
      },
    ],
  },
  {
    prefix: "eksyar",
    caseType: "Ekonomi Syariah",
    subject: "Ekonomi Syariah",
    scenarios: [
      {
        slug: "murabahah",
        title: "Akad Murabahah",
        scenario: "sengketa pembiayaan murabahah",
        factFocus: "objek pembiayaan, harga pokok, margin, angsuran, dan wanprestasi",
        evidenceFocus: "akad, jadwal angsuran, rekening koran, dan surat peringatan",
        legalFocus: "pemenuhan kewajiban akad dan perhitungan sisa kewajiban",
      },
      {
        slug: "mudharabah",
        title: "Akad Mudharabah",
        scenario: "sengketa bagi hasil atau kerugian usaha mudharabah",
        factFocus: "modal, pengelola, nisbah, laporan usaha, dan penyebab kerugian",
        evidenceFocus: "akad, laporan keuangan, bukti modal, atau saksi usaha",
        legalFocus: "tanggung jawab kerugian dan transparansi pengelolaan",
      },
      {
        slug: "musyarakah",
        title: "Akad Musyarakah",
        scenario: "sengketa kerja sama modal musyarakah",
        factFocus: "kontribusi modal, pengelolaan, pembagian laba, dan kerugian",
        evidenceFocus: "akad, rekening, pembukuan, atau bukti setoran modal",
        legalFocus: "hak dan kewajiban para mitra usaha",
      },
      {
        slug: "ijarah",
        title: "Akad Ijarah",
        scenario: "sengketa sewa manfaat atau jasa",
        factFocus: "objek sewa, masa sewa, pembayaran, dan penggunaan objek",
        evidenceFocus: "akad, kuitansi, bukti serah terima, atau foto objek",
        legalFocus: "apakah manfaat dan ujrah telah dipenuhi sesuai akad",
      },
      {
        slug: "jaminan",
        title: "Jaminan dan Eksekusi",
        scenario: "sengketa jaminan pembiayaan syariah",
        factFocus: "objek jaminan, penguasaan, nilai, dan tindakan eksekusi",
        evidenceFocus: "akta jaminan, sertifikat, BPKB, somasi, atau berita acara",
        legalFocus: "keabsahan tindakan terhadap jaminan dan perlindungan debitur",
      },
    ],
  },
  {
    prefix: "wali-ampu",
    caseType: "Perwalian dan Pengampuan",
    subject: "Perwalian/Pengampuan",
    scenarios: [
      {
        slug: "anak-yatim",
        title: "Perwalian Anak Yatim",
        scenario: "permohonan wali untuk anak yang orang tuanya meninggal",
        factFocus: "status orang tua, kebutuhan anak, dan hubungan Pemohon dengan anak",
        evidenceFocus: "surat kematian, KK, akta kelahiran, atau saksi keluarga",
        legalFocus: "kepentingan terbaik anak dan kelayakan wali",
      },
      {
        slug: "jual-harta-anak",
        title: "Izin Mengurus Harta Anak",
        scenario: "permohonan izin mengurus atau menjual harta anak",
        factFocus: "objek harta, alasan pengurusan, dan manfaat bagi anak",
        evidenceFocus: "sertifikat, taksiran harga, kebutuhan pendidikan/kesehatan, atau saksi keluarga",
        legalFocus: "harta anak hanya boleh digunakan untuk kepentingan anak",
      },
      {
        slug: "pengampuan-dewasa",
        title: "Pengampuan Orang Dewasa",
        scenario: "permohonan pengampuan bagi orang dewasa yang tidak cakap",
        factFocus: "kondisi kesehatan, kemampuan mengambil keputusan, dan kebutuhan perlindungan",
        evidenceFocus: "surat dokter, saksi keluarga, atau catatan perawatan",
        legalFocus: "perlindungan orang yang tidak mampu mengurus kepentingannya",
      },
      {
        slug: "wali-nikah",
        title: "Penetapan Wali untuk Nikah",
        scenario: "kebutuhan penetapan wali untuk kepentingan nikah",
        factFocus: "ketiadaan wali nasab, hubungan keluarga, dan kebutuhan administrasi",
        evidenceFocus: "silsilah, surat kematian, KK, atau keterangan KUA",
        legalFocus: "penentuan kewenangan wali secara sah",
      },
      {
        slug: "wali-sekolah",
        title: "Administrasi Pendidikan Anak",
        scenario: "perwalian untuk kebutuhan sekolah atau administrasi anak",
        factFocus: "dokumen pendidikan, pengasuhan sehari-hari, dan kebutuhan administrasi",
        evidenceFocus: "surat sekolah, KK, akta kelahiran, atau keterangan pengasuh",
        legalFocus: "perlindungan administrasi anak tanpa mengabaikan hak orang tua",
      },
    ],
  },
  {
    prefix: "mafqud",
    caseType: "Mafqud dan Orang Hilang",
    subject: "Mafqud",
    scenarios: [
      {
        slug: "suami-hilang",
        title: "Suami Hilang",
        scenario: "suami tidak diketahui keberadaannya dalam waktu lama",
        factFocus: "waktu terakhir bertemu, upaya pencarian, dan kebutuhan hukum keluarga",
        evidenceFocus: "surat desa, laporan kehilangan, komunikasi terakhir, atau saksi keluarga",
        legalFocus: "kepastian hukum bagi pasangan dan keluarga",
      },
      {
        slug: "istri-hilang",
        title: "Istri Hilang",
        scenario: "istri tidak diketahui keberadaannya",
        factFocus: "alamat terakhir, sebab pergi, komunikasi, dan upaya pencarian",
        evidenceFocus: "relas, surat keterangan, laporan, atau keterangan keluarga",
        legalFocus: "apakah keadaan hilang berdampak pada status hukum perkawinan",
      },
      {
        slug: "pewaris-hilang",
        title: "Pewaris Hilang",
        scenario: "status seseorang hilang berdampak pada waris",
        factFocus: "waktu hilang, umur, kondisi terakhir, dan ahli waris terkait",
        evidenceFocus: "laporan kehilangan, keterangan keluarga, atau pencarian resmi",
        legalFocus: "hati-hati dalam menentukan akibat hukum terhadap waris",
      },
      {
        slug: "wali-hilang",
        title: "Wali Nasab Hilang",
        scenario: "wali nasab tidak diketahui keberadaannya",
        factFocus: "kedudukan wali, alamat terakhir, dan upaya menghubungi",
        evidenceFocus: "silsilah, surat keterangan, relas, atau saksi keluarga",
        legalFocus: "apakah dapat dialihkan kepada wali berikutnya atau wali hakim",
      },
      {
        slug: "administrasi-hilang",
        title: "Administrasi Orang Hilang",
        scenario: "permohonan administrasi karena anggota keluarga hilang",
        factFocus: "kebutuhan administrasi, hubungan keluarga, dan upaya pencarian",
        evidenceFocus: "surat instansi, laporan kehilangan, atau dokumen keluarga",
        legalFocus: "kepastian hukum tanpa mengabaikan kemungkinan orang tersebut masih hidup",
      },
    ],
  },
  {
    prefix: "persidangan",
    caseType: "Persidangan dan Administrasi",
    subject: "Administrasi Persidangan",
    scenarios: [
      {
        slug: "mediasi-berhasil-sebagian",
        title: "Mediasi Berhasil Sebagian",
        scenario: "mediasi menghasilkan kesepakatan sebagian",
        factFocus: "poin yang disepakati, poin yang tetap disengketakan, dan kehendak para pihak",
        evidenceFocus: "laporan mediator, draft kesepakatan, atau keterangan para pihak",
        legalFocus: "pemisahan isu yang selesai dan yang perlu diputus",
      },
      {
        slug: "mediasi-gagal",
        title: "Mediasi Gagal",
        scenario: "mediasi tidak berhasil mendamaikan para pihak",
        factFocus: "upaya mediator, alasan gagal, dan posisi terakhir para pihak",
        evidenceFocus: "laporan mediator atau keterangan para pihak",
        legalFocus: "pemeriksaan pokok perkara dapat dilanjutkan",
      },
      {
        slug: "eksepsi-kompetensi",
        title: "Eksepsi Kompetensi",
        scenario: "keberatan mengenai kewenangan mengadili",
        factFocus: "domisili, objek perkara, akad, atau dasar kewenangan relatif/absolut",
        evidenceFocus: "KTP, alamat, akad, sertifikat, atau dokumen lain",
        legalFocus: "apakah pengadilan berwenang memeriksa perkara",
      },
      {
        slug: "pencabutan-perkara",
        title: "Pencabutan Perkara",
        scenario: "permohonan pencabutan perkara",
        factFocus: "alasan pencabutan, persetujuan pihak lawan jika diperlukan, dan akibatnya",
        evidenceFocus: "surat pencabutan, keterangan di persidangan, atau kesepakatan",
        legalFocus: "apakah pencabutan dapat dikabulkan sesuai tahap perkara",
      },
      {
        slug: "perubahan-gugatan",
        title: "Perubahan Gugatan/Permohonan",
        scenario: "perubahan gugatan atau permohonan sebelum pemeriksaan pokok",
        factFocus: "bagian yang diubah, alasan perubahan, dan tanggapan pihak lawan",
        evidenceFocus: "dokumen perubahan, berita acara, atau catatan persidangan",
        legalFocus: "apakah perubahan tidak merugikan hak pembelaan pihak lain",
      },
    ],
  },
  {
    prefix: "ecourt",
    caseType: "e-Court dan e-Litigasi",
    subject: "e-Court/e-Litigasi",
    scenarios: [
      {
        slug: "pendaftaran-elektronik",
        title: "Pendaftaran Elektronik",
        scenario: "perkara didaftarkan melalui e-Court",
        factFocus: "akun pengguna, tanggal pendaftaran, pembayaran panjar, dan dokumen unggahan",
        evidenceFocus: "nomor e-Court, bukti pembayaran, dan riwayat sistem",
        legalFocus: "validitas administrasi elektronik",
      },
      {
        slug: "jawaban-elektronik",
        title: "Jawaban Elektronik",
        scenario: "jawaban, replik, duplik, atau kesimpulan disampaikan elektronik",
        factFocus: "tanggal unggah, penerimaan dokumen, dan akses para pihak",
        evidenceFocus: "riwayat unggah, notifikasi, atau bukti sistem",
        legalFocus: "dokumen elektronik diperlakukan sebagai bagian proses persidangan",
      },
      {
        slug: "domisili-elektronik",
        title: "Domisili Elektronik",
        scenario: "pihak menggunakan domisili elektronik",
        factFocus: "alamat email/akun, persetujuan, dan riwayat pemberitahuan",
        evidenceFocus: "persetujuan e-Litigasi, log sistem, atau notifikasi email",
        legalFocus: "pemberitahuan elektronik sah jika sesuai prosedur",
      },
      {
        slug: "kendala-sistem",
        title: "Kendala Sistem",
        scenario: "kendala teknis e-Court atau e-Litigasi",
        factFocus: "waktu gangguan, jenis kendala, dan upaya mengatasi",
        evidenceFocus: "tangkapan layar, notifikasi sistem, atau surat keterangan",
        legalFocus: "perlindungan hak pihak saat ada kendala teknis",
      },
      {
        slug: "dokumen-digital",
        title: "Dokumen Digital",
        scenario: "penggunaan dokumen digital sebagai bukti atau berkas perkara",
        factFocus: "sumber dokumen, keutuhan, dan pihak yang mengunggah",
        evidenceFocus: "metadata, tanda terima unggah, atau dokumen asli pembanding",
        legalFocus: "keandalan dan relevansi dokumen digital",
      },
    ],
  },
  {
    prefix: "pbt",
    caseType: "Panggilan, Pemberitahuan, dan Relas",
    subject: "PBT/Relas",
    scenarios: [
      {
        slug: "panggilan-pribadi",
        title: "Panggilan Diterima Pribadi",
        scenario: "panggilan diterima langsung oleh pihak",
        factFocus: "tanggal panggilan, identitas penerima, dan isi panggilan",
        evidenceFocus: "relaas panggilan dan keterangan jurusita",
        legalFocus: "panggilan telah disampaikan secara patut",
      },
      {
        slug: "panggilan-keluarga",
        title: "Panggilan Melalui Keluarga",
        scenario: "panggilan diterima anggota keluarga atau orang serumah",
        factFocus: "hubungan penerima dengan pihak dan penyerahan relas",
        evidenceFocus: "relaas, tanda tangan penerima, atau keterangan jurusita",
        legalFocus: "kepatutan pemanggilan melalui orang yang layak menerima",
      },
      {
        slug: "pbt-putusan",
        title: "Pemberitahuan Putusan",
        scenario: "pemberitahuan isi putusan kepada pihak",
        factFocus: "tanggal pemberitahuan, penerima, dan tenggang upaya hukum",
        evidenceFocus: "relaas pemberitahuan putusan",
        legalFocus: "awal perhitungan tenggang upaya hukum",
      },
      {
        slug: "pbt-ikrar",
        title: "Panggilan Ikrar Talak",
        scenario: "panggilan sidang ikrar talak",
        factFocus: "tanggal panggilan, pihak yang hadir/tidak hadir, dan sebab ketidakhadiran",
        evidenceFocus: "relaas panggilan dan berita acara sidang",
        legalFocus: "apakah ikrar dapat dilaksanakan atau ditunda",
      },
      {
        slug: "relas-tempel",
        title: "Relas Tempel/Pengumuman",
        scenario: "panggilan melalui pengumuman atau penempelan",
        factFocus: "alasan penempelan, lokasi, dan waktu pengumuman",
        evidenceFocus: "berita acara, foto, atau keterangan perangkat desa",
        legalFocus: "kepatutan panggilan ketika pihak tidak dijumpai",
      },
    ],
  },
  {
    prefix: "validasi-bas",
    caseType: "Validasi BAS",
    subject: "Berita Acara Sidang",
    scenarios: [
      {
        slug: "identitas-pihak",
        title: "Konsistensi Identitas Pihak",
        scenario: "pemeriksaan kesesuaian identitas pihak dalam BAS",
        factFocus: "nama, umur, pekerjaan, alamat, dan kapasitas hukum pihak",
        evidenceFocus: "KTP, KK, surat kuasa, dan dokumen perkara",
        legalFocus: "BAS harus mencatat identitas secara benar dan konsisten",
      },
      {
        slug: "susunan-majelis",
        title: "Susunan Majelis dan PP",
        scenario: "pemeriksaan susunan majelis hakim dan panitera pengganti",
        factFocus: "nama hakim, jabatan, panitera pengganti, dan kehadiran sidang",
        evidenceFocus: "PMH, penetapan PP, dan catatan persidangan",
        legalFocus: "BAS sesuai dengan penetapan majelis dan kehadiran aktual",
      },
      {
        slug: "agenda-sidang",
        title: "Agenda Sidang",
        scenario: "pencatatan agenda sidang dan hasil sidang",
        factFocus: "agenda, kehadiran pihak, proses pemeriksaan, dan penundaan",
        evidenceFocus: "jadwal sidang, BAS sebelumnya, dan catatan panitera",
        legalFocus: "agenda dan hasil sidang harus jelas untuk kesinambungan perkara",
      },
      {
        slug: "bukti-saksi",
        title: "Bukti dan Saksi",
        scenario: "pencatatan bukti surat dan keterangan saksi dalam BAS",
        factFocus: "nomor bukti, saksi yang diperiksa, sumpah, dan pokok keterangan",
        evidenceFocus: "daftar bukti, berita acara sumpah, dan catatan pemeriksaan",
        legalFocus: "BAS menjadi rekam resmi proses pembuktian",
      },
      {
        slug: "penundaan",
        title: "Penundaan Sidang",
        scenario: "penundaan sidang dan alasan penundaan",
        factFocus: "alasan tunda, tanggal sidang berikutnya, dan pemberitahuan kepada pihak",
        evidenceFocus: "BAS, panggilan, dan catatan kalender sidang",
        legalFocus: "penundaan harus tercatat jelas dan tidak merugikan hak pihak",
      },
    ],
  },
  {
    prefix: "putusan",
    caseType: "Putusan dan Penetapan",
    subject: "Putusan/Penetapan",
    scenarios: [
      {
        slug: "verstek",
        title: "Putusan Verstek",
        scenario: "putusan karena Tergugat/Termohon tidak hadir",
        factFocus: "panggilan patut, ketidakhadiran, dan dalil yang dibuktikan",
        evidenceFocus: "relaas, bukti surat, dan keterangan saksi",
        legalFocus: "syarat pemeriksaan verstek terpenuhi",
      },
      {
        slug: "gugur",
        title: "Perkara Gugur",
        scenario: "Penggugat/Pemohon tidak hadir sehingga perkara gugur",
        factFocus: "panggilan kepada Penggugat/Pemohon dan alasan ketidakhadiran",
        evidenceFocus: "relaas panggilan dan catatan sidang",
        legalFocus: "apakah perkara dapat dinyatakan gugur",
      },
      {
        slug: "dicabut",
        title: "Perkara Dicabut",
        scenario: "perkara dicabut oleh pihak yang mengajukan",
        factFocus: "kehendak pencabutan, persetujuan lawan, dan tahap pemeriksaan",
        evidenceFocus: "surat pencabutan atau pernyataan di sidang",
        legalFocus: "akibat hukum pencabutan terhadap perkara",
      },
      {
        slug: "n-o",
        title: "Tidak Dapat Diterima",
        scenario: "gugatan/permohonan tidak dapat diterima",
        factFocus: "cacat formil, kewenangan, legal standing, atau kurang pihak",
        evidenceFocus: "dokumen gugatan, identitas, dan bukti awal",
        legalFocus: "alasan formil yang menghalangi pemeriksaan pokok",
      },
      {
        slug: "akta-damai",
        title: "Akta Damai",
        scenario: "para pihak mencapai perdamaian",
        factFocus: "isi kesepakatan, kesukarelaan, dan kemampuan melaksanakan",
        evidenceFocus: "kesepakatan tertulis, laporan mediator, atau pernyataan pihak",
        legalFocus: "kesepakatan tidak bertentangan dengan hukum dan dapat dikuatkan",
      },
    ],
  },
  {
    prefix: "eksekusi",
    caseType: "Eksekusi",
    subject: "Eksekusi",
    scenarios: [
      {
        slug: "nafkah-anak",
        title: "Eksekusi Nafkah Anak",
        scenario: "permohonan eksekusi kewajiban nafkah anak",
        factFocus: "amar putusan, jumlah tunggakan, pembayaran terakhir, dan kemampuan termohon",
        evidenceFocus: "putusan, bukti pembayaran, rekening, atau perhitungan tunggakan",
        legalFocus: "pelaksanaan amar putusan secara efektif dan proporsional",
      },
      {
        slug: "harta-bersama",
        title: "Eksekusi Harta Bersama",
        scenario: "eksekusi pembagian harta bersama",
        factFocus: "objek, amar putusan, penguasaan, dan hambatan pelaksanaan",
        evidenceFocus: "putusan, sertifikat, berita acara konstatering, atau foto objek",
        legalFocus: "objek eksekusi sesuai amar dan dapat dilaksanakan",
      },
      {
        slug: "pengosongan",
        title: "Pengosongan Objek",
        scenario: "pengosongan objek sengketa",
        factFocus: "siapa yang menguasai, penggunaan objek, dan potensi keberatan pihak ketiga",
        evidenceFocus: "putusan, penetapan eksekusi, atau berita acara lapangan",
        legalFocus: "perlindungan hak pihak dan ketertiban pelaksanaan",
      },
      {
        slug: "aanmaning",
        title: "Aanmaning",
        scenario: "teguran agar pihak melaksanakan putusan sukarela",
        factFocus: "panggilan aanmaning, sikap termohon, dan kesanggupan melaksanakan",
        evidenceFocus: "relaas, berita acara aanmaning, atau pernyataan pihak",
        legalFocus: "kesempatan pelaksanaan sukarela sebelum tindakan eksekusi",
      },
      {
        slug: "perlawanan",
        title: "Perlawanan Eksekusi",
        scenario: "adanya perlawanan terhadap pelaksanaan eksekusi",
        factFocus: "alasan perlawanan, hubungan pelawan dengan objek, dan bukti hak",
        evidenceFocus: "gugatan perlawanan, dokumen kepemilikan, atau saksi penguasaan",
        legalFocus: "apakah perlawanan mempengaruhi kelanjutan eksekusi",
      },
    ],
  },
  {
    prefix: "jinayat",
    caseType: "Jinayat",
    subject: "Jinayat",
    scenarios: [
      {
        slug: "khamar",
        title: "Jarimah Khamar",
        scenario: "dugaan mengonsumsi atau mengedarkan khamar",
        factFocus: "waktu, tempat, barang bukti, dan keadaan terdakwa/terlapor",
        evidenceFocus: "barang bukti, hasil pemeriksaan, saksi penangkap, atau pengakuan",
        legalFocus: "unsur perbuatan dan pembuktian secara sah",
      },
      {
        slug: "maisir",
        title: "Jarimah Maisir",
        scenario: "dugaan perjudian atau maisir",
        factFocus: "bentuk permainan, taruhan, alat, dan pihak yang terlibat",
        evidenceFocus: "uang/barang bukti, alat permainan, saksi, atau dokumentasi",
        legalFocus: "apakah unsur maisir terpenuhi",
      },
      {
        slug: "khalwat",
        title: "Jarimah Khalwat",
        scenario: "dugaan khalwat",
        factFocus: "tempat tertutup/sepi, hubungan para pihak, dan keadaan saat ditemukan",
        evidenceFocus: "saksi penemu, lokasi, foto, atau berita acara",
        legalFocus: "apakah unsur khalwat terbukti tanpa melanggar kehormatan pihak",
      },
      {
        slug: "ikhtilath",
        title: "Jarimah Ikhtilath",
        scenario: "dugaan ikhtilath",
        factFocus: "perbuatan, lokasi, saksi yang melihat, dan konteks kejadian",
        evidenceFocus: "saksi langsung, dokumentasi, atau berita acara pemeriksaan",
        legalFocus: "pembuktian perbuatan secara hati-hati dan tidak berlebihan",
      },
      {
        slug: "perlindungan-korban",
        title: "Perlindungan Korban",
        scenario: "pemeriksaan yang membutuhkan perlindungan korban/saksi",
        factFocus: "kondisi korban/saksi, tekanan, trauma, dan kebutuhan pendampingan",
        evidenceFocus: "keterangan pendamping, medis, psikolog, atau keluarga",
        legalFocus: "pemeriksaan tetap menjaga martabat dan keamanan korban/saksi",
      },
    ],
  },
];

function item(templateId: string, order: number, question: string, answer: string): BasQaSeedItem {
  return {
    id: `${templateId}-q${String(order).padStart(2, "0")}`,
    order,
    question,
    answer,
  };
}

function questionsFor(seed: ScenarioSeed): Array<{ question: string; answer: string }> {
  return [
    {
      question: `Apakah Saksi mengetahui bahwa pemeriksaan ini berkaitan dengan ${seed.scenario}?`,
      answer: "Saksi menerangkan bahwa Saksi memahami pokok pemeriksaan yang ditanyakan;",
    },
    {
      question: `Apa hubungan Saksi dengan para pihak dan sejak kapan Saksi mengetahui keadaan terkait ${seed.title.toLowerCase()}?`,
      answer: "Saksi menerangkan hubungan Saksi dengan para pihak dan awal pengetahuan Saksi;",
    },
    {
      question: `Apakah pengetahuan Saksi mengenai ${seed.factFocus} berasal dari melihat sendiri, mendengar sendiri, atau dari cerita orang lain?`,
      answer: "Saksi menjelaskan sumber pengetahuan Saksi secara terperinci;",
    },
    {
      question: `Kapan dan di mana fakta mengenai ${seed.factFocus} terjadi menurut pengetahuan Saksi?`,
      answer: "Saksi menerangkan waktu, tempat, dan keadaan peristiwa yang diketahui;",
    },
    {
      question: `Siapa saja yang hadir, mengetahui, atau terlibat langsung dalam peristiwa terkait ${seed.scenario}?`,
      answer: "Saksi menyebut pihak-pihak yang hadir atau mengetahui peristiwa tersebut;",
    },
    {
      question: `Apakah Saksi pernah melihat atau mengetahui dokumen/bukti berupa ${seed.evidenceFocus}?`,
      answer: "Saksi menerangkan dokumen atau bukti yang pernah Saksi lihat atau ketahui;",
    },
    {
      question: `Apakah pernah ada musyawarah keluarga, mediasi, teguran, atau upaya penyelesaian terkait ${seed.scenario}?`,
      answer: "Saksi menerangkan upaya penyelesaian yang pernah dilakukan dan hasilnya;",
    },
    {
      question: `Apakah ada tekanan, paksaan, kepentingan pribadi, atau janji tertentu yang mempengaruhi keterangan Saksi?`,
      answer: "Saksi menjawab apakah ada atau tidak ada hal yang mempengaruhi keterangan Saksi;",
    },
    {
      question: `Menurut pengetahuan Saksi, bagaimana dampak fakta tersebut terhadap hak, kewajiban, atau kepentingan para pihak?`,
      answer: "Saksi menerangkan dampak yang diketahui terhadap para pihak secara objektif;",
    },
    {
      question: `Apakah Saksi mengetahui hal lain yang penting untuk menilai ${seed.legalFocus}?`,
      answer: "Saksi menerangkan hal lain yang dianggap penting untuk pertimbangan majelis;",
    },
  ];
}

function template(index: number, group: ScenarioGroup, seed: ScenarioSeed): BasQaSeedTemplate {
  const templateId = `jlf-bas-qa-extra-${String(index).padStart(3, "0")}-${group.prefix}-${seed.slug}`;
  return {
    id: templateId,
    code: `JLF-BAS-X${String(index).padStart(3, "0")}`,
    name: `Saksi ${group.subject} - ${seed.title}`,
    caseType: group.caseType,
    paperSize: "A4",
    isActive: true,
    updatedAt: UPDATED_AT,
    items: questionsFor(seed).map((question, questionIndex) =>
      item(templateId, questionIndex + 1, question.question, question.answer)
    ),
  };
}

export const SUPPLEMENTAL_BAS_QA_TEMPLATES: BasQaSeedTemplate[] = scenarioGroups.flatMap((group, groupIndex) =>
  group.scenarios.map((seed, scenarioIndex) => template(groupIndex * 5 + scenarioIndex + 1, group, seed))
);
