export type Pendukung2018GroupKey =
  | "KEUANGAN"
  | "VALIDASI_KEUANGAN"
  | "KEADAAN_KEUANGAN"
  | "MONITORING_PERKARA"
  | "KONTROL_PERKARA"
  | "KINERJA_SIPP"
  | "AKTA_CERAI"
  | "LAPORAN"
  | "EKSTERNAL"
  | "MANUAL_REFERENSI";

export type Pendukung2018ImplementationStatus =
  | "READY_READ_ONLY"
  | "READY_OPERATIONAL"
  | "READY_WITH_DATASOURCE"
  | "READY_WITH_AUTO_REVIEWED_QUERY"
  | "PARTIAL_READ_ONLY"
  | "QUERY_NEEDS_REVIEW"
  | "MANUAL_INPUT_REQUIRED"
  | "MANUAL_INPUT_READY"
  | "EXTERNAL_CONNECTOR_REQUIRED"
  | "EXTERNAL_CONNECTOR_WAITING_CONFIG"
  | "REPORT_TEMPLATE_READY"
  | "REPORT_TEMPLATE_REQUIRED"
  | "SCHEMA_MAPPING_REQUIRED"
  | "FORMULA_CONFIGURATION_REQUIRED"
  | "UNSAFE_LEGACY_QUERY_REJECTED"
  | "MISSING_PERIOD_FILTER"
  | "LEGACY_WRITE_REFERENCE_ONLY"
  | "REFERENCE_ONLY";

export type Pendukung2018QueryPlan = {
  queryKey: string;
  queryName: string;
  sql: string;
  tables: string[];
  columns: string[];
  parameters: Array<{ name: string; label: string; dataType: "text" | "date" | "number"; required: boolean }>;
  securityStatus: "SAFE_READ_ONLY" | "NEEDS_REVIEW";
  executionMode: "READY_MONITORING" | "PENDUKUNG2018_REFERENCE_ONLY";
  reviewStatus: "AUTO_IMPORTED" | "NEEDS_ADMIN_REVIEW";
  confidenceScore: number;
  riskNotes: string;
};

export type Pendukung2018FeatureDefinition = {
  featureKey: string;
  featureCode: string;
  featureName: string;
  groupKey: Pendukung2018GroupKey;
  groupName: string;
  sortOrder: number;
  sourceFiles: string[];
  sourceEvidence: string[];
  implementationStatus: Pendukung2018ImplementationStatus;
  migrationStatus: "AUTO_IMPLEMENTED" | "PARTIAL" | "MANUAL_ONLY" | "REFERENCE_ONLY" | "EXTERNAL_REQUIRED";
  safetyStatus: string;
  reviewStatus: "AUTO_IMPORTED" | "NEEDS_ADMIN_REVIEW";
  relatedQueryKey: string;
  relatedIndicatorKey: string;
  tablesUsed: string[];
  columnsUsed: string[];
  periodType: "HARIAN" | "BULANAN" | "TAHUNAN" | "PERIODE_TANGGAL" | "TRIWULAN" | "MANUAL";
  calculationMode: "QUERY_REGISTRY" | "MANUAL_INPUT" | "EXTERNAL_CONNECTOR" | "REFERENCE_ONLY";
  resultType: "REPORT_DATA" | "ISSUE_LIST" | "SCORE" | "EXPORT_REFERENCE";
  noQueryReason: string;
  requiresManualInput: boolean;
  externalDependency: string;
  uiRoute: string;
  riskNotes: string;
  recommendationTemplate: string;
  query: Pendukung2018QueryPlan | null;
};

export const PENDUKUNG2018_GROUPS: Array<{ groupKey: Pendukung2018GroupKey; groupName: string; sortOrder: number; description: string }> = [
  { groupKey: "KEUANGAN", groupName: "Monitoring Keuangan", sortOrder: 1, description: "Transaksi biaya perkara harian dan keadaan kas perkara." },
  { groupKey: "VALIDASI_KEUANGAN", groupName: "Validasi Keuangan", sortOrder: 2, description: "Validasi saldo, transaksi harian, bulanan, dan tahunan." },
  { groupKey: "KEADAAN_KEUANGAN", groupName: "Keadaan Keuangan", sortOrder: 3, description: "Keadaan perkara berjalan, upaya hukum, dan saldo perkara." },
  { groupKey: "MONITORING_PERKARA", groupName: "Monitoring Perkara", sortOrder: 4, description: "Beban majelis/PP, validasi perkara, prodeo, dan rekap tahunan." },
  { groupKey: "KONTROL_PERKARA", groupName: "Kontrol Perkara", sortOrder: 5, description: "Kontrol minutasi, PBT, meterai, perkara lama, dan perbandingan eksternal." },
  { groupKey: "KINERJA_SIPP", groupName: "Kinerja SIPP", sortOrder: 6, description: "Kepatuhan input tahapan perkara, login, dan kinerja user." },
  { groupKey: "AKTA_CERAI", groupName: "Akta Cerai", sortOrder: 7, description: "Penyerahan, register, buku induk, dan perkara putus belum AC." },
  { groupKey: "LAPORAN", groupName: "Laporan", sortOrder: 8, description: "LIPA, laporan keuangan perkara, dan kebutuhan export." },
  { groupKey: "EKSTERNAL", groupName: "Eksternal/Online", sortOrder: 9, description: "Kirim online PTA dan monitoring pelaporan eksternal." },
  { groupKey: "MANUAL_REFERENSI", groupName: "Manual/Referensi", sortOrder: 10, description: "Fitur legacy yang bergantung tabel lokal, dokumen, atau alur manual." },
];

const GROUP_BY_KEY = new Map(PENDUKUNG2018_GROUPS.map((group) => [group.groupKey, group]));

const PERIOD_PARAMETERS = [
  { name: "date_start", label: "Tanggal mulai", dataType: "date" as const, required: true },
  { name: "date_end", label: "Tanggal selesai", dataType: "date" as const, required: true },
];

const YEAR_PARAMETERS = [{ name: "tahun", label: "Tahun", dataType: "number" as const, required: true }];
const READ_ONLY_QUERY_PATTERN = /^\s*(?:WITH\b[\s\S]+?\bSELECT\b|SELECT\b|SHOW\b|DESCRIBE\b|EXPLAIN\b)/i;
const BLOCKED_QUERY_PATTERN = /\b(INSERT|UPDATE|DELETE|DROP|ALTER|TRUNCATE|CREATE|REPLACE|GRANT|REVOKE|CALL|LOAD_FILE|INTO\s+OUTFILE|INTO\s+DUMPFILE)\b/i;

function slugKey(value: string, maxLength = 70) {
  return value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_")
    .slice(0, maxLength) || "fitur";
}

function featureKey(number: number, name: string) {
  return `P2018_${String(number).padStart(3, "0")}_${slugKey(name, 54).toUpperCase()}`;
}

function indicatorKey(number: number, name: string) {
  return `P2018_FEATURE_${String(number).padStart(3, "0")}_${slugKey(name, 50).toUpperCase()}`;
}

function queryKey(number: number, name: string) {
  return `QRY_PENDUKUNG2018_${String(number).padStart(3, "0")}_${slugKey(name, 48).toUpperCase()}`;
}

function q(input: {
  number: number;
  name: string;
  sql: string;
  tables: string[];
  columns: string[];
  parameters?: Pendukung2018QueryPlan["parameters"];
  securityStatus?: Pendukung2018QueryPlan["securityStatus"];
  confidenceScore?: number;
  riskNotes?: string;
}) {
  const normalizedSql = input.sql.replace(/\s+/g, " ").trim();
  const readOnly = READ_ONLY_QUERY_PATTERN.test(normalizedSql) && !BLOCKED_QUERY_PATTERN.test(normalizedSql);
  const securityStatus = readOnly ? input.securityStatus ?? "SAFE_READ_ONLY" : "NEEDS_REVIEW";
  const reviewStatus = input.securityStatus === "NEEDS_REVIEW" ? "NEEDS_ADMIN_REVIEW" : securityStatus === "SAFE_READ_ONLY" ? "AUTO_IMPORTED" : "NEEDS_ADMIN_REVIEW";
  return {
    queryKey: queryKey(input.number, input.name),
    queryName: `${input.name} - Pendukung2018`,
    sql: normalizedSql,
    tables: input.tables,
    columns: input.columns,
    parameters: input.parameters ?? PERIOD_PARAMETERS,
    securityStatus,
    executionMode: securityStatus === "SAFE_READ_ONLY" ? "READY_MONITORING" : "PENDUKUNG2018_REFERENCE_ONLY",
    reviewStatus,
    confidenceScore: input.confidenceScore ?? (securityStatus === "SAFE_READ_ONLY" ? 78 : 55),
    riskNotes: input.riskNotes ?? "Query kandidat disusun ulang sebagai SELECT read-only dengan parameter periode dan LIMIT.",
  } satisfies Pendukung2018QueryPlan;
}

function financialRows(extraWhere = "", extraColumns = "") {
  return `
    SELECT
      pb.id AS transaksi_id,
      pb.perkara_id,
      p.nomor_perkara,
      pb.tanggal_transaksi,
      pb.uraian,
      pb.jumlah,
      pb.jenis_transaksi,
      pb.kategori_id,
      pb.jenis_biaya_id
      ${extraColumns}
    FROM perkara_biaya pb
    LEFT JOIN perkara p ON p.perkara_id = pb.perkara_id
    WHERE pb.tanggal_transaksi BETWEEN :date_start AND :date_end
      ${extraWhere}
    ORDER BY pb.tanggal_transaksi DESC, pb.id DESC
    LIMIT 500
  `;
}

function financialSummary(extraWhere = "") {
  return `
    SELECT
      COUNT(*) AS denominator,
      COUNT(*) AS numerator,
      100 AS score_percent,
      SUM(CASE WHEN pb.jenis_transaksi = 1 THEN pb.jumlah ELSE 0 END) AS total_masuk,
      SUM(CASE WHEN pb.jenis_transaksi = -1 THEN pb.jumlah ELSE 0 END) AS total_keluar,
      SUM(pb.jumlah) AS total_transaksi
    FROM perkara_biaya pb
    WHERE pb.tanggal_transaksi BETWEEN :date_start AND :date_end
      ${extraWhere}
    LIMIT 1
  `;
}

function caseRows(dateColumn = "p.tanggal_pendaftaran", extraWhere = "") {
  return `
    SELECT
      p.perkara_id,
      p.nomor_perkara,
      p.jenis_perkara_nama,
      p.tanggal_pendaftaran,
      pp.tanggal_putusan
    FROM perkara p
    LEFT JOIN perkara_putusan pp ON pp.perkara_id = p.perkara_id
    WHERE ${dateColumn} BETWEEN :date_start AND :date_end
      ${extraWhere}
    ORDER BY ${dateColumn} DESC, p.nomor_perkara
    LIMIT 500
  `;
}

function issueQuery(sql: string) {
  return sql.replace(/\bSELECT\b/i, "SELECT 1 AS is_problem,");
}

function f(input: {
  number: number;
  name: string;
  groupKey: Pendukung2018GroupKey;
  sourceFiles: string[];
  sourceEvidence: string[];
  query?: Pendukung2018QueryPlan | null;
  implementationStatus?: Pendukung2018ImplementationStatus;
  migrationStatus?: Pendukung2018FeatureDefinition["migrationStatus"];
  safetyStatus?: string;
  periodType?: Pendukung2018FeatureDefinition["periodType"];
  calculationMode?: Pendukung2018FeatureDefinition["calculationMode"];
  resultType?: Pendukung2018FeatureDefinition["resultType"];
  noQueryReason?: string;
  requiresManualInput?: boolean;
  externalDependency?: string;
  riskNotes?: string;
  recommendationTemplate?: string;
}) {
  const group = GROUP_BY_KEY.get(input.groupKey);
  if (!group) throw new Error(`Grup Pendukung2018 tidak dikenal: ${input.groupKey}`);
  const key = featureKey(input.number, input.name);
  const query = input.query ?? null;
  const implementationStatus = input.implementationStatus ?? (query?.securityStatus === "SAFE_READ_ONLY" ? "READY_READ_ONLY" : query ? "QUERY_NEEDS_REVIEW" : "REFERENCE_ONLY");
  const safetyStatus = input.safetyStatus ?? (query?.securityStatus === "SAFE_READ_ONLY" ? "SAFE_READ_ONLY" : query ? "NEEDS_REVIEW" : implementationStatus);
  const migrationStatus = input.migrationStatus ?? (implementationStatus === "READY_READ_ONLY" || implementationStatus === "READY_OPERATIONAL" || implementationStatus === "READY_WITH_DATASOURCE" || implementationStatus === "READY_WITH_AUTO_REVIEWED_QUERY" ? "AUTO_IMPLEMENTED" : implementationStatus === "MANUAL_INPUT_REQUIRED" || implementationStatus === "MANUAL_INPUT_READY" ? "MANUAL_ONLY" : implementationStatus === "EXTERNAL_CONNECTOR_REQUIRED" || implementationStatus === "EXTERNAL_CONNECTOR_WAITING_CONFIG" ? "EXTERNAL_REQUIRED" : "PARTIAL");
  const calculationMode = input.calculationMode ?? (query ? "QUERY_REGISTRY" : implementationStatus === "EXTERNAL_CONNECTOR_REQUIRED" || implementationStatus === "EXTERNAL_CONNECTOR_WAITING_CONFIG" ? "EXTERNAL_CONNECTOR" : implementationStatus === "MANUAL_INPUT_REQUIRED" || implementationStatus === "MANUAL_INPUT_READY" || implementationStatus === "LEGACY_WRITE_REFERENCE_ONLY" ? "MANUAL_INPUT" : "REFERENCE_ONLY");
  return {
    featureKey: key,
    featureCode: `P2018-${String(input.number).padStart(3, "0")}`,
    featureName: input.name,
    groupKey: input.groupKey,
    groupName: group.groupName,
    sortOrder: input.number,
    sourceFiles: input.sourceFiles,
    sourceEvidence: input.sourceEvidence,
    implementationStatus,
    migrationStatus,
    safetyStatus,
    reviewStatus: query?.reviewStatus ?? "NEEDS_ADMIN_REVIEW",
    relatedQueryKey: query?.queryKey ?? "",
    relatedIndicatorKey: indicatorKey(input.number, input.name),
    tablesUsed: query?.tables ?? [],
    columnsUsed: query?.columns ?? [],
    periodType: input.periodType ?? "PERIODE_TANGGAL",
    calculationMode,
    resultType: input.resultType ?? (calculationMode === "QUERY_REGISTRY" ? "REPORT_DATA" : "EXPORT_REFERENCE"),
    noQueryReason: input.noQueryReason ?? (query ? "" : "Belum ada query read-only yang aman; fitur disimpan sebagai referensi/manual."),
    requiresManualInput: Boolean(input.requiresManualInput ?? calculationMode === "MANUAL_INPUT"),
    externalDependency: input.externalDependency ?? "",
    uiRoute: `/aleta-sipp?section=pendukung2018&group=${input.groupKey}&feature=${key}`,
    riskNotes: input.riskNotes ?? "Hanya metadata ALETA yang diubah. Database SIPP tetap read-only lewat query registry.",
    recommendationTemplate: input.recommendationTemplate ?? "Review hasil, parameter periode, dan status query sebelum dipakai operasional.",
    query,
  } satisfies Pendukung2018FeatureDefinition;
}

const financialColumns = ["transaksi_id", "perkara_id", "nomor_perkara", "tanggal_transaksi", "uraian", "jumlah", "jenis_transaksi", "kategori_id", "jenis_biaya_id"];
const financialTables = ["perkara_biaya", "perkara"];

export const PENDUKUNG2018_FEATURES: Pendukung2018FeatureDefinition[] = [
  f({ number: 1, name: "Buku Kas Bantu Harian", groupKey: "KEUANGAN", sourceFiles: ["keuangan_transaksi_harian.php"], sourceEvidence: ["SELECT perkara_biaya LEFT JOIN perkara filter tanggal_transaksi."], query: q({ number: 1, name: "Buku Kas Bantu Harian", sql: financialRows("", ", 100 AS score_percent"), tables: financialTables, columns: financialColumns }) }),
  f({ number: 2, name: "Transaksi Harian SIPP", groupKey: "KEUANGAN", sourceFiles: ["transaksi_harian_sipp.php"], sourceEvidence: ["Daftar transaksi harian dari perkara_biaya."], query: q({ number: 2, name: "Transaksi Harian SIPP", sql: financialRows("", ", 100 AS score_percent"), tables: financialTables, columns: financialColumns }) }),
  f({ number: 3, name: "Transaksi Panjar", groupKey: "KEUANGAN", sourceFiles: ["transaksi_panjar_harian.php"], sourceEvidence: ["Transaksi panjar harian perkara_biaya."], query: q({ number: 3, name: "Transaksi Panjar", sql: financialRows("AND pb.jenis_transaksi = 1", ", 100 AS score_percent"), tables: financialTables, columns: financialColumns, riskNotes: "Filter jenis_transaksi panjar perlu dicocokkan dengan konfigurasi SIPP aktif." }) }),
  f({ number: 4, name: "Transaksi PNBP", groupKey: "KEUANGAN", sourceFiles: ["transaksi_pnbp_harian.php"], sourceEvidence: ["Legacy menghitung total PNBP dan detail transaksi."], query: q({ number: 4, name: "Transaksi PNBP", sql: financialRows("AND (LOWER(pb.uraian) LIKE '%pnbp%' OR pb.kategori_id = 7)", ", 100 AS score_percent"), tables: financialTables, columns: financialColumns, securityStatus: "NEEDS_REVIEW", riskNotes: "Mapping kategori PNBP berbeda antar versi SIPP, butuh review admin." }) }),
  f({ number: 5, name: "Transaksi ATK", groupKey: "KEUANGAN", sourceFiles: ["transaksi_atk_harian.php"], sourceEvidence: ["Legacy membaca biaya ATK dari perkara_biaya."], query: q({ number: 5, name: "Transaksi ATK", sql: financialRows("AND (LOWER(pb.uraian) LIKE '%atk%' OR LOWER(pb.uraian) LIKE '%alat tulis%')", ", 100 AS score_percent"), tables: financialTables, columns: financialColumns, securityStatus: "NEEDS_REVIEW", riskNotes: "Pemetaan ATK berbasis uraian perlu dikonfirmasi dengan jenis_biaya lokal." }) }),
  f({ number: 6, name: "Biaya Panggilan", groupKey: "KEUANGAN", sourceFiles: ["transaksi_panggilan_harian.php"], sourceEvidence: ["Join perkara_biaya, perkara, jenis_biaya, perkara_penetapan."], query: q({ number: 6, name: "Biaya Panggilan", sql: financialRows("AND (LOWER(pb.uraian) LIKE '%panggil%' OR pb.kategori_id IN (4,5,6))", ", 100 AS score_percent"), tables: financialTables, columns: financialColumns, securityStatus: "NEEDS_REVIEW", riskNotes: "Kategori panggilan/relaas perlu review terhadap master jenis_biaya." }) }),
  f({ number: 7, name: "Biaya Pemberitahuan", groupKey: "KEUANGAN", sourceFiles: ["transaksi_pemberitahuan_harian.php"], sourceEvidence: ["Join biaya pemberitahuan dari perkara_biaya."], query: q({ number: 7, name: "Biaya Pemberitahuan", sql: financialRows("AND (LOWER(pb.uraian) LIKE '%pemberitahuan%' OR LOWER(pb.uraian) LIKE '%pbt%')", ", 100 AS score_percent"), tables: financialTables, columns: financialColumns, securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 8, name: "Materai", groupKey: "KEUANGAN", sourceFiles: ["transaksi_materai_harian.php"], sourceEvidence: ["Legacy memakai perkara_biaya untuk transaksi meterai."], query: q({ number: 8, name: "Materai", sql: financialRows("AND (pb.jenis_biaya_id = 152 OR LOWER(pb.uraian) LIKE '%meterai%' OR LOWER(pb.uraian) LIKE '%materai%')", ", 100 AS score_percent"), tables: financialTables, columns: financialColumns, securityStatus: "NEEDS_REVIEW", riskNotes: "jenis_biaya_id meterai dapat berbeda, fallback uraian perlu review." }) }),
  f({ number: 9, name: "Pengembalian Sisa Panjar", groupKey: "KEUANGAN", sourceFiles: ["transaksi_sisa_panjar_harian.php"], sourceEvidence: ["Transaksi pengembalian sisa panjar dari perkara_biaya."], query: q({ number: 9, name: "Pengembalian Sisa Panjar", sql: financialRows("AND (LOWER(pb.uraian) LIKE '%sisa panjar%' OR LOWER(pb.uraian) LIKE '%pengembalian%')", ", 100 AS score_percent"), tables: financialTables, columns: financialColumns, securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 10, name: "HHK", groupKey: "KEUANGAN", sourceFiles: ["transaksi_hhk_harian.php"], sourceEvidence: ["Transaksi HHK harian dari perkara_biaya."], query: q({ number: 10, name: "HHK", sql: financialRows("AND LOWER(pb.uraian) LIKE '%hhk%'", ", 100 AS score_percent"), tables: financialTables, columns: financialColumns, securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 11, name: "HHK Lainnya Baru", groupKey: "KEUANGAN", sourceFiles: ["transaksi_hhk_harian_lainya_baru.php"], sourceEvidence: ["Legacy mem-parsing nomor_perkara dari keterangan."], query: q({ number: 11, name: "HHK Lainnya Baru", sql: financialRows("AND LOWER(pb.uraian) LIKE '%hhk%'", ", 100 AS score_percent"), tables: financialTables, columns: financialColumns, securityStatus: "NEEDS_REVIEW", riskNotes: "Legacy mem-parsing nomor perkara dari keterangan; ALETA hanya menyimpan kandidat read-only dan butuh review." }) }),
  f({ number: 12, name: "Keuangan Jurusita/JSP", groupKey: "KEUANGAN", sourceFiles: ["monitoring_keuangan_jurusita.php"], sourceEvidence: ["Membaca perkara_biaya_jurusita dan jurusita."], query: q({ number: 12, name: "Keuangan Jurusita JSP", sql: "SELECT pbj.id AS biaya_jurusita_id, pbj.perkara_id, p.nomor_perkara, pbj.jurusita_id, j.nama AS nama_jurusita, pbj.jumlah, pbj.tanggal_transaksi, 100 AS score_percent FROM perkara_biaya_jurusita pbj LEFT JOIN perkara p ON p.perkara_id = pbj.perkara_id LEFT JOIN jurusita j ON j.id = pbj.jurusita_id WHERE pbj.tanggal_transaksi BETWEEN :date_start AND :date_end ORDER BY pbj.tanggal_transaksi DESC LIMIT 500", tables: ["perkara_biaya_jurusita", "jurusita", "perkara"], columns: ["biaya_jurusita_id", "perkara_id", "nomor_perkara", "jurusita_id", "nama_jurusita", "jumlah", "tanggal_transaksi"], securityStatus: "NEEDS_REVIEW", riskNotes: "Nama kolom jurusita pada SIPP perlu dicocokkan sebelum READY_MONITORING." }) }),

  f({ number: 13, name: "Saldo Awal", groupKey: "VALIDASI_KEUANGAN", sourceFiles: ["keuangan_saldo_awal.php"], sourceEvidence: ["Legacy memiliki INSERT/UPDATE/DELETE saldo_awal lokal."], implementationStatus: "LEGACY_WRITE_REFERENCE_ONLY", migrationStatus: "MANUAL_ONLY", safetyStatus: "PERLU_INPUT_MANUAL", periodType: "MANUAL", noQueryReason: "Legacy menulis tabel saldo_awal lokal; ALETA mengubahnya menjadi input manual/cache terverifikasi.", requiresManualInput: true, riskNotes: "Operasi INSERT/UPDATE/DELETE legacy ditolak. Nilai saldo awal harus masuk lewat input manual ALETA." }),
  f({ number: 14, name: "Validasi Transaksi Harian", groupKey: "VALIDASI_KEUANGAN", sourceFiles: ["keuangan_valid_harian.php"], sourceEvidence: ["Legacy membandingkan transaksi SIPP lalu INSERT/DELETE tabel biaya lokal."], query: q({ number: 14, name: "Validasi Transaksi Harian", sql: financialSummary(), tables: ["perkara_biaya"], columns: ["denominator", "numerator", "score_percent", "total_masuk", "total_keluar", "total_transaksi"] }), implementationStatus: "PARTIAL_READ_ONLY", migrationStatus: "PARTIAL", riskNotes: "Bagian write legacy ke tabel biaya lokal diganti agregasi read-only SIPP; validasi akhir perlu cache/manual ALETA." }),
  f({ number: 15, name: "Rekap Perbandingan Bulanan", groupKey: "VALIDASI_KEUANGAN", sourceFiles: ["keuangan_valid_bulanan_cek.php"], sourceEvidence: ["Legacy membandingkan jumlah SIPP dengan tabel biaya lokal."], query: q({ number: 15, name: "Rekap Perbandingan Bulanan", sql: "SELECT EXTRACT(YEAR FROM pb.tanggal_transaksi) AS tahun, EXTRACT(MONTH FROM pb.tanggal_transaksi) AS bulan, COUNT(*) AS denominator, COUNT(*) AS numerator, 100 AS score_percent, SUM(pb.jumlah) AS total_transaksi FROM perkara_biaya pb WHERE pb.tanggal_transaksi BETWEEN :date_start AND :date_end GROUP BY EXTRACT(YEAR FROM pb.tanggal_transaksi), EXTRACT(MONTH FROM pb.tanggal_transaksi) ORDER BY tahun, bulan LIMIT 36", tables: ["perkara_biaya"], columns: ["tahun", "bulan", "denominator", "numerator", "score_percent", "total_transaksi"], securityStatus: "NEEDS_REVIEW", riskNotes: "Fungsi EXTRACT perlu disesuaikan bila bridge memakai MySQL lama." }), implementationStatus: "PARTIAL_READ_ONLY" }),
  f({ number: 16, name: "Rekap Tahunan", groupKey: "VALIDASI_KEUANGAN", sourceFiles: ["keuangan_valid_tahunan.php"], sourceEvidence: ["Legacy melakukan agregasi bulanan/tahunan."], query: q({ number: 16, name: "Rekap Tahunan", sql: "SELECT COUNT(*) AS denominator, COUNT(*) AS numerator, 100 AS score_percent, SUM(pb.jumlah) AS total_transaksi FROM perkara_biaya pb WHERE pb.tanggal_transaksi BETWEEN :date_start AND :date_end LIMIT 1", tables: ["perkara_biaya"], columns: ["denominator", "numerator", "score_percent", "total_transaksi"] }) }),

  f({ number: 17, name: "Perkara Berjalan", groupKey: "KEADAAN_KEUANGAN", sourceFiles: ["keuangan_berjalan.php"], sourceEvidence: ["Keadaan keuangan perkara belum putus."], query: q({ number: 17, name: "Perkara Berjalan", sql: caseRows("p.tanggal_pendaftaran", "AND pp.tanggal_putusan IS NULL"), tables: ["perkara", "perkara_putusan"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_pendaftaran", "tanggal_putusan"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 18, name: "Banding", groupKey: "KEADAAN_KEUANGAN", sourceFiles: ["keuangan_banding.php"], sourceEvidence: ["Keadaan keuangan perkara banding."], query: q({ number: 18, name: "Banding", sql: caseRows("p.tanggal_pendaftaran", "AND EXISTS (SELECT 1 FROM perkara_banding b WHERE b.perkara_id = p.perkara_id)"), tables: ["perkara", "perkara_banding", "perkara_putusan"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_pendaftaran", "tanggal_putusan"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 19, name: "Kasasi", groupKey: "KEADAAN_KEUANGAN", sourceFiles: ["keuangan_kasasi.php"], sourceEvidence: ["Keadaan keuangan perkara kasasi."], query: q({ number: 19, name: "Kasasi", sql: caseRows("p.tanggal_pendaftaran", "AND EXISTS (SELECT 1 FROM perkara_kasasi k WHERE k.perkara_id = p.perkara_id)"), tables: ["perkara", "perkara_kasasi", "perkara_putusan"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_pendaftaran", "tanggal_putusan"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 20, name: "PK", groupKey: "KEADAAN_KEUANGAN", sourceFiles: ["keuangan_pk.php"], sourceEvidence: ["Keadaan keuangan perkara PK."], query: q({ number: 20, name: "PK", sql: caseRows("p.tanggal_pendaftaran", "AND EXISTS (SELECT 1 FROM perkara_pk pk WHERE pk.perkara_id = p.perkara_id)"), tables: ["perkara", "perkara_pk", "perkara_putusan"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_pendaftaran", "tanggal_putusan"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 21, name: "Putus Bersaldo", groupKey: "KEADAAN_KEUANGAN", sourceFiles: ["keuangan_putus_saldo.php"], sourceEvidence: ["Perkara putus yang masih memiliki saldo biaya."], query: q({ number: 21, name: "Putus Bersaldo", sql: issueQuery("SELECT p.perkara_id, p.nomor_perkara, pp.tanggal_putusan, SUM(pb.jumlah) AS saldo_estimasi FROM perkara p JOIN perkara_putusan pp ON pp.perkara_id = p.perkara_id LEFT JOIN perkara_biaya pb ON pb.perkara_id = p.perkara_id WHERE pp.tanggal_putusan BETWEEN :date_start AND :date_end GROUP BY p.perkara_id, p.nomor_perkara, pp.tanggal_putusan HAVING SUM(pb.jumlah) <> 0 ORDER BY pp.tanggal_putusan DESC LIMIT 500"), tables: ["perkara", "perkara_putusan", "perkara_biaya"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_putusan", "saldo_estimasi"], securityStatus: "NEEDS_REVIEW", riskNotes: "Rumus saldo harus dicocokkan dengan tanda debit/kredit SIPP aktif." }), resultType: "ISSUE_LIST" }),
  f({ number: 22, name: "Rekap Keuangan", groupKey: "KEADAAN_KEUANGAN", sourceFiles: ["keuangan_rekap.php"], sourceEvidence: ["Rekap keadaan keuangan perkara."], query: q({ number: 22, name: "Rekap Keuangan", sql: financialSummary(), tables: ["perkara_biaya"], columns: ["denominator", "numerator", "score_percent", "total_masuk", "total_keluar", "total_transaksi"] }) }),

  f({ number: 23, name: "Pembagian Perkara Majelis", groupKey: "MONITORING_PERKARA", sourceFiles: ["transaksi_majelis_harian.php"], sourceEvidence: ["Join perkara_hakim_pn, perkara, perkara_penetapan."], query: q({ number: 23, name: "Pembagian Perkara Majelis", sql: "SELECT p.perkara_id, p.nomor_perkara, ph.hakim_id, ph.nama_hakim, ph.jabatan_hakim, ph.aktif, 100 AS score_percent FROM perkara_hakim_pn ph JOIN perkara p ON p.perkara_id = ph.perkara_id WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end ORDER BY p.tanggal_pendaftaran DESC, p.nomor_perkara LIMIT 500", tables: ["perkara_hakim_pn", "perkara"], columns: ["perkara_id", "nomor_perkara", "hakim_id", "nama_hakim", "jabatan_hakim", "aktif"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 24, name: "Pembagian Majelis Ikrar", groupKey: "MONITORING_PERKARA", sourceFiles: ["transaksi_majelis_ikrar_harian.php"], sourceEvidence: ["Pembagian majelis untuk perkara ikrar."], query: q({ number: 24, name: "Pembagian Majelis Ikrar", sql: "SELECT p.perkara_id, p.nomor_perkara, ph.hakim_id, ph.nama_hakim, 100 AS score_percent FROM perkara_hakim_pn ph JOIN perkara p ON p.perkara_id = ph.perkara_id WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end AND LOWER(p.jenis_perkara_nama) LIKE '%cerai talak%' ORDER BY p.tanggal_pendaftaran DESC LIMIT 500", tables: ["perkara_hakim_pn", "perkara"], columns: ["perkara_id", "nomor_perkara", "hakim_id", "nama_hakim"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 25, name: "Rekap Beban Majelis", groupKey: "MONITORING_PERKARA", sourceFiles: ["beban_perkara_majelis.php", "beban_majelis_detil_model.php"], sourceEvidence: ["Legacy menghitung sisa, masuk, putus per majelis."], query: q({ number: 25, name: "Rekap Beban Majelis", sql: "SELECT ph.hakim_id, ph.nama_hakim, COUNT(DISTINCT p.perkara_id) AS denominator, COUNT(DISTINCT p.perkara_id) AS numerator, 100 AS score_percent FROM perkara_hakim_pn ph JOIN perkara p ON p.perkara_id = ph.perkara_id WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end GROUP BY ph.hakim_id, ph.nama_hakim ORDER BY ph.nama_hakim LIMIT 100", tables: ["perkara_hakim_pn", "perkara"], columns: ["hakim_id", "nama_hakim", "denominator", "numerator", "score_percent"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 26, name: "Pembagian Perkara ke PP", groupKey: "MONITORING_PERKARA", sourceFiles: ["transaksi_pp_harian.php"], sourceEvidence: ["Pembagian perkara ke panitera pengganti."], query: q({ number: 26, name: "Pembagian Perkara ke PP", sql: "SELECT p.perkara_id, p.nomor_perkara, pp.panitera_id, pp.nama_panitera, pp.aktif, 100 AS score_percent FROM perkara_panitera_pn pp JOIN perkara p ON p.perkara_id = pp.perkara_id WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end ORDER BY p.tanggal_pendaftaran DESC LIMIT 500", tables: ["perkara_panitera_pn", "perkara"], columns: ["perkara_id", "nomor_perkara", "panitera_id", "nama_panitera", "aktif"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 27, name: "Rekap Beban PP", groupKey: "MONITORING_PERKARA", sourceFiles: ["beban_perkara_pp.php", "beban_pp_detil_model.php"], sourceEvidence: ["Legacy menghitung beban PP per periode."], query: q({ number: 27, name: "Rekap Beban PP", sql: "SELECT pp.panitera_id, pp.nama_panitera, COUNT(DISTINCT p.perkara_id) AS denominator, COUNT(DISTINCT p.perkara_id) AS numerator, 100 AS score_percent FROM perkara_panitera_pn pp JOIN perkara p ON p.perkara_id = pp.perkara_id WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end GROUP BY pp.panitera_id, pp.nama_panitera ORDER BY pp.nama_panitera LIMIT 100", tables: ["perkara_panitera_pn", "perkara"], columns: ["panitera_id", "nama_panitera", "denominator", "numerator", "score_percent"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 28, name: "Validasi Perkara Masuk Harian", groupKey: "MONITORING_PERKARA", sourceFiles: ["perkara_masuk_valid_harian.php"], sourceEvidence: ["Legacy membandingkan panjar dan perkara lalu INSERT perkara_masuk lokal."], query: q({ number: 28, name: "Validasi Perkara Masuk Harian", sql: "SELECT COUNT(*) AS denominator, COUNT(*) AS numerator, 100 AS score_percent FROM perkara p WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end LIMIT 1", tables: ["perkara"], columns: ["denominator", "numerator", "score_percent"] }), implementationStatus: "PARTIAL_READ_ONLY", riskNotes: "Write legacy ke tabel perkara_masuk lokal diganti agregasi read-only SIPP." }),
  f({ number: 29, name: "Validasi Perkara Putus Harian", groupKey: "MONITORING_PERKARA", sourceFiles: ["perkara_putus_valid_harian.php"], sourceEvidence: ["Legacy membandingkan data putus lalu INSERT perkara_putus lokal."], query: q({ number: 29, name: "Validasi Perkara Putus Harian", sql: "SELECT COUNT(*) AS denominator, COUNT(*) AS numerator, 100 AS score_percent FROM perkara_putusan pp WHERE pp.tanggal_putusan BETWEEN :date_start AND :date_end LIMIT 1", tables: ["perkara_putusan"], columns: ["denominator", "numerator", "score_percent"] }), implementationStatus: "PARTIAL_READ_ONLY", riskNotes: "Write legacy ke tabel perkara_putus lokal diganti agregasi read-only SIPP." }),
  f({ number: 30, name: "Rekap Perbandingan Data Perkara Tahunan", groupKey: "MONITORING_PERKARA", sourceFiles: ["perkara_valid_tahunan.php"], sourceEvidence: ["Legacy melakukan rekap tahunan data perkara."], query: q({ number: 30, name: "Rekap Perbandingan Data Perkara Tahunan", sql: "SELECT COUNT(*) AS denominator, COUNT(*) AS numerator, 100 AS score_percent FROM perkara p WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end LIMIT 1", tables: ["perkara"], columns: ["denominator", "numerator", "score_percent"] }) }),
  f({ number: 31, name: "Perkara Prodeo", groupKey: "MONITORING_PERKARA", sourceFiles: ["monitoring_perkara_prodeo.php"], sourceEvidence: ["Filter perkara prodeo."], query: q({ number: 31, name: "Perkara Prodeo", sql: caseRows("p.tanggal_pendaftaran", "AND (LOWER(p.prodeo) = 'y' OR LOWER(p.jenis_perkara_nama) LIKE '%prodeo%')"), tables: ["perkara", "perkara_putusan"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_pendaftaran", "tanggal_putusan"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 32, name: "Perkara Majelis Tahunan", groupKey: "MONITORING_PERKARA", sourceFiles: ["perkara_majelis_tahunan.php"], sourceEvidence: ["Rekap perkara majelis tahunan."], query: q({ number: 32, name: "Perkara Majelis Tahunan", sql: "SELECT ph.hakim_id, ph.nama_hakim, COUNT(DISTINCT p.perkara_id) AS denominator, COUNT(DISTINCT p.perkara_id) AS numerator, 100 AS score_percent FROM perkara_hakim_pn ph JOIN perkara p ON p.perkara_id = ph.perkara_id WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end GROUP BY ph.hakim_id, ph.nama_hakim ORDER BY ph.nama_hakim LIMIT 100", tables: ["perkara_hakim_pn", "perkara"], columns: ["hakim_id", "nama_hakim", "denominator", "numerator", "score_percent"], securityStatus: "NEEDS_REVIEW" }) }),

  f({ number: 33, name: "Rekap Kontrol Perkara / e-doc", groupKey: "KONTROL_PERKARA", sourceFiles: ["kontrol.php"], sourceEvidence: ["Kontrol e-doc petitum, BAS, dan relaas."], query: q({ number: 33, name: "Rekap Kontrol Perkara e-doc", sql: issueQuery("SELECT p.perkara_id, p.nomor_perkara, p.tanggal_pendaftaran, CASE WHEN p.petitum_dok IS NULL OR p.petitum_dok = '' THEN 'PETITUM_BELUM_UPLOAD' ELSE 'OK' END AS status FROM perkara p WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end AND (p.petitum_dok IS NULL OR p.petitum_dok = '') ORDER BY p.tanggal_pendaftaran DESC LIMIT 500"), tables: ["perkara"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_pendaftaran", "status"], securityStatus: "NEEDS_REVIEW" }), resultType: "ISSUE_LIST" }),
  f({ number: 34, name: "Putus Belum Minutasi", groupKey: "KONTROL_PERKARA", sourceFiles: ["putus_belum_minut.php"], sourceEvidence: ["WHERE tanggal_minutasi IS NULL."], query: q({ number: 34, name: "Putus Belum Minutasi", sql: issueQuery("SELECT pp.perkara_id, p.nomor_perkara, pp.tanggal_putusan, pp.tanggal_minutasi FROM perkara_putusan pp JOIN perkara p ON p.perkara_id = pp.perkara_id WHERE pp.tanggal_putusan BETWEEN :date_start AND :date_end AND pp.tanggal_minutasi IS NULL ORDER BY pp.tanggal_putusan DESC LIMIT 500"), tables: ["perkara_putusan", "perkara"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_putusan", "tanggal_minutasi"] }), resultType: "ISSUE_LIST" }),
  f({ number: 35, name: "Perkara Lebih dari 5 Bulan", groupKey: "KONTROL_PERKARA", sourceFiles: ["perkara_lebih_dari6.php"], sourceEvidence: ["Legacy menghitung ambang lima bulan dan perkara belum putus."], query: q({ number: 35, name: "Perkara Lebih dari 5 Bulan", sql: issueQuery("SELECT p.perkara_id, p.nomor_perkara, p.tanggal_pendaftaran, pp.tanggal_putusan FROM perkara p LEFT JOIN perkara_putusan pp ON pp.perkara_id = p.perkara_id WHERE p.tanggal_pendaftaran <= :date_start AND pp.tanggal_putusan IS NULL ORDER BY p.tanggal_pendaftaran ASC LIMIT 500"), tables: ["perkara", "perkara_putusan"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_pendaftaran", "tanggal_putusan"], securityStatus: "NEEDS_REVIEW", riskNotes: "Parameter date_start dipakai sebagai tanggal ambang; UI dapat mengisi awal periode sebagai batas lima bulan." }), resultType: "ISSUE_LIST" }),
  f({ number: 36, name: "Belum PBT", groupKey: "KONTROL_PERKARA", sourceFiles: ["belum_pbt.php"], sourceEvidence: ["Query PBT dari perkara_putusan_pemberitahuan_putusan."], query: q({ number: 36, name: "Belum PBT", sql: issueQuery("SELECT pp.perkara_id, p.nomor_perkara, pp.tanggal_putusan FROM perkara_putusan pp JOIN perkara p ON p.perkara_id = pp.perkara_id LEFT JOIN perkara_putusan_pemberitahuan_putusan pbt ON pbt.perkara_id = pp.perkara_id WHERE pp.tanggal_putusan BETWEEN :date_start AND :date_end AND pbt.perkara_id IS NULL ORDER BY pp.tanggal_putusan DESC LIMIT 500"), tables: ["perkara_putusan", "perkara", "perkara_putusan_pemberitahuan_putusan"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_putusan"], securityStatus: "NEEDS_REVIEW" }), resultType: "ISSUE_LIST" }),
  f({ number: 37, name: "Putus Tanpa PBT", groupKey: "KONTROL_PERKARA", sourceFiles: ["putus_tanpa_pbt.php"], sourceEvidence: ["Subquery perkara_biaya kategori_id=6."], query: q({ number: 37, name: "Putus Tanpa PBT", sql: issueQuery("SELECT pp.perkara_id, p.nomor_perkara, pp.tanggal_putusan FROM perkara_putusan pp JOIN perkara p ON p.perkara_id = pp.perkara_id WHERE pp.tanggal_putusan BETWEEN :date_start AND :date_end AND NOT EXISTS (SELECT 1 FROM perkara_biaya pb WHERE pb.perkara_id = pp.perkara_id AND pb.kategori_id = 6) ORDER BY pp.tanggal_putusan DESC LIMIT 500"), tables: ["perkara_putusan", "perkara", "perkara_biaya"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_putusan"], securityStatus: "NEEDS_REVIEW" }), resultType: "ISSUE_LIST" }),
  f({ number: 38, name: "Putus Belum Meterai", groupKey: "KONTROL_PERKARA", sourceFiles: ["kontrol_putus_belum_meterai.php"], sourceEvidence: ["Perkara putus tanpa biaya meterai."], query: q({ number: 38, name: "Putus Belum Meterai", sql: issueQuery("SELECT pp.perkara_id, p.nomor_perkara, pp.tanggal_putusan FROM perkara_putusan pp JOIN perkara p ON p.perkara_id = pp.perkara_id WHERE pp.tanggal_putusan BETWEEN :date_start AND :date_end AND NOT EXISTS (SELECT 1 FROM perkara_biaya pb WHERE pb.perkara_id = pp.perkara_id AND (pb.jenis_biaya_id = 152 OR LOWER(pb.uraian) LIKE '%meterai%' OR LOWER(pb.uraian) LIKE '%materai%')) ORDER BY pp.tanggal_putusan DESC LIMIT 500"), tables: ["perkara_putusan", "perkara", "perkara_biaya"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_putusan"], securityStatus: "NEEDS_REVIEW" }), resultType: "ISSUE_LIST" }),
  f({ number: 39, name: "Meterai Belum Putus", groupKey: "KONTROL_PERKARA", sourceFiles: ["kontrol_meterai_belum_putus.php"], sourceEvidence: ["Biaya meterai tetapi belum ada putusan."], query: q({ number: 39, name: "Meterai Belum Putus", sql: issueQuery("SELECT p.perkara_id, p.nomor_perkara, pb.tanggal_transaksi, pb.uraian FROM perkara_biaya pb JOIN perkara p ON p.perkara_id = pb.perkara_id LEFT JOIN perkara_putusan pp ON pp.perkara_id = p.perkara_id WHERE pb.tanggal_transaksi BETWEEN :date_start AND :date_end AND (pb.jenis_biaya_id = 152 OR LOWER(pb.uraian) LIKE '%meterai%' OR LOWER(pb.uraian) LIKE '%materai%') AND pp.perkara_id IS NULL ORDER BY pb.tanggal_transaksi DESC LIMIT 500"), tables: ["perkara_biaya", "perkara", "perkara_putusan"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_transaksi", "uraian"], securityStatus: "NEEDS_REVIEW" }), resultType: "ISSUE_LIST" }),
  f({ number: 40, name: "PBT >14 Hari Belum AC", groupKey: "KONTROL_PERKARA", sourceFiles: ["wayahe_inkrah.php"], sourceEvidence: ["PBT/putusan, status >14 hari logic."], query: q({ number: 40, name: "PBT Lebih 14 Hari Belum AC", sql: issueQuery("SELECT p.perkara_id, p.nomor_perkara, pbt.tanggal_pemberitahuan_putusan, ac.nomor_akta_cerai FROM perkara p JOIN perkara_putusan_pemberitahuan_putusan pbt ON pbt.perkara_id = p.perkara_id LEFT JOIN perkara_akta_cerai ac ON ac.perkara_id = p.perkara_id WHERE pbt.tanggal_pemberitahuan_putusan BETWEEN :date_start AND :date_end AND ac.perkara_id IS NULL ORDER BY pbt.tanggal_pemberitahuan_putusan ASC LIMIT 500"), tables: ["perkara", "perkara_putusan_pemberitahuan_putusan", "perkara_akta_cerai"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_pemberitahuan_putusan", "nomor_akta_cerai"], securityStatus: "NEEDS_REVIEW", riskNotes: "Batas 14 hari perlu dihitung di bridge/query final sesuai fungsi tanggal database aktif." }), resultType: "ISSUE_LIST" }),
  f({ number: 41, name: "Perbandingan Tanggal Putus SIPP/SIADPA", groupKey: "KONTROL_PERKARA", sourceFiles: ["kontrol_perbandingan_data_tanggal putus.php"], sourceEvidence: ["Membandingkan SIPP dengan SIADPA eksternal."], implementationStatus: "EXTERNAL_CONNECTOR_REQUIRED", migrationStatus: "EXTERNAL_REQUIRED", safetyStatus: "EXTERNAL_CONNECTOR_REQUIRED", calculationMode: "EXTERNAL_CONNECTOR", resultType: "ISSUE_LIST", externalDependency: "SIADPA read-only connector", noQueryReason: "Perbandingan membutuhkan sumber SIADPA; query SIPP saja tidak cukup." }),
  f({ number: 42, name: "Perbandingan Saldo Keuangan SIPP/SIADPA", groupKey: "KONTROL_PERKARA", sourceFiles: ["kontrol_perbandingan_data_saldo_keuangan.php"], sourceEvidence: ["Membandingkan saldo SIPP dengan SIADPA."], implementationStatus: "EXTERNAL_CONNECTOR_REQUIRED", migrationStatus: "EXTERNAL_REQUIRED", safetyStatus: "EXTERNAL_CONNECTOR_REQUIRED", calculationMode: "EXTERNAL_CONNECTOR", resultType: "ISSUE_LIST", externalDependency: "SIADPA read-only connector", noQueryReason: "Butuh data SIADPA sebagai pembanding; belum aman dieksekusi tanpa konektor." }),
  f({ number: 43, name: "Jadwal Sidang SIPP/SIADPA", groupKey: "KONTROL_PERKARA", sourceFiles: ["cek_tanggal_sidang.php"], sourceEvidence: ["Membandingkan jadwal sidang SIADPA/SIPP."], implementationStatus: "EXTERNAL_CONNECTOR_REQUIRED", migrationStatus: "EXTERNAL_REQUIRED", safetyStatus: "EXTERNAL_CONNECTOR_REQUIRED", calculationMode: "EXTERNAL_CONNECTOR", resultType: "ISSUE_LIST", externalDependency: "SIADPA read-only connector", noQueryReason: "Butuh jadwal SIADPA sebagai pembanding." }),

  f({ number: 44, name: "Kepatuhan Pengisian SIPP", groupKey: "KINERJA_SIPP", sourceFiles: ["kinerja_kepatuhanok.php", "sys_json.php"], sourceEvidence: ["Menghitung perkara_proses, tanggal input, dan tupoksi."], query: q({ number: 44, name: "Kepatuhan Pengisian SIPP", sql: "SELECT p.perkara_id, p.nomor_perkara, pr.proses_nama, pr.tanggal_proses, pr.diinput_tanggal, 100 AS score_percent FROM perkara_proses pr JOIN perkara p ON p.perkara_id = pr.perkara_id WHERE pr.diinput_tanggal BETWEEN :date_start AND :date_end ORDER BY pr.diinput_tanggal DESC LIMIT 500", tables: ["perkara_proses", "perkara"], columns: ["perkara_id", "nomor_perkara", "proses_nama", "tanggal_proses", "diinput_tanggal"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 45, name: "Kepatuhan Pendaftaran", groupKey: "KINERJA_SIPP", sourceFiles: ["kinerja_kepatuhan_pendaftaran.php", "sys_json.php"], sourceEvidence: ["sys_json kepatuhan_tanggal_input_pendaftaran."], query: q({ number: 45, name: "Kepatuhan Pendaftaran", sql: "SELECT COUNT(*) AS denominator, COUNT(*) AS numerator, 100 AS score_percent FROM perkara p WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end LIMIT 1", tables: ["perkara"], columns: ["denominator", "numerator", "score_percent"] }) }),
  f({ number: 46, name: "PMH", groupKey: "KINERJA_SIPP", sourceFiles: ["kinerja_kepatuhan_pmh.php"], sourceEvidence: ["Kepatuhan tanggal input PMH."], query: q({ number: 46, name: "PMH", sql: "SELECT p.perkara_id, p.nomor_perkara, pp.tanggal_penetapan, pp.diinput_tanggal, 100 AS score_percent FROM perkara_penetapan pp JOIN perkara p ON p.perkara_id = pp.perkara_id WHERE pp.tanggal_penetapan BETWEEN :date_start AND :date_end ORDER BY pp.tanggal_penetapan DESC LIMIT 500", tables: ["perkara_penetapan", "perkara"], columns: ["perkara_id", "nomor_perkara", "tanggal_penetapan", "diinput_tanggal"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 47, name: "PHS / Update Sidang", groupKey: "KINERJA_SIPP", sourceFiles: ["kinerja_kepatuhan_phs.php"], sourceEvidence: ["Kepatuhan PHS dan update sidang."], query: q({ number: 47, name: "PHS Update Sidang", sql: "SELECT p.perkara_id, p.nomor_perkara, js.tanggal_sidang, js.diinput_tanggal, js.agenda, 100 AS score_percent FROM perkara_jadwal_sidang js JOIN perkara p ON p.perkara_id = js.perkara_id WHERE js.tanggal_sidang BETWEEN :date_start AND :date_end ORDER BY js.tanggal_sidang DESC LIMIT 500", tables: ["perkara_jadwal_sidang", "perkara"], columns: ["perkara_id", "nomor_perkara", "tanggal_sidang", "diinput_tanggal", "agenda"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 48, name: "Minutasi", groupKey: "KINERJA_SIPP", sourceFiles: ["kinerja_kepatuhan_minutasi.php"], sourceEvidence: ["Kepatuhan input minutasi."], query: q({ number: 48, name: "Minutasi", sql: issueQuery("SELECT pp.perkara_id, p.nomor_perkara, pp.tanggal_putusan, pp.tanggal_minutasi FROM perkara_putusan pp JOIN perkara p ON p.perkara_id = pp.perkara_id WHERE pp.tanggal_putusan BETWEEN :date_start AND :date_end AND pp.tanggal_minutasi IS NULL ORDER BY pp.tanggal_putusan DESC LIMIT 500"), tables: ["perkara_putusan", "perkara"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_putusan", "tanggal_minutasi"] }), resultType: "ISSUE_LIST" }),
  f({ number: 49, name: "Putusan", groupKey: "KINERJA_SIPP", sourceFiles: ["kinerja_kepatuhan_putusan.php"], sourceEvidence: ["Kepatuhan input putusan."], query: q({ number: 49, name: "Putusan", sql: "SELECT pp.perkara_id, p.nomor_perkara, pp.tanggal_putusan, pp.diinput_tanggal, 100 AS score_percent FROM perkara_putusan pp JOIN perkara p ON p.perkara_id = pp.perkara_id WHERE pp.tanggal_putusan BETWEEN :date_start AND :date_end ORDER BY pp.tanggal_putusan DESC LIMIT 500", tables: ["perkara_putusan", "perkara"], columns: ["perkara_id", "nomor_perkara", "tanggal_putusan", "diinput_tanggal"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 50, name: "BHT/PBT", groupKey: "KINERJA_SIPP", sourceFiles: ["kinerja_kepatuhan_bht.php", "kinerja_kepatuhan_pbt.php"], sourceEvidence: ["Kepatuhan BHT dan PBT."], query: q({ number: 50, name: "BHT PBT", sql: "SELECT p.perkara_id, p.nomor_perkara, pbt.tanggal_pemberitahuan_putusan, 100 AS score_percent FROM perkara p JOIN perkara_putusan_pemberitahuan_putusan pbt ON pbt.perkara_id = p.perkara_id WHERE pbt.tanggal_pemberitahuan_putusan BETWEEN :date_start AND :date_end ORDER BY pbt.tanggal_pemberitahuan_putusan DESC LIMIT 500", tables: ["perkara_putusan_pemberitahuan_putusan", "perkara"], columns: ["perkara_id", "nomor_perkara", "tanggal_pemberitahuan_putusan"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 51, name: "Mediasi", groupKey: "KINERJA_SIPP", sourceFiles: ["kinerja_kepatuhan_mediasi.php"], sourceEvidence: ["Kepatuhan input mediasi."], query: q({ number: 51, name: "Mediasi", sql: "SELECT p.perkara_id, p.nomor_perkara, m.tanggal_mediasi, m.hasil_mediasi, 100 AS score_percent FROM perkara_mediasi m JOIN perkara p ON p.perkara_id = m.perkara_id WHERE m.tanggal_mediasi BETWEEN :date_start AND :date_end ORDER BY m.tanggal_mediasi DESC LIMIT 500", tables: ["perkara_mediasi", "perkara"], columns: ["perkara_id", "nomor_perkara", "tanggal_mediasi", "hasil_mediasi"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 52, name: "AC/Ikrar Talak", groupKey: "KINERJA_SIPP", sourceFiles: ["kinerja_kepatuhan_ac.php"], sourceEvidence: ["Kepatuhan input AC/Ikrar Talak."], query: q({ number: 52, name: "AC Ikrar Talak", sql: "SELECT p.perkara_id, p.nomor_perkara, ac.nomor_akta_cerai, ac.tgl_akta_cerai, 100 AS score_percent FROM perkara_akta_cerai ac JOIN perkara p ON p.perkara_id = ac.perkara_id WHERE ac.tgl_akta_cerai BETWEEN :date_start AND :date_end ORDER BY ac.tgl_akta_cerai DESC LIMIT 500", tables: ["perkara_akta_cerai", "perkara"], columns: ["perkara_id", "nomor_perkara", "nomor_akta_cerai", "tgl_akta_cerai"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 53, name: "Login SIPP", groupKey: "KINERJA_SIPP", sourceFiles: ["kinerja_login.php", "sys_json.php"], sourceEvidence: ["Membaca sys_audittrail/sys_users."], query: q({ number: 53, name: "Login SIPP", sql: "SELECT a.id AS audit_id, a.userid, u.nama AS nama_user, a.waktu AS login_at, 100 AS score_percent FROM sys_audittrail a LEFT JOIN sys_users u ON u.userid = a.userid WHERE a.waktu BETWEEN :date_start AND :date_end ORDER BY a.waktu DESC LIMIT 500", tables: ["sys_audittrail", "sys_users"], columns: ["audit_id", "userid", "nama_user", "login_at"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 54, name: "Kinerja Individu/User", groupKey: "KINERJA_SIPP", sourceFiles: ["kinerja_individu.php"], sourceEvidence: ["Agregasi sys_audittrail per user."], query: q({ number: 54, name: "Kinerja Individu User", sql: "SELECT a.userid, u.nama AS nama_user, COUNT(*) AS denominator, COUNT(*) AS numerator, 100 AS score_percent FROM sys_audittrail a LEFT JOIN sys_users u ON u.userid = a.userid WHERE a.waktu BETWEEN :date_start AND :date_end GROUP BY a.userid, u.nama ORDER BY COUNT(*) DESC LIMIT 200", tables: ["sys_audittrail", "sys_users"], columns: ["userid", "nama_user", "denominator", "numerator", "score_percent"], securityStatus: "NEEDS_REVIEW" }) }),

  f({ number: 55, name: "Formulir Penyerahan AC", groupKey: "AKTA_CERAI", sourceFiles: ["ac_penyerahan.php"], sourceEvidence: ["Formulir penyerahan AC membaca perkara_biaya dan perkara."], query: q({ number: 55, name: "Formulir Penyerahan AC", sql: financialRows("AND (LOWER(pb.uraian) LIKE '%akta cerai%' OR LOWER(pb.uraian) LIKE '% ac %')", ", 100 AS score_percent"), tables: financialTables, columns: financialColumns, securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 56, name: "Laporan Penyerahan AC", groupKey: "AKTA_CERAI", sourceFiles: ["ac_penyerahan_rekap.php"], sourceEvidence: ["Rekap perkara_akta_cerai, putusan, ikrar, BHT."], query: q({ number: 56, name: "Laporan Penyerahan AC", sql: "SELECT ac.perkara_id, p.nomor_perkara, ac.nomor_akta_cerai, ac.tgl_akta_cerai, 100 AS score_percent FROM perkara_akta_cerai ac JOIN perkara p ON p.perkara_id = ac.perkara_id WHERE ac.tgl_akta_cerai BETWEEN :date_start AND :date_end ORDER BY ac.tgl_akta_cerai DESC LIMIT 500", tables: ["perkara_akta_cerai", "perkara"], columns: ["perkara_id", "nomor_perkara", "nomor_akta_cerai", "tgl_akta_cerai"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 57, name: "Putus Belum AC", groupKey: "AKTA_CERAI", sourceFiles: ["putus_belum_ac.php"], sourceEvidence: ["Cerai putus tanpa akta cerai."], query: q({ number: 57, name: "Putus Belum AC", sql: issueQuery("SELECT pp.perkara_id, p.nomor_perkara, pp.tanggal_putusan FROM perkara_putusan pp JOIN perkara p ON p.perkara_id = pp.perkara_id LEFT JOIN perkara_akta_cerai ac ON ac.perkara_id = pp.perkara_id WHERE pp.tanggal_putusan BETWEEN :date_start AND :date_end AND LOWER(p.jenis_perkara_nama) LIKE '%cerai%' AND ac.perkara_id IS NULL ORDER BY pp.tanggal_putusan DESC LIMIT 500"), tables: ["perkara_putusan", "perkara", "perkara_akta_cerai"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_putusan"] }), resultType: "ISSUE_LIST" }),
  f({ number: 58, name: "Buku Induk AC", groupKey: "AKTA_CERAI", sourceFiles: ["induk_ac.php"], sourceEvidence: ["Buku induk akta cerai."], query: q({ number: 58, name: "Buku Induk AC", sql: "SELECT ac.perkara_id, p.nomor_perkara, ac.nomor_akta_cerai, ac.tgl_akta_cerai, 100 AS score_percent FROM perkara_akta_cerai ac JOIN perkara p ON p.perkara_id = ac.perkara_id WHERE ac.tgl_akta_cerai BETWEEN :date_start AND :date_end ORDER BY ac.nomor_akta_cerai LIMIT 500", tables: ["perkara_akta_cerai", "perkara"], columns: ["perkara_id", "nomor_perkara", "nomor_akta_cerai", "tgl_akta_cerai"], securityStatus: "NEEDS_REVIEW" }) }),
  f({ number: 59, name: "Register AC", groupKey: "AKTA_CERAI", sourceFiles: ["register_akta_cerai.php"], sourceEvidence: ["Register akta cerai."], query: q({ number: 59, name: "Register AC", sql: "SELECT ac.perkara_id, p.nomor_perkara, ac.nomor_akta_cerai, ac.tgl_akta_cerai, 100 AS score_percent FROM perkara_akta_cerai ac JOIN perkara p ON p.perkara_id = ac.perkara_id WHERE ac.tgl_akta_cerai BETWEEN :date_start AND :date_end ORDER BY ac.tgl_akta_cerai DESC LIMIT 500", tables: ["perkara_akta_cerai", "perkara"], columns: ["perkara_id", "nomor_perkara", "nomor_akta_cerai", "tgl_akta_cerai"], securityStatus: "NEEDS_REVIEW" }) }),

  f({ number: 60, name: "LIPA 1-17", groupKey: "LAPORAN", sourceFiles: ["laporan.php", "laporan_proses.php"], sourceEvidence: ["Legacy mengisi template LIPA 1-17."], implementationStatus: "REPORT_TEMPLATE_REQUIRED", migrationStatus: "PARTIAL", safetyStatus: "REPORT_TEMPLATE_REQUIRED", resultType: "EXPORT_REFERENCE", noQueryReason: "LIPA 1-17 sudah dibuka sebagai modul laporan awal; LIPA 7 memakai fitur Keuangan Perkara, laporan lain menunggu template resmi." }),
  f({ number: 61, name: "Input Pagu/Iwadl/Yandu/Sidkel/Prodeo/Posbakum/Petikan", groupKey: "MANUAL_REFERENSI", sourceFiles: ["laporan_pagu.php", "1.1.sql", "1.5.sql"], sourceEvidence: ["Legacy membuat/mengubah tabel lokal pelaporan."], implementationStatus: "MANUAL_INPUT_READY", migrationStatus: "MANUAL_ONLY", safetyStatus: "MANUAL_INPUT_READY", calculationMode: "MANUAL_INPUT", resultType: "EXPORT_REFERENCE", noQueryReason: "Legacy menulis tabel lokal pelaporan; ALETA memakai input manual/cache metadata, bukan write ke SIPP.", requiresManualInput: true }),
  f({ number: 62, name: "Kirim Online PTA", groupKey: "EKSTERNAL", sourceFiles: ["laporan_menu.php"], sourceEvidence: ["Menu kirim online PTA."], implementationStatus: "EXTERNAL_CONNECTOR_REQUIRED", migrationStatus: "EXTERNAL_REQUIRED", safetyStatus: "EXTERNAL_CONNECTOR_REQUIRED", calculationMode: "EXTERNAL_CONNECTOR", resultType: "EXPORT_REFERENCE", externalDependency: "Connector PTA/Simkara resmi", noQueryReason: "Kirim online membutuhkan endpoint eksternal resmi dan kredensial; belum dieksekusi dari ALETA." }),
  f({ number: 63, name: "Monitoring Pelaporan", groupKey: "EKSTERNAL", sourceFiles: ["laporan_monitoring.php"], sourceEvidence: ["GET eksternal simkara.pta-semarang.go.id/test/monitoring_data."], implementationStatus: "EXTERNAL_CONNECTOR_REQUIRED", migrationStatus: "EXTERNAL_REQUIRED", safetyStatus: "EXTERNAL_CONNECTOR_REQUIRED", calculationMode: "EXTERNAL_CONNECTOR", resultType: "EXPORT_REFERENCE", externalDependency: "Connector monitoring pelaporan PTA", noQueryReason: "Sumber data eksternal belum tersedia sebagai connector read-only." }),
  f({ number: 64, name: "LIPA 7 / Keuangan Perkara", groupKey: "LAPORAN", sourceFiles: ["lipa7a.php"], sourceEvidence: ["Agregasi keuangan perkara LIPA 7."], query: q({ number: 64, name: "LIPA 7 Keuangan Perkara", sql: financialSummary(), tables: ["perkara_biaya"], columns: ["denominator", "numerator", "score_percent", "total_masuk", "total_keluar", "total_transaksi"] }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 65, name: "Delegasi/Register/SAPM/Dokumen", groupKey: "MANUAL_REFERENSI", sourceFiles: ["register_*.php", "delegasi*.php", "sapm*.php", "dokumen*.php"], sourceEvidence: ["Menu tambahan non-main: register, delegasi, SAPM, dokumen."], implementationStatus: "SCHEMA_MAPPING_REQUIRED", migrationStatus: "PARTIAL", safetyStatus: "SCHEMA_MAPPING_REQUIRED", resultType: "EXPORT_REFERENCE", noQueryReason: "Kelompok fitur legacy dipecah menjadi fitur granular mulai nomor 66 agar audit query, register, delegasi, dan SAPM bisa ditinjau satu per satu." }),

  f({ number: 66, name: "Delegasi Masuk", groupKey: "EKSTERNAL", sourceFiles: ["delegasi_masuk.php", "delegasi_masuk_pta.php"], sourceEvidence: ["Legacy membaca daftar delegasi masuk dan menggabungkan perkara, PP, serta status proses delegasi."], query: q({ number: 66, name: "Delegasi Masuk", sql: "SELECT d.id AS delegasi_id, d.perkara_id, p.nomor_perkara, pp.nama_panitera, d.tanggal AS tanggal_delegasi, d.status_kirim, 100 AS score_percent FROM delegasi_masuk d LEFT JOIN perkara p ON p.perkara_id = d.perkara_id LEFT JOIN perkara_panitera_pn pp ON pp.perkara_id = d.perkara_id AND pp.aktif = 'Y' WHERE d.tanggal BETWEEN :date_start AND :date_end ORDER BY d.tanggal DESC LIMIT 500", tables: ["delegasi_masuk", "perkara", "perkara_panitera_pn"], columns: ["delegasi_id", "perkara_id", "nomor_perkara", "nama_panitera", "tanggal_delegasi", "status_kirim"], securityStatus: "NEEDS_REVIEW", riskNotes: "Tabel delegasi_masuk pada legacy dapat berasal dari database lokal/eksternal, sehingga perlu validasi datasource read-only." }), implementationStatus: "QUERY_NEEDS_REVIEW", migrationStatus: "PARTIAL", resultType: "REPORT_DATA", externalDependency: "Konektor delegasi read-only bila tabel bukan bagian dari SIPP utama." }),
  f({ number: 67, name: "Delegasi Keluar", groupKey: "EKSTERNAL", sourceFiles: ["delegasi_keluar.php", "delegasi_keluar_kirim_pta.php"], sourceEvidence: ["Legacy menampilkan delegasi keluar, nomor perkara, majelis/penetapan, dan status kirim PTA."], query: q({ number: 67, name: "Delegasi Keluar", sql: "SELECT d.id AS delegasi_id, d.perkara_id, p.nomor_perkara, pn.tanggal_penetapan, d.tgl_pengiriman, d.status_kirim, 100 AS score_percent FROM delegasi_keluar d LEFT JOIN perkara p ON p.perkara_id = d.perkara_id LEFT JOIN perkara_penetapan pn ON pn.perkara_id = d.perkara_id WHERE d.tgl_pengiriman BETWEEN :date_start AND :date_end ORDER BY d.tgl_pengiriman DESC LIMIT 500", tables: ["delegasi_keluar", "perkara", "perkara_penetapan"], columns: ["delegasi_id", "perkara_id", "nomor_perkara", "tanggal_penetapan", "tgl_pengiriman", "status_kirim"], securityStatus: "NEEDS_REVIEW", riskNotes: "Kolom status/tanggal delegasi keluar perlu dicocokkan dengan schema lokal legacy." }), implementationStatus: "QUERY_NEEDS_REVIEW", migrationStatus: "PARTIAL", resultType: "REPORT_DATA", externalDependency: "Konektor delegasi/PTA read-only." }),
  f({ number: 68, name: "Kontrol Delegasi Keluar", groupKey: "EKSTERNAL", sourceFiles: ["delegasi_keluar_kontrol.php", "delegasi_keluar_kontrol_proses.php"], sourceEvidence: ["Legacy mengecek delegasi keluar yang belum selesai atau belum terkirim."], query: q({ number: 68, name: "Kontrol Delegasi Keluar", sql: issueQuery("SELECT d.id AS delegasi_id, d.perkara_id, p.nomor_perkara, d.tgl_pengiriman, d.status_kirim FROM delegasi_keluar d LEFT JOIN perkara p ON p.perkara_id = d.perkara_id WHERE d.tgl_pengiriman BETWEEN :date_start AND :date_end AND (d.status_kirim IS NULL OR d.status_kirim <> 1) ORDER BY d.tgl_pengiriman ASC LIMIT 500"), tables: ["delegasi_keluar", "perkara"], columns: ["is_problem", "delegasi_id", "perkara_id", "nomor_perkara", "tgl_pengiriman", "status_kirim"], securityStatus: "NEEDS_REVIEW", riskNotes: "Nilai status_kirim legacy perlu dikonfirmasi sebelum dipakai sebagai temuan operasional." }), implementationStatus: "QUERY_NEEDS_REVIEW", migrationStatus: "PARTIAL", resultType: "ISSUE_LIST", externalDependency: "Konektor delegasi/PTA read-only." }),
  f({ number: 69, name: "Permohonan Bantuan Delegasi Keluar", groupKey: "EKSTERNAL", sourceFiles: ["delegasi_keluar_permohonan.php"], sourceEvidence: ["Legacy membuat permohonan bantuan panggilan/pemberitahuan ke satker lain."], query: q({ number: 69, name: "Permohonan Bantuan Delegasi Keluar", sql: "SELECT d.id AS delegasi_id, d.perkara_id, p.nomor_perkara, d.tgl_pengiriman, d.tujuan_satker, d.status_kirim, 100 AS score_percent FROM delegasi_keluar d LEFT JOIN perkara p ON p.perkara_id = d.perkara_id WHERE d.tgl_pengiriman BETWEEN :date_start AND :date_end ORDER BY d.tgl_pengiriman DESC LIMIT 500", tables: ["delegasi_keluar", "perkara"], columns: ["delegasi_id", "perkara_id", "nomor_perkara", "tgl_pengiriman", "tujuan_satker", "status_kirim"], securityStatus: "NEEDS_REVIEW", riskNotes: "Kolom tujuan_satker tidak selalu sama di semua instalasi legacy." }), implementationStatus: "QUERY_NEEDS_REVIEW", migrationStatus: "PARTIAL", resultType: "EXPORT_REFERENCE", externalDependency: "Konektor delegasi/PTA read-only." }),
  f({ number: 70, name: "Pembagian Perkara Jurusita/JSP", groupKey: "MONITORING_PERKARA", sourceFiles: ["pembagian_perkara_js.php", "pembagian_perkara_js_detail.php"], sourceEvidence: ["Legacy memiliki pembagian perkara jurusita/JSP seperti pembagian majelis dan PP."], query: q({ number: 70, name: "Pembagian Perkara Jurusita JSP", sql: "SELECT p.perkara_id, p.nomor_perkara, js.jurusita_id, js.nama_jurusita, js.aktif, 100 AS score_percent FROM perkara_jurusita js JOIN perkara p ON p.perkara_id = js.perkara_id WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end ORDER BY p.tanggal_pendaftaran DESC LIMIT 500", tables: ["perkara_jurusita", "perkara"], columns: ["perkara_id", "nomor_perkara", "jurusita_id", "nama_jurusita", "aktif"], securityStatus: "NEEDS_REVIEW", riskNotes: "Sebagian SIPP memakai nama tabel/kolom jurusita berbeda; query harus direview terhadap SIPP live." }), implementationStatus: "QUERY_NEEDS_REVIEW", migrationStatus: "PARTIAL" }),
  f({ number: 71, name: "Register Induk Perkara Gugatan", groupKey: "LAPORAN", sourceFiles: ["register_gugatan.php", "dok_sapm_register_induk.php", "dok_sapm_register_induk_cetak.php"], sourceEvidence: ["Legacy register induk menampilkan perkara gugatan, tanggal daftar, para pihak, dan status putusan."], query: q({ number: 71, name: "Register Induk Perkara Gugatan", sql: "SELECT p.perkara_id, p.nomor_perkara, p.jenis_perkara_nama, p.tanggal_pendaftaran, pp.tanggal_putusan, 100 AS score_percent FROM perkara p LEFT JOIN perkara_putusan pp ON pp.perkara_id = p.perkara_id WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end AND LOWER(p.jenis_perkara_nama) NOT LIKE '%permohonan%' ORDER BY p.tanggal_pendaftaran DESC, p.nomor_perkara LIMIT 500", tables: ["perkara", "perkara_putusan"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_pendaftaran", "tanggal_putusan"] }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 72, name: "Register Induk Perkara Permohonan", groupKey: "LAPORAN", sourceFiles: ["register_permohonan.php", "dok_sapm_register_induk.php"], sourceEvidence: ["Legacy register permohonan menampilkan perkara voluntair/permohonan per periode."], query: q({ number: 72, name: "Register Induk Perkara Permohonan", sql: "SELECT p.perkara_id, p.nomor_perkara, p.jenis_perkara_nama, p.tanggal_pendaftaran, pp.tanggal_putusan, 100 AS score_percent FROM perkara p LEFT JOIN perkara_putusan pp ON pp.perkara_id = p.perkara_id WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end AND LOWER(p.jenis_perkara_nama) LIKE '%permohonan%' ORDER BY p.tanggal_pendaftaran DESC, p.nomor_perkara LIMIT 500", tables: ["perkara", "perkara_putusan"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_pendaftaran", "tanggal_putusan"] }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 73, name: "Register Mediasi", groupKey: "LAPORAN", sourceFiles: ["register_mediasi.php", "dok_sapm_register_mediasi.php", "dok_sapm_cetak_reg_mediasi.php"], sourceEvidence: ["Legacy register mediasi membaca perkara dan data mediasi."], query: q({ number: 73, name: "Register Mediasi", sql: "SELECT m.perkara_id, p.nomor_perkara, m.tanggal_mediasi, m.hasil_mediasi, 100 AS score_percent FROM perkara_mediasi m JOIN perkara p ON p.perkara_id = m.perkara_id WHERE m.tanggal_mediasi BETWEEN :date_start AND :date_end ORDER BY m.tanggal_mediasi DESC LIMIT 500", tables: ["perkara_mediasi", "perkara"], columns: ["perkara_id", "nomor_perkara", "tanggal_mediasi", "hasil_mediasi"], securityStatus: "NEEDS_REVIEW", riskNotes: "Kolom hasil/tanggal mediasi perlu divalidasi pada versi SIPP aktif." }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 74, name: "Register Permohonan Banding", groupKey: "LAPORAN", sourceFiles: ["register_permohonan_banding.php", "dok_sapm_register_permohonan_banding.php", "dok_sapm_register_permohonan_banding_prodeo.php"], sourceEvidence: ["Legacy register banding menampilkan perkara banding dan status biaya/prodeo."], query: q({ number: 74, name: "Register Permohonan Banding", sql: "SELECT b.perkara_id, p.nomor_perkara, b.permohonan_banding, b.tanggal_putusan_banding, 100 AS score_percent FROM perkara_banding b JOIN perkara p ON p.perkara_id = b.perkara_id WHERE b.permohonan_banding BETWEEN :date_start AND :date_end ORDER BY b.permohonan_banding DESC LIMIT 500", tables: ["perkara_banding", "perkara"], columns: ["perkara_id", "nomor_perkara", "permohonan_banding", "tanggal_putusan_banding"], securityStatus: "NEEDS_REVIEW", riskNotes: "Nama kolom banding berbeda antar versi SIPP; perlu review sebelum aktif." }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 75, name: "Register Permohonan Kasasi", groupKey: "LAPORAN", sourceFiles: ["register_permohonan_kasasi.php", "dok_sapm_register_kasasi.php", "dok_sapm_register_permohonan_kasasi_bebas_biaya.php"], sourceEvidence: ["Legacy register kasasi menampilkan permohonan kasasi dan status bebas biaya."], query: q({ number: 75, name: "Register Permohonan Kasasi", sql: "SELECT k.perkara_id, p.nomor_perkara, k.permohonan_kasasi, k.tanggal_putusan_kasasi, 100 AS score_percent FROM perkara_kasasi k JOIN perkara p ON p.perkara_id = k.perkara_id WHERE k.permohonan_kasasi BETWEEN :date_start AND :date_end ORDER BY k.permohonan_kasasi DESC LIMIT 500", tables: ["perkara_kasasi", "perkara"], columns: ["perkara_id", "nomor_perkara", "permohonan_kasasi", "tanggal_putusan_kasasi"], securityStatus: "NEEDS_REVIEW", riskNotes: "Nama kolom kasasi perlu divalidasi terhadap SIPP live." }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 76, name: "Register Permohonan PK", groupKey: "LAPORAN", sourceFiles: ["register_permohonan_pk.php"], sourceEvidence: ["Legacy register PK menampilkan permohonan peninjauan kembali per periode."], query: q({ number: 76, name: "Register Permohonan PK", sql: "SELECT pk.perkara_id, p.nomor_perkara, pk.permohonan_pk, pk.tanggal_putusan_pk, 100 AS score_percent FROM perkara_pk pk JOIN perkara p ON p.perkara_id = pk.perkara_id WHERE pk.permohonan_pk BETWEEN :date_start AND :date_end ORDER BY pk.permohonan_pk DESC LIMIT 500", tables: ["perkara_pk", "perkara"], columns: ["perkara_id", "nomor_perkara", "permohonan_pk", "tanggal_putusan_pk"], securityStatus: "NEEDS_REVIEW", riskNotes: "Nama kolom PK perlu validasi SIPP live." }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 77, name: "Register Eksekusi", groupKey: "LAPORAN", sourceFiles: ["register_eksekusi.php", "dok_sapm_register_pendaftaran_eksekusi.php"], sourceEvidence: ["Legacy register eksekusi membaca perkara eksekusi dan nomor register."], query: q({ number: 77, name: "Register Eksekusi", sql: "SELECT e.perkara_id, p.nomor_perkara, e.nomor_eksekusi, e.tanggal_pendaftaran_eksekusi, 100 AS score_percent FROM perkara_eksekusi e LEFT JOIN perkara p ON p.perkara_id = e.perkara_id WHERE e.tanggal_pendaftaran_eksekusi BETWEEN :date_start AND :date_end ORDER BY e.tanggal_pendaftaran_eksekusi DESC LIMIT 500", tables: ["perkara_eksekusi", "perkara"], columns: ["perkara_id", "nomor_perkara", "nomor_eksekusi", "tanggal_pendaftaran_eksekusi"], securityStatus: "NEEDS_REVIEW", riskNotes: "Schema eksekusi perlu dicocokkan dengan versi SIPP aktif." }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 78, name: "Register Sita", groupKey: "LAPORAN", sourceFiles: ["register_sita.php", "dok_sapm_register_sita.php"], sourceEvidence: ["Legacy register sita menampilkan pendaftaran dan pelaksanaan sita."], query: q({ number: 78, name: "Register Sita", sql: "SELECT s.perkara_id, p.nomor_perkara, s.nomor_sita, s.tanggal_pendaftaran_sita, 100 AS score_percent FROM perkara_sita s LEFT JOIN perkara p ON p.perkara_id = s.perkara_id WHERE s.tanggal_pendaftaran_sita BETWEEN :date_start AND :date_end ORDER BY s.tanggal_pendaftaran_sita DESC LIMIT 500", tables: ["perkara_sita", "perkara"], columns: ["perkara_id", "nomor_perkara", "nomor_sita", "tanggal_pendaftaran_sita"], securityStatus: "NEEDS_REVIEW", riskNotes: "Schema sita perlu review terhadap SIPP live." }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 79, name: "Register Kuasa Hukum", groupKey: "LAPORAN", sourceFiles: ["register_kuasa.php", "register_surat_kuasa_pdf.php"], sourceEvidence: ["Legacy register kuasa dan surat kuasa PDF membaca data pengacara/kuasa perkara."], query: q({ number: 79, name: "Register Kuasa Hukum", sql: "SELECT pk.perkara_id, p.nomor_perkara, pk.nama AS nama_kuasa, pk.tanggal_surat_kuasa, 100 AS score_percent FROM perkara_pengacara pk JOIN perkara p ON p.perkara_id = pk.perkara_id WHERE pk.tanggal_surat_kuasa BETWEEN :date_start AND :date_end ORDER BY pk.tanggal_surat_kuasa DESC LIMIT 500", tables: ["perkara_pengacara", "perkara"], columns: ["perkara_id", "nomor_perkara", "nama_kuasa", "tanggal_surat_kuasa"], securityStatus: "NEEDS_REVIEW", riskNotes: "Nama tabel/kolom kuasa hukum perlu validasi SIPP live." }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 80, name: "Register Prodeo/Pembebasan Biaya", groupKey: "LAPORAN", sourceFiles: ["register_prodeo.php", "dok_sapm_register_permohonan_pembebasan_biaya_perkara.php"], sourceEvidence: ["Legacy register prodeo/pembebasan biaya memakai perkara prodeo dan laporan bantuan biaya."], query: q({ number: 80, name: "Register Prodeo Pembebasan Biaya", sql: "SELECT p.perkara_id, p.nomor_perkara, p.jenis_perkara_nama, p.tanggal_pendaftaran, p.prodeo, 100 AS score_percent FROM perkara p WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end AND (LOWER(COALESCE(p.prodeo, '')) = 'y' OR LOWER(p.jenis_perkara_nama) LIKE '%prodeo%') ORDER BY p.tanggal_pendaftaran DESC LIMIT 500", tables: ["perkara"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_pendaftaran", "prodeo"], securityStatus: "NEEDS_REVIEW", riskNotes: "Kolom prodeo tidak selalu tersedia pada semua versi SIPP." }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 81, name: "SAPM Buku Agenda Pemanggilan", groupKey: "KONTROL_PERKARA", sourceFiles: ["dok_sapm_buku_agenda_pemanggilan.php"], sourceEvidence: ["Legacy SAPM buku agenda pemanggilan memakai jadwal sidang dan perkara."], query: q({ number: 81, name: "SAPM Buku Agenda Pemanggilan", sql: "SELECT js.perkara_id, p.nomor_perkara, js.tanggal_sidang, js.agenda, 100 AS score_percent FROM perkara_jadwal_sidang js JOIN perkara p ON p.perkara_id = js.perkara_id WHERE js.tanggal_sidang BETWEEN :date_start AND :date_end ORDER BY js.tanggal_sidang ASC, p.nomor_perkara LIMIT 500", tables: ["perkara_jadwal_sidang", "perkara"], columns: ["perkara_id", "nomor_perkara", "tanggal_sidang", "agenda"], securityStatus: "NEEDS_REVIEW", riskNotes: "Output agenda pemanggilan butuh mapping relaas/panggilan lebih rinci." }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 82, name: "SAPM Kendali Pemanggilan Ghaib", groupKey: "KONTROL_PERKARA", sourceFiles: ["dok_sapm_kendali_pemanggilan_ghoib.php", "dok_sapm_kendali_pemanggilan_ghoib_input.php"], sourceEvidence: ["Legacy SAPM kendali ghoib memantau panggilan ghaib dan input manual."], query: q({ number: 82, name: "SAPM Kendali Pemanggilan Ghaib", sql: issueQuery("SELECT p.perkara_id, p.nomor_perkara, js.tanggal_sidang, js.agenda FROM perkara p JOIN perkara_jadwal_sidang js ON js.perkara_id = p.perkara_id WHERE js.tanggal_sidang BETWEEN :date_start AND :date_end AND (LOWER(js.agenda) LIKE '%ghaib%' OR LOWER(js.agenda) LIKE '%ghoib%') ORDER BY js.tanggal_sidang ASC LIMIT 500"), tables: ["perkara", "perkara_jadwal_sidang"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_sidang", "agenda"], securityStatus: "NEEDS_REVIEW", riskNotes: "Legacy sebagian memakai input lokal; query ini hanya kandidat deteksi awal dari agenda sidang." }), implementationStatus: "PARTIAL_READ_ONLY", migrationStatus: "PARTIAL", resultType: "ISSUE_LIST" }),
  f({ number: 83, name: "SAPM Daftar Perkara Putus Sudah BHT", groupKey: "KONTROL_PERKARA", sourceFiles: ["dok_sapm_daftar_perkara_putus_sudah_bht.php", "dok_sapm_daftar_perkara_putus_ct_sudah_bht.php"], sourceEvidence: ["Legacy menampilkan daftar perkara putus yang sudah BHT."], query: q({ number: 83, name: "SAPM Daftar Perkara Putus Sudah BHT", sql: "SELECT pp.perkara_id, p.nomor_perkara, pp.tanggal_putusan, pp.tanggal_bht, 100 AS score_percent FROM perkara_putusan pp JOIN perkara p ON p.perkara_id = pp.perkara_id WHERE pp.tanggal_putusan BETWEEN :date_start AND :date_end AND pp.tanggal_bht IS NOT NULL ORDER BY pp.tanggal_bht DESC LIMIT 500", tables: ["perkara_putusan", "perkara"], columns: ["perkara_id", "nomor_perkara", "tanggal_putusan", "tanggal_bht"], securityStatus: "NEEDS_REVIEW", riskNotes: "Nama kolom tanggal_bht perlu validasi SIPP live." }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 84, name: "SAPM Daftar Tidak Hadir Saat Putusan", groupKey: "KONTROL_PERKARA", sourceFiles: ["dok_sapm_daftar_yang_tidak_hadir_dalam_pengucapan_putusan.php"], sourceEvidence: ["Legacy membuat daftar pihak yang tidak hadir dalam pengucapan putusan."], query: q({ number: 84, name: "SAPM Daftar Tidak Hadir Saat Putusan", sql: issueQuery("SELECT pp.perkara_id, p.nomor_perkara, pp.tanggal_putusan, js.agenda FROM perkara_putusan pp JOIN perkara p ON p.perkara_id = pp.perkara_id LEFT JOIN perkara_jadwal_sidang js ON js.perkara_id = pp.perkara_id AND js.tanggal_sidang = pp.tanggal_putusan WHERE pp.tanggal_putusan BETWEEN :date_start AND :date_end AND (LOWER(COALESCE(js.agenda, '')) LIKE '%putusan%' OR js.agenda IS NULL) ORDER BY pp.tanggal_putusan DESC LIMIT 500"), tables: ["perkara_putusan", "perkara", "perkara_jadwal_sidang"], columns: ["is_problem", "perkara_id", "nomor_perkara", "tanggal_putusan", "agenda"], securityStatus: "NEEDS_REVIEW", riskNotes: "Data kehadiran pihak biasanya berada pada relaas/berita acara; query ini kandidat awal dan perlu review." }), resultType: "ISSUE_LIST" }),
  f({ number: 85, name: "SAPM Register Gugatan Sederhana", groupKey: "LAPORAN", sourceFiles: ["dok_sapm_register_gugatan_sederhana.php"], sourceEvidence: ["Legacy register gugatan sederhana memfilter jenis perkara sederhana."], query: q({ number: 85, name: "SAPM Register Gugatan Sederhana", sql: "SELECT p.perkara_id, p.nomor_perkara, p.jenis_perkara_nama, p.tanggal_pendaftaran, pp.tanggal_putusan, 100 AS score_percent FROM perkara p LEFT JOIN perkara_putusan pp ON pp.perkara_id = p.perkara_id WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end AND LOWER(p.jenis_perkara_nama) LIKE '%gugatan sederhana%' ORDER BY p.tanggal_pendaftaran DESC LIMIT 500", tables: ["perkara", "perkara_putusan"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_pendaftaran", "tanggal_putusan"] }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 86, name: "SAPM Register Konsignasi", groupKey: "LAPORAN", sourceFiles: ["dok_sapm_register_konsignasi.php"], sourceEvidence: ["Legacy register konsignasi mencatat permohonan konsignasi."], query: q({ number: 86, name: "SAPM Register Konsignasi", sql: "SELECT p.perkara_id, p.nomor_perkara, p.jenis_perkara_nama, p.tanggal_pendaftaran, 100 AS score_percent FROM perkara p WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end AND LOWER(p.jenis_perkara_nama) LIKE '%konsignasi%' ORDER BY p.tanggal_pendaftaran DESC LIMIT 500", tables: ["perkara"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_pendaftaran"], securityStatus: "NEEDS_REVIEW", riskNotes: "Konsignasi bisa memakai tabel/klasifikasi khusus pada beberapa SIPP." }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 87, name: "SAPM Rekap Sidang Diluar Gedung", groupKey: "LAPORAN", sourceFiles: ["dok_sapm_rekap_data_perkara_sidang_diluar_gedung.php", "dok_sapm_rekap_data_perkara_sidang_diluar_gedung_detail.php"], sourceEvidence: ["Legacy merekap sidang di luar gedung dan detail per perkara."], query: q({ number: 87, name: "SAPM Rekap Sidang Diluar Gedung", sql: "SELECT js.perkara_id, p.nomor_perkara, js.tanggal_sidang, js.ruangan, js.agenda, 100 AS score_percent FROM perkara_jadwal_sidang js JOIN perkara p ON p.perkara_id = js.perkara_id WHERE js.tanggal_sidang BETWEEN :date_start AND :date_end AND (LOWER(COALESCE(js.ruangan, '')) LIKE '%luar%' OR LOWER(COALESCE(js.agenda, '')) LIKE '%luar gedung%') ORDER BY js.tanggal_sidang DESC LIMIT 500", tables: ["perkara_jadwal_sidang", "perkara"], columns: ["perkara_id", "nomor_perkara", "tanggal_sidang", "ruangan", "agenda"], securityStatus: "NEEDS_REVIEW", riskNotes: "Kolom ruangan/lokasi sidang perlu validasi versi SIPP." }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 88, name: "SAPM Rekap Layanan Hukum", groupKey: "LAPORAN", sourceFiles: ["dok_sapm_rekap_layanan_hukum.php"], sourceEvidence: ["Legacy merekap layanan hukum seperti prodeo, sidang keliling, posbakum, dan layanan terkait."], implementationStatus: "MANUAL_INPUT_READY", migrationStatus: "MANUAL_ONLY", safetyStatus: "MANUAL_INPUT_READY", calculationMode: "MANUAL_INPUT", resultType: "EXPORT_REFERENCE", noQueryReason: "Legacy menggabungkan beberapa input lokal pelaporan; ALETA perlu input manual/cache terverifikasi per jenis layanan sebelum otomatis." }),
  f({ number: 89, name: "LIPA 6 Perkara Putus", groupKey: "LAPORAN", sourceFiles: ["laporan_lipa_6.php"], sourceEvidence: ["Legacy LIPA 6 menghitung perkara putus dan klasifikasi laporan per periode."], query: q({ number: 89, name: "LIPA 6 Perkara Putus", sql: "SELECT pp.perkara_id, p.nomor_perkara, p.jenis_perkara_nama, pp.tanggal_putusan, 100 AS score_percent FROM perkara_putusan pp JOIN perkara p ON p.perkara_id = pp.perkara_id WHERE pp.tanggal_putusan BETWEEN :date_start AND :date_end ORDER BY pp.tanggal_putusan DESC LIMIT 500", tables: ["perkara_putusan", "perkara"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_putusan"] }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 90, name: "Rekapitulasi Data Perceraian", groupKey: "LAPORAN", sourceFiles: ["kontrol_rekapitulasi_data_perceraian.php", "laporan_input_rekapitulasi_data_perceraian.php"], sourceEvidence: ["Legacy rekap perceraian memakai perkara cerai, putusan, dan akta cerai."], query: q({ number: 90, name: "Rekapitulasi Data Perceraian", sql: "SELECT p.perkara_id, p.nomor_perkara, p.jenis_perkara_nama, pp.tanggal_putusan, ac.nomor_akta_cerai, ac.tgl_akta_cerai, 100 AS score_percent FROM perkara p LEFT JOIN perkara_putusan pp ON pp.perkara_id = p.perkara_id LEFT JOIN perkara_akta_cerai ac ON ac.perkara_id = p.perkara_id WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end AND LOWER(p.jenis_perkara_nama) LIKE '%cerai%' ORDER BY p.tanggal_pendaftaran DESC LIMIT 500", tables: ["perkara", "perkara_putusan", "perkara_akta_cerai"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_putusan", "nomor_akta_cerai", "tgl_akta_cerai"] }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 91, name: "Kinerja Tupoksi dan Ketepatan Input", groupKey: "KINERJA_SIPP", sourceFiles: ["kinerja_kepatuhan_tupoksi.php", "kinerja_kepatuhan_bukan_tupoksi.php", "kinerja_kepatuhan_tepat.php", "kinerja_kepatuhan_tidak_tepat.php"], sourceEvidence: ["Legacy memisahkan pekerjaan sesuai tupoksi, bukan tupoksi, tepat, dan tidak tepat."], query: q({ number: 91, name: "Kinerja Tupoksi dan Ketepatan Input", sql: "SELECT pr.perkara_id, p.nomor_perkara, pr.proses_nama, pr.tanggal_proses, pr.diinput_tanggal, 100 AS score_percent FROM perkara_proses pr JOIN perkara p ON p.perkara_id = pr.perkara_id WHERE pr.diinput_tanggal BETWEEN :date_start AND :date_end ORDER BY pr.diinput_tanggal DESC LIMIT 500", tables: ["perkara_proses", "perkara"], columns: ["perkara_id", "nomor_perkara", "proses_nama", "tanggal_proses", "diinput_tanggal"], securityStatus: "NEEDS_REVIEW", riskNotes: "Klasifikasi tupoksi/ketepatan membutuhkan threshold dan mapping user/tahapan yang harus dikonfigurasi admin." }), implementationStatus: "PARTIAL_READ_ONLY", migrationStatus: "PARTIAL", resultType: "SCORE" }),
  f({ number: 92, name: "Register Ekonomi Syariah", groupKey: "LAPORAN", sourceFiles: ["register_ekonomi_syariah.php"], sourceEvidence: ["Legacy register ekonomi syariah memfilter perkara ekonomi syariah."], query: q({ number: 92, name: "Register Ekonomi Syariah", sql: "SELECT p.perkara_id, p.nomor_perkara, p.jenis_perkara_nama, p.tanggal_pendaftaran, pp.tanggal_putusan, 100 AS score_percent FROM perkara p LEFT JOIN perkara_putusan pp ON pp.perkara_id = p.perkara_id WHERE p.tanggal_pendaftaran BETWEEN :date_start AND :date_end AND LOWER(p.jenis_perkara_nama) LIKE '%ekonomi syariah%' ORDER BY p.tanggal_pendaftaran DESC LIMIT 500", tables: ["perkara", "perkara_putusan"], columns: ["perkara_id", "nomor_perkara", "jenis_perkara_nama", "tanggal_pendaftaran", "tanggal_putusan"] }), resultType: "EXPORT_REFERENCE" }),
  f({ number: 93, name: "Register Surat Kuasa", groupKey: "LAPORAN", sourceFiles: ["register_surat_kuasa_pdf.php", "register_kuasa.php"], sourceEvidence: ["Legacy mencetak/register surat kuasa dari data kuasa hukum perkara."], query: q({ number: 93, name: "Register Surat Kuasa", sql: "SELECT pk.perkara_id, p.nomor_perkara, pk.nama AS nama_kuasa, pk.tanggal_surat_kuasa, 100 AS score_percent FROM perkara_pengacara pk JOIN perkara p ON p.perkara_id = pk.perkara_id WHERE pk.tanggal_surat_kuasa BETWEEN :date_start AND :date_end ORDER BY pk.tanggal_surat_kuasa DESC LIMIT 500", tables: ["perkara_pengacara", "perkara"], columns: ["perkara_id", "nomor_perkara", "nama_kuasa", "tanggal_surat_kuasa"], securityStatus: "NEEDS_REVIEW", riskNotes: "Duplikat fungsional dengan Register Kuasa Hukum, dipertahankan sebagai mapping cetak PDF legacy." }), resultType: "EXPORT_REFERENCE" }),
];

export const PENDUKUNG2018_FEATURE_BY_KEY = new Map(PENDUKUNG2018_FEATURES.map((feature) => [feature.featureKey, feature]));

export function listPendukung2018FeatureDefinitions() {
  return PENDUKUNG2018_FEATURES;
}

export function getPendukung2018FeatureDefinition(featureKeyValue: string) {
  return PENDUKUNG2018_FEATURE_BY_KEY.get(featureKeyValue);
}
